-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_vsku_vitem_cspu_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_vsku_vitem_cspu_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_vsku_vitem_cspu_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_vsku_vitem_cspu_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_vsku_vitem_cspu_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_vsku_vitem_cspu_1d.sql
-- deprecated: False
-- sha256: 0a4052c591054e7febdf8620384f610db82436698a8b592704e17b150b0cd4b8
CREATE TEMPORARY VIEW model_vitem_mapping_${grass_region_without_quote} AS
SELECT -- 如果一个rmodelid发生一天中只换cspuid，但是却不更换vitemid的情况，这时候关联键才会发生不够用，造成整天复算而非半天归属
     vitem_id
    ,cspu_id
    ,model_id
FROM srdi_mart.dim_sr_data_warehouse_vsku_model_mapping_hf
where grass_region in (${grass_region})  and local_date = ${local_date}
group by
     vitem_id
    ,cspu_id
    ,model_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW vsku_order_${grass_region_without_quote} AS
SELECT
    spu_vsku_item_id
   ,model_id
   ,sum(order_fraction) as order_cnt
FROM mp_order.dwd_spu_vsku_order_item_df__reg_live
where grass_region in (${grass_region})  and grass_date = ${local_date}
group by
    spu_vsku_item_id
   ,model_id
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_vsku_vitem_cspu_1d partition(grass_region = ${grass_region}, local_date = ${local_date})
SELECT
    vitem_id
   ,cspu_id
   ,sum(order_cnt) as order_cnt
FROM model_vitem_mapping_${grass_region_without_quote} a
left join vsku_order_${grass_region_without_quote} b on a.model_id=b.model_id and a.vitem_id=b.spu_vsku_item_id -- rsku可以绑定在同cspu的多个vmodel上，且一个rmodel一定对应的是不同的 vitem，这个我们做了限制
group by
    vitem_id
   ,cspu_id
;
