-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_state_level_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_state_level_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_state_level_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_state_level_metrics_1d_dim_join.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_exp_state_level_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_state_level_metrics_1d_dim_join.sql
-- deprecated: False
-- sha256: 658398e87ec1b1707b8fe51d6dd50e2b8474b0f14fc85269cfd576742dc7610b
CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
select
    user_id
    ,collect_list(exp_group_id) as exp_group_ids
from
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
where
    grass_region in (${grass_region})
    and local_date = ${local_date}
    and is_assignment_log = 1
    and is_rcmd_whitelist = 1
group by user_id
;

--sql_divide_splitter--

CREATE TEMPORARY VIEW br_registraton_state_${grass_region_without_quote} AS
SELECT DISTINCT
    user_id
    ,CASE
        WHEN registration_state = 'Sao Paulo' THEN 'Sao Paulo'
        WHEN registration_state = 'Rio de Janeiro' THEN 'Rio de Janeiro'
        ELSE 'others'
    END AS detail_state
FROM
    traffic.dwd_register_di__reg_live
WHERE
    ${grass_region} = 'BR'
    AND grass_region = ${grass_region}
    AND registration_country = ${grass_region}
    AND user_id > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW br_buyer_shipping_state_${grass_region_without_quote} AS
SELECT
    buyer_id AS user_id
    ,CASE
        WHEN buyer_shipping_address_state = 'São Paulo' THEN 'Sao Paulo'
        WHEN buyer_shipping_address_state = 'Rio de Janeiro' THEN 'Rio de Janeiro'
        ELSE 'others'
    END AS detail_state
    ,ROW_NUMBER() OVER (PARTITION BY buyer_id ORDER BY create_datetime DESC) AS order_dt
FROM
    mp_order.dwd_order_item_all_ent_df__reg_s0_live
WHERE
    ${grass_region} = 'BR'
    AND grass_date BETWEEN DATE_SUB(${local_date}, 59) AND ${local_date}
    AND grass_region = ${grass_region}
    AND tz_type = 'local'
    AND DATE(create_datetime) BETWEEN DATE_SUB(${local_date}, 29) AND ${local_date}
    AND buyer_shipping_address_state IS NOT NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW br_buyer_shipping_state_first_${grass_region_without_quote} AS
SELECT
    user_id
    ,detail_state
FROM
    br_buyer_shipping_state_${grass_region_without_quote}
WHERE
    order_dt = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW br_user_state_mapping_${grass_region_without_quote} AS
SELECT
    a.user_id AS user_id
    ,CASE
        WHEN b.user_id IS NOT NULL THEN b.detail_state
        ELSE a.detail_state
    END AS state
FROM
    br_registraton_state_${grass_region_without_quote} a
LEFT JOIN
    br_buyer_shipping_state_first_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY 1, 2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW vn_default_delivery_state_${grass_region_without_quote} AS
SELECT
    user_id
    ,major_region AS state
FROM
    mp_user.dim_user__reg_s0_live a
LEFT JOIN
    vnbi_mkt.shopee_vn_bi_team__vietnam_region_map_details b
ON
    a.default_delivery_address_state = b.province
WHERE
    ${grass_region} = 'VN'
    AND grass_region = ${grass_region}
    AND grass_date = ${local_date}
    AND is_backend_created = 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW vn_last_shipping_province_${grass_region_without_quote} AS
SELECT
    a.user_id AS user_id
    ,major_region AS state
FROM
    mp_user.dim_user__reg_s0_live a
LEFT JOIN
    vnbi_mkt.dim_user__address b
ON
    a.user_id = b.user_id
LEFT JOIN
    vnbi_mkt.shopee_vn_bi_team__vietnam_region_map_details c
ON
    b.last_shipping_province = c.province
WHERE
    ${grass_region} = 'VN'
    AND grass_region = ${grass_region}
    AND grass_date = ${local_date}
    AND is_backend_created = 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW vn_registration_state_${grass_region_without_quote} AS
SELECT
    a.user_id AS user_id
    ,major_region AS state
FROM
    mp_user.dim_user__reg_s0_live a
LEFT JOIN
    mp_user.dwd_register_ent_di__vn_s0_live b
ON
    a.user_id = b.user_id
LEFT JOIN
    vnbi_mkt.shopee_vn_bi_team__vietnam_region_map_details c
ON
    b.registration_state = c.province_reg
WHERE
    ${grass_region} = 'VN'
    AND a.grass_region = ${grass_region}
    AND a.grass_date = ${local_date}
    AND a.is_backend_created = 0
    AND b.registration_country = 'VN'
    AND b.registration_state != '-';

--sql_divide_splitter--

CREATE TEMPORARY VIEW vn_user_state_mapping_${grass_region_without_quote} AS
SELECT DISTINCT
    a.user_id AS user_id
    ,COALESCE(a.state, b.state, c.state, 'Unknown') AS state
FROM
    vn_default_delivery_state_${grass_region_without_quote} a
LEFT JOIN
    vn_last_shipping_province_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LEFT JOIN
    vn_registration_state_${grass_region_without_quote} c
ON
    a.user_id = c.user_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_state_mapping_${grass_region_without_quote} AS
SELECT
    user_id
    ,state
FROM
    br_user_state_mapping_${grass_region_without_quote}
UNION ALL
SELECT
    user_id
    ,state
FROM
    vn_user_state_mapping_${grass_region_without_quote};

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_metrics_raw_${grass_region_without_quote} AS
select
    coalesce(platform, 'NULL') AS platform
    ,coalesce(cast(is_ads as string), 'false') as is_ads
    ,scenario_tag
    ,feature_detail
    ,case
        when feature_detail = '__ALL__' then '__ALL__'
        else if(split(feature_detail,'-')[2] IS NOT NULL, split(feature_detail,'-')[2], split(feature_detail,'-')[1])
    end as target_type
    ,user_id

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
from
    srdi_mart.dws_sr_data_warehouse_platform_user_level_benchmark_1d
where
    grass_region = ${grass_region}
    and local_date = ${local_date}
    and user_id > 0
    and (
        scenario_tag like 'DA_%'
        or scenario_tag = 'dpm module Global Search business line Search'
        or scenario_tag = '__ALL__'
    );

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_metrics_${grass_region_without_quote} AS

select
    *
from
    user_level_metrics_raw_${grass_region_without_quote}

union all
select
    platform
    ,is_ads
    ,scenario_tag
    ,'__ALL__' as feature_detail
    ,target_type
    ,user_id

    ,sum(imp_cnt) as sum
    ,sum(click_cnt) as click_cnt
    ,sum(ppv_cnt) as ppv_cnt
    ,sum(ppv_cnt_exclude_isback) as ppv_cnt_exclude_isback
    ,sum(cart_cnt) as cart_cnt
    ,sum(order_cnt) as order_cnt
    ,sum(gmv) as gmv
    ,sum(pc2_gmv) as pc2_gmv
from
    user_level_metrics_raw_${grass_region_without_quote}
where
    scenario_tag != '__ALL__'
    and feature_detail != '__ALL__'
group by 1, 2, 3, 5, 6;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_exp_level_metrics_${grass_region_without_quote} AS
select
    COALESCE(state, 'Unknown') AS state
    ,platform
    ,is_ads
    ,scenario_tag
    ,feature_detail
    ,target_type
    ,t1.user_id

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
from
    user_level_metrics_${grass_region_without_quote} as t1
left join
    user_state_mapping_${grass_region_without_quote} as t2
on t1.user_id = t2.user_id
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_metrics_cube_${grass_region_without_quote} AS
select
    state
    ,coalesce(platform, '__ALL__') as platform
    ,coalesce(is_ads, '__ALL__') as is_ads
    ,scenario_tag
    ,feature_detail
    ,target_type
    ,user_id

    ,sum(imp_cnt) as imp_cnt
    ,sum(click_cnt) as click_cnt
    ,sum(ppv_cnt) as ppv_cnt
    ,sum(ppv_cnt_exclude_isback) as ppv_cnt_exclude_isback
    ,sum(cart_cnt) as cart_cnt
    ,sum(order_cnt) as order_cnt
    ,sum(gmv) as gmv
    ,sum(pc2_gmv) as pc2_gmv
from
    user_exp_level_metrics_${grass_region_without_quote}
group by grouping sets (
    -- Cube dimension is_ads, platform
     (state, scenario_tag, feature_detail, target_type, user_id, platform, is_ads)
    ,(state, scenario_tag, feature_detail, target_type, user_id, platform)
    ,(state, scenario_tag, feature_detail, target_type, user_id, is_ads)
    ,(state, scenario_tag, feature_detail, target_type, user_id)
);

--sql_divide_splitter--
CREATE TEMPORARY VIEW uu_data_${grass_region_without_quote} AS
SELECT
    *
    ,if(imp_cnt > 0 and user_id > 0, 1, 0) as imp_uu
    ,if(click_cnt > 0 and user_id > 0, 1, 0) as click_uu
    ,if(ppv_cnt > 0 and user_id > 0, 1, 0) as ppv_uu
    ,if(cart_cnt > 0 and user_id > 0, 1, 0) as cart_uu
    ,if(order_cnt > 0 and user_id > 0, 1, 0) as order_uu
FROM
    user_level_metrics_cube_${grass_region_without_quote};

--sql_divide_splitter--
create TEMPORARY VIEW map_data_${grass_region_without_quote} as
select
    state
    ,platform
    ,is_ads
    ,scenario_tag
    ,feature_detail
    ,target_type
    ,user_id
    ,array(
        imp_uu
        ,click_uu
        ,ppv_uu
        ,cart_uu
        ,order_uu
        ,imp_cnt
        ,click_cnt
        ,ppv_cnt
        ,ppv_cnt_exclude_isback
        ,cart_cnt
        ,order_cnt
        ,gmv
        ,pc2_gmv
    ) as metrics
from
    uu_data_${grass_region_without_quote};

--sql_divide_splitter--
CREATE TEMPORARY VIEW metric_table_${grass_region_without_quote} AS
SELECT
    state
    ,platform
    ,is_ads
    ,scenario_tag
    ,feature_detail
    ,target_type
    ,exp_sum(b.exp_group_ids, a.metrics) as exp_metrics
FROM
    map_data_${grass_region_without_quote} as a
inner join 
    user_exp_${grass_region_without_quote} as b
on 
    a.user_id = b.user_id
group by 1,2,3,4,5,6;

--sql_divide_splitter--
CREATE TEMPORARY VIEW platform_metrics_${grass_region_without_quote} AS
select
    state
    ,platform
    ,is_ads
    ,scenario_tag
    ,feature_detail
    ,target_type
    ,exp_info.exp_group_id as exp_group_id

    ,cast(exp_info.fields[0] as bigint) as imp_uu
    ,cast(exp_info.fields[1] as bigint) as click_uu
    ,cast(exp_info.fields[2] as bigint) as ppv_uu
    ,cast(exp_info.fields[3] as bigint) as cart_uu
    ,cast(exp_info.fields[4] as bigint) as order_uu
    ,cast(exp_info.fields[5] as bigint) as imp_cnt
    ,cast(exp_info.fields[6] as bigint) as click_cnt
    ,cast(exp_info.fields[7] as bigint) as ppv_cnt
    ,cast(exp_info.fields[8] as bigint) as ppv_cnt_exclude_isback
    ,cast(exp_info.fields[9] as bigint) as cart_cnt
    ,exp_info.fields[10] as order_cnt
    ,exp_info.fields[11] as gmv
    ,exp_info.fields[12] as pc2_gmv
from
    metric_table_${grass_region_without_quote}
    LATERAL VIEW EXPLODE(exp_metrics) as exp_info;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_gmv_raw_${grass_region_without_quote} AS
select
    user_id
    ,scenario_tag
    ,feature_detail
    ,coalesce(cast(is_ads as string), 'false') as is_ads
    ,gmv
    ,pc2_gmv
    ,imp_cnt
    ,order_cnt
from
    srdi_mart.dws_sr_data_warehouse_platform_user_level_benchmark_1d
where
    grass_region = ${grass_region}
    and local_date = ${local_date}
    and user_id > 0
    and (
        replace(scenario_tag, 'DA_', '') in (
            'Daily Discover', 'You May Also Like', 'Cart_Unify', 'Buy Again (Me Page)', 'Cart Recommendation',
            'odp_ymal-order_detail', 'Order Successful Recommendation', 'mpp_ymal-order_list',
            'Me YMAL', 'Shop YMAL', 'YMAL_Cart', 'RCMD Unify'
        )
        or scenario_tag = 'dpm module Global Search business line Search'
        or scenario_tag = '__ALL__'
    )
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_gmv_${grass_region_without_quote} AS
select
    user_id
    ,scenario_tag
    ,'__ALL__' as target_type
    ,is_ads
    ,sum(gmv) as gmv
    ,sum(pc2_gmv) as pc2_gmv
    ,sum(imp_cnt) as imp_cnt
    ,sum(order_cnt) as order_cnt
from
    user_level_gmv_raw_${grass_region_without_quote}
where
    feature_detail = '__ALL__'
group by 1, 2, 4

union all
select
    user_id
    ,scenario_tag
    ,if(split(feature_detail,'-')[2] IS NOT NULL, split(feature_detail,'-')[2], split(feature_detail,'-')[1]) as target_type
    ,is_ads
    ,sum(gmv) as gmv
    ,sum(pc2_gmv) as pc2_gmv
    ,sum(imp_cnt) as imp_cnt
    ,sum(order_cnt) as order_cnt
from
    user_level_gmv_raw_${grass_region_without_quote}
where
    feature_detail != '__ALL__'
group by 1, 2, 3, 4
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_gmv_state_${grass_region_without_quote} AS
select
    t1.user_id
    ,COALESCE(state, 'Unknown') AS state
    ,scenario_tag
    ,target_type
    ,is_ads
    ,gmv
    ,pc2_gmv
    ,imp_cnt
    ,order_cnt
from
    user_level_gmv_${grass_region_without_quote} as t1
left join
    user_state_mapping_${grass_region_without_quote} as t2
on t1.user_id = t2.user_id
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_level_gmv_cube_${grass_region_without_quote} AS
select
    state
    ,scenario_tag
    ,target_type
    ,coalesce(is_ads, '__ALL__') as is_ads
    ,user_id
    ,coalesce(sum(gmv), 0) as gmv
    ,coalesce(sum(gmv) / sum(order_cnt), 0) as abs
    ,coalesce(sum(pc2_gmv), 0) as pc2_gmv
    ,coalesce(sum(imp_cnt), 0) as imp_cnt
from
    user_level_gmv_state_${grass_region_without_quote}
group by grouping sets (
    (state, scenario_tag, target_type, is_ads, user_id)
    ,(state, scenario_tag, target_type, user_id)
);

--sql_divide_splitter--
CREATE TEMPORARY VIEW abs_995_val_${grass_region_without_quote} AS
select
    case
        when feature_group = 'Search' then 'dpm module Global Search business line Search'
        when feature_group = 'all' then '__ALL__'
        when feature_group = 'Cart Unify' then 'DA_Cart_Unify'
        when feature_group = 'Order Detail Page YMAL' then 'DA_odp_ymal-order_detail'
        when feature_group = 'My Purchase Page YMAL' then 'DA_mpp_ymal-order_list'
        else concat('DA_', feature_group)
     end as scenario_tag
    ,case when is_ads = 'all' then '__ALL__' else is_ads end as is_ads
    ,max(val) as abs_995
from
    srdi_mart.ads_rcmd_platform_scenario_level_outlier_di
where
    grass_region = ${grass_region}
    and grass_date = ${local_date}
    and outlier_type = 'abs'
    and percentile = 0.995
group by 1, 2;

--sql_divide_splitter--
CREATE TEMPORARY VIEW metrics_995_map_data_${grass_region_without_quote} AS
select
    state
    ,user_id
    ,t1.is_ads
    ,t1.scenario_tag
    ,target_type
    ,array(
        sum(gmv) -- gmv_995
        ,sum(pc2_gmv) -- pc2_gmv_995
        ,max(if(imp_cnt > 0 and user_id > 0, 1, 0)) -- imp_uu
    ) as metrics
from
    user_level_gmv_cube_${grass_region_without_quote} as t1
left join
    abs_995_val_${grass_region_without_quote} as t2
on
    t1.scenario_tag = t2.scenario_tag
    and t1.is_ads = t2.is_ads
where
    coalesce(abs, 0) <= abs_995
group by 1, 2, 3, 4, 5;

--sql_divide_splitter--
CREATE TEMPORARY VIEW metrics_995_exp_${grass_region_without_quote} AS
select
    state
    ,is_ads
    ,scenario_tag
    ,target_type
    ,exp_sum(b.exp_group_ids, a.metrics) as exp_metrics
from
    metrics_995_map_data_${grass_region_without_quote} as a
inner join 
    user_exp_${grass_region_without_quote} as b
on 
    a.user_id = b.user_id
group by 1,2,3,4;

--sql_divide_splitter--
CREATE TEMPORARY VIEW metrics_995_${grass_region_without_quote} AS
select
    state
    ,exp_info.exp_group_id as exp_group_id
    ,'__ALL__' as platform
    ,is_ads
    ,scenario_tag
    ,target_type
    ,'__ALL__' as feature_detail

    ,exp_info.fields[0] as gmv_995
    ,exp_info.fields[1] as pc2_gmv_995
    ,cast(exp_info.fields[2] as bigint) as imp_uu_995
from
    metrics_995_exp_${grass_region_without_quote}
    LATERAL VIEW EXPLODE(exp_metrics) as exp_info;

--sql_divide_splitter--
CREATE TEMPORARY VIEW ads_metrics_raw_${grass_region_without_quote} AS
select
    case
        when entrance = 1 then 'dpm module Global Search business line Search'
        when entrance in (3, 25, 31, 32, 56) then 'DA_Daily Discover'
        when entrance = 4 then 'DA_You May Also Like'
        when entrance = 8 then 'DA_Cart Recommendation'
        when entrance = 9 then 'DA_Order Successful Recommendation'
        when entrance = 10 then 'DA_odp_ymal-order_detail'
        when entrance = 11 then 'DA_mpp_ymal-order_list'
        when entrance = 40 then 'DA_Me YMAL'
        when entrance = 45 then 'DA_Shop YMAL'
        when entrance in (7, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 26, 41, 43) then 'Game'
        else 'Others'
    end as scenario_tag
    ,user_id
    ,sum(coalesce(expenditure_amt_usd, 0)) as revenue_usd
    ,sum(coalesce(ads_order_gmv_usd, 0)) as ads_gmv_usd
    ,sum(coalesce(broad_gmv_amt_local, 0)) as ads_broad_gmv_local
    ,sum(coalesce(broad_order_cnt, 0)) as ads_broad_order_cnt
    ,sum(coalesce(order_cnt, 0)) as ads_order_cnt
    ,sum(coalesce(impression_cnt, 0)) as ads_imp_cnt
    ,sum(coalesce(click_cnt, 0)) as ads_click_cnt
from mp_paidads.dwd_advertise_performance_di__reg_s0_live
where
    grass_region in (${grass_region})
    and grass_date = ${local_date}
    and tz_type = 'local'
    and ads_id > 0
group by 1, 2
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW fx_rate_${grass_region_without_quote} AS
SELECT
    FIRST(exchange_rate) AS fx
FROM
    mp_order.dim_exchange_rate__reg_s0_live
WHERE
    grass_date = ${local_date}
    AND grass_region = ${grass_region}
;

--sql_divide_splitter--
create TEMPORARY VIEW ads_metrics_map_data_${grass_region_without_quote} as
select
    COALESCE(state, 'Unknown') AS state
    ,scenario_tag
    ,t1.user_id
    ,array(
        sum(revenue_usd)
        ,sum(ads_gmv_usd)
        ,sum(ads_broad_gmv_local)/avg(fx)
        ,sum(ads_broad_order_cnt)
        ,sum(ads_order_cnt)
        ,sum(ads_imp_cnt)
        ,sum(ads_click_cnt)
    ) as metrics
from
    ads_metrics_raw_${grass_region_without_quote} as t1
left join
    user_state_mapping_${grass_region_without_quote} as t2
on t1.user_id = t2.user_id
left join
    fx_rate_${grass_region_without_quote} as t3
group by 1, 2, 3;

--sql_divide_splitter--
CREATE TEMPORARY VIEW ads_metrics_table_${grass_region_without_quote} AS
select
    state
    ,scenario_tag
    ,exp_sum(b.exp_group_ids, a.metrics) as exp_metrics
from
    ads_metrics_map_data_${grass_region_without_quote} as a
inner join
    user_exp_${grass_region_without_quote} as b
on
    a.user_id = b.user_id
group by 1,2;

--sql_divide_splitter--
CACHE TABLE ads_metrics_explode_${grass_region_without_quote} AS
select
    state
    ,scenario_tag
    ,exp_info.exp_group_id as exp_group_id
    ,exp_info.fields[0] as revenue_usd
    ,exp_info.fields[1] as ads_gmv_usd
    ,exp_info.fields[2] as ads_broad_gmv_usd
    ,exp_info.fields[3] as ads_broad_order_cnt
    ,exp_info.fields[4] as ads_order_cnt
    ,cast(exp_info.fields[5] as bigint) as ads_imp_cnt
    ,cast(exp_info.fields[6] as bigint) as ads_click_cnt
from
    ads_metrics_table_${grass_region_without_quote}
    LATERAL VIEW EXPLODE(exp_metrics) as exp_info;

--sql_divide_splitter--
CREATE TEMPORARY VIEW ads_metrics_cube_${grass_region_without_quote} AS
select
    state
    ,exp_group_id
    ,'__ALL__' as platform
    ,'true' as is_ads
    ,coalesce(scenario_tag, '__ALL__') as scenario_tag
    ,'__ALL__' as feature_detail
    ,'__ALL__' as target_type

    ,sum(revenue_usd) as revenue_usd
    ,sum(ads_gmv_usd) as ads_gmv_usd
    ,sum(ads_broad_gmv_usd) as ads_broad_gmv_usd
    ,sum(ads_broad_order_cnt) as ads_broad_order_cnt
    ,sum(ads_order_cnt) as ads_order_cnt
    ,sum(ads_imp_cnt) as ads_imp_cnt
    ,sum(ads_click_cnt) as ads_click_cnt
from
    ads_metrics_explode_${grass_region_without_quote}
group by grouping sets (
    (state, exp_group_id, scenario_tag)
    ,(state, exp_group_id)
)

union all
select
    state
    ,exp_group_id
    ,'__ALL__' as platform
    ,'true' as is_ads
    ,'DA_Cart_Unify' as scenario_tag
    ,'__ALL__' as feature_detail
    ,'__ALL__' as target_type

    ,sum(revenue_usd) as revenue_usd
    ,sum(ads_gmv_usd) as ads_gmv_usd
    ,sum(ads_broad_gmv_usd) as ads_broad_gmv_usd
    ,sum(ads_broad_order_cnt) as ads_broad_order_cnt
    ,sum(ads_order_cnt) as ads_order_cnt
    ,sum(ads_imp_cnt) as ads_imp_cnt
    ,sum(ads_click_cnt) as ads_click_cnt
from
    ads_metrics_explode_${grass_region_without_quote}
where scenario_tag in (
    'DA_Cart Recommendation', 'DA_Order Successful Recommendation',
    'DA_odp_ymal-order_detail', 'DA_mpp_ymal-order_list',
    'DA_Me YMAL', 'DA_Shop YMAL'
)
group by 1, 2

union all
select
    state
    ,exp_group_id
    ,'__ALL__' as platform
    ,'true' as is_ads
    ,'DA_RCMD Unify' as scenario_tag
    ,'__ALL__' as feature_detail
    ,'__ALL__' as target_type

    ,sum(revenue_usd) as revenue_usd
    ,sum(ads_gmv_usd) as ads_gmv_usd
    ,sum(ads_broad_gmv_usd) as ads_broad_gmv_usd
    ,sum(ads_broad_order_cnt) as ads_broad_order_cnt
    ,sum(ads_order_cnt) as ads_order_cnt
    ,sum(ads_imp_cnt) as ads_imp_cnt
    ,sum(ads_click_cnt) as ads_click_cnt
from
    ads_metrics_explode_${grass_region_without_quote}
where scenario_tag in (
    'DA_Cart Recommendation', 'DA_Order Successful Recommendation',
    'DA_odp_ymal-order_detail', 'DA_mpp_ymal-order_list',
    'DA_Me YMAL', 'DA_Shop YMAL',
    'DA_You May Also Like', 'DA_Daily Discover'
)
group by 1, 2

union all
select
    state
    ,exp_group_id
    ,'__ALL__' as platform
    ,'true' as is_ads
    ,'DA_YMAL_Cart' as scenario_tag
    ,'__ALL__' as feature_detail
    ,'__ALL__' as target_type

    ,sum(revenue_usd) as revenue_usd
    ,sum(ads_gmv_usd) as ads_gmv_usd
    ,sum(ads_broad_gmv_usd) as ads_broad_gmv_usd
    ,sum(ads_broad_order_cnt) as ads_broad_order_cnt
    ,sum(ads_order_cnt) as ads_order_cnt
    ,sum(ads_imp_cnt) as ads_imp_cnt
    ,sum(ads_click_cnt) as ads_click_cnt
from
    ads_metrics_explode_${grass_region_without_quote}
where scenario_tag in (
    'DA_Cart Recommendation', 'DA_Order Successful Recommendation',
    'DA_odp_ymal-order_detail', 'DA_mpp_ymal-order_list',
    'DA_Me YMAL', 'DA_Shop YMAL',
    'DA_You May Also Like'
)
group by 1, 2
;

--sql_divide_splitter--
INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_platform_exp_state_level_metrics_1d
PARTITION (exp_type = 'dim_join', grass_region = ${grass_region}, local_date = ${local_date})

select
    coalesce(t1.state, t3.state) as state
    ,coalesce(t1.exp_group_id, t3.exp_group_id) as exp_group_id
    ,coalesce(t1.platform, t3.platform) as platform
    ,coalesce(t1.is_ads, t3.is_ads) as is_ads
    ,coalesce(t1.scenario_tag, t3.scenario_tag) as scenario_tag
    ,coalesce(t1.feature_detail, t3.feature_detail) as feature_detail
    ,coalesce(t1.target_type, t3.target_type) as target_type

    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv

    ,gmv_995
    ,pc2_gmv_995
    ,imp_uu_995

    ,revenue_usd
    ,ads_gmv_usd
    ,ads_broad_gmv_usd
    ,ads_broad_order_cnt
    ,ads_order_cnt
    ,ads_imp_cnt
    ,ads_click_cnt

from
    platform_metrics_${grass_region_without_quote} as t1
left join
    metrics_995_${grass_region_without_quote} as t2
on
    t1.state = t2.state
    and t1.exp_group_id = t2.exp_group_id
    and t1.platform = t2.platform
    and t1.is_ads = t2.is_ads
    and t1.scenario_tag = t2.scenario_tag
    and t1.feature_detail = t2.feature_detail
    and t1.target_type = t2.target_type
full outer join
    ads_metrics_cube_${grass_region_without_quote} as t3
on
    t1.state = t3.state
    and t1.exp_group_id = t3.exp_group_id
    and t1.platform = t3.platform
    and t1.is_ads in ('true', '__ALL__')
    and t1.scenario_tag = t3.scenario_tag
    and t1.feature_detail = t3.feature_detail
    and t1.target_type = t3.target_type
