-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d.sql
-- deprecated: False
-- sha256: 7596affbb616ca237035445455113a3ccffac2557017f4f080b8ade0869a92e4
CREATE TEMPORARY VIEW exp_info_${grass_region_without_quote} as
select group_id as exp_group_id
from abtest.shopee_experiment_admin_db__group_dimension_tab__reg_continuous_s0_live
where experiment_id in (163151,163152,163153)
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW user_exp_raw_${grass_region_without_quote} as
SELECT
    user_id
     ,exp_group_id
FROM srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE grass_region in (${grass_region}) AND local_date = ${local_date} AND is_assignment_log = 1
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
SELECT
    user_id
     ,a.exp_group_id
FROM user_exp_raw_${grass_region_without_quote} a
inner join exp_info_${grass_region_without_quote} b on a.exp_group_id = b.exp_group_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_raw_${grass_region_without_quote} as
select local_hour
     ,user_id
     ,is_item_card
     ,is_ads
     ,mapping_general
     ,shop_id
     ,item_id
     ,model_id
     ,sum(imp_cnt) imp_cnt
     ,sum(click_cnt) click_cnt
     ,sum(order_cnt) order_cnt
     ,sum(gmv) gmv
     ,sum(pc2_gmv) pc2_gmv
FROM srdi_mart.dws_sr_data_warehouse_tc_pb_basic_aggr_1d
WHERE grass_region IN (${grass_region}) AND local_date = ${local_date}
and mapping_general in ('Search', 'Daily Discover', 'You May Also Like', 'Post Purchase','S&R__ALL__')
group by 1,2,3,4,5,6,7,8
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_exp_step1_${grass_region_without_quote} as
SELECT a.*
    ,b.exp_group_id
from traffic_raw_${grass_region_without_quote} a
INNER JOIN user_exp_${grass_region_without_quote} b
on a.user_id = b.user_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_exp_${grass_region_without_quote} as
select *
from traffic_exp_step1_${grass_region_without_quote}
union ALL
select local_hour
 ,user_id
 ,is_item_card
 ,is_ads
 ,'RCMD' as mapping_general
 ,shop_id
 ,item_id
 ,model_id
 ,sum(imp_cnt) imp_cnt
 ,sum(click_cnt) click_cnt
 ,sum(order_cnt) order_cnt
 ,sum(gmv) gmv
 ,sum(pc2_gmv) pc2_gmv
 ,exp_group_id
from traffic_exp_step1_${grass_region_without_quote}
where mapping_general in ('Daily Discover', 'You May Also Like', 'Post Purchase')
group by 1,2,3,4,5,6,7,8, 14
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_exp_aggr_${grass_region_without_quote} as
select local_hour
     ,exp_group_id
     ,is_item_card
     ,is_ads
     ,mapping_general
     ,shop_id
     ,item_id
     ,model_id
     ,sum(imp_cnt) imp_cnt
     ,sum(click_cnt) click_cnt
     ,sum(order_cnt) order_cnt
     ,sum(gmv) gmv
     ,sum(pc2_gmv) pc2_gmv
from traffic_exp_${grass_region_without_quote}
group by 1,2,3,4,5,6,7,8
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW all_cspu_model_${grass_region_without_quote} as
SELECT model_id
     ,item_id
     ,cspu_id
     ,local_hour
from srdi_mart.dim_sr_data_warehouse_pb_all_cspu_link_analysis_hf
where grass_region = ${grass_region}
  and local_date = ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_model_list_raw_${grass_region_without_quote} as
SELECT cspu_id
     ,shop_id
     ,model_id
     ,item_id
     ,business_type
     ,local_hour
from srdi_mart.dim_sr_data_warehouse_pb_one_variation_model_analysis_hf
where grass_region = ${grass_region} AND local_date = ${local_date}
group by 1,2,3,4,5,6
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_model_list_${grass_region_without_quote} as
select a.model_id
     ,a.item_id
     ,coalesce(b.type,'non-scs') as shop_scs_type
     ,business_type
     ,a.local_hour
from cheapest_model_list_raw_${grass_region_without_quote} a
left join (
    select type
         ,shop_id
    from regds_listing.dim_scs_shop_list_df
    where grass_region = ${grass_region}
      and type in ('scs-local','scs-cb')
)b
on a.shop_id = b.shop_id
inner join all_cspu_model_${grass_region_without_quote} c
on a.local_hour = c.local_hour
and a.model_id = c.model_id
and a.cspu_id = c.cspu_id
group by 1,2,3,4,5
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_item_list_${grass_region_without_quote} as
select item_id
     ,shop_scs_type
     ,business_type
     ,local_hour
from cheapest_model_list_${grass_region_without_quote}
group by 1,2,3,4
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_list_${grass_region_without_quote} as
select cspu_id
     ,business_type
     ,local_hour
from cheapest_model_list_raw_${grass_region_without_quote}
group by 1,2,3
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_all_model_${grass_region_without_quote} as
SELECT model_id
    ,item_id
    ,business_type
    ,a.local_hour
from all_cspu_model_${grass_region_without_quote} a
inner join cheapest_cspu_list_${grass_region_without_quote} b
on a.local_hour = b.local_hour
and a.cspu_id = b.cspu_id
group by 1,2,3,4
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW winner_cspu_model_list_${grass_region_without_quote} as
select model_id
    ,local_hour
from cheapest_cspu_all_model_${grass_region_without_quote}
where business_type in (3,4)
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_model_list_${grass_region_without_quote} as
select model_id
     ,local_hour
from cheapest_cspu_all_model_${grass_region_without_quote}
where business_type in (1,2)
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW winner_cspu_item_list_${grass_region_without_quote} as
select item_id
     ,local_hour
from cheapest_cspu_all_model_${grass_region_without_quote}
where business_type in (3,4)
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_item_list_${grass_region_without_quote} as
select item_id
     ,local_hour
from cheapest_cspu_all_model_${grass_region_without_quote}
where business_type in (1,2)
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_cheapest_step1_${grass_region_without_quote} as
SELECT a.local_hour
     ,exp_group_id
     ,is_item_card
     ,is_ads
     ,mapping_general
     ,b.shop_scs_type
     ,b.business_type
     ,sum(imp_cnt) item_imp_cnt
     ,sum(click_cnt) item_click_cnt
     ,sum(order_cnt) item_order_cnt
     ,sum(gmv) item_gmv
     ,sum(case when c.model_id is not null then order_cnt end) model_order_cnt
     ,sum(case when c.model_id is not null then gmv end) model_gmv
from traffic_exp_aggr_${grass_region_without_quote} a
inner join cheapest_item_list_${grass_region_without_quote} b
on a.local_hour = b.local_hour
and a.item_id = b.item_id
left join cheapest_model_list_${grass_region_without_quote} c
on a.local_hour = c.local_hour
and a.model_id = c.model_id
and b.business_type = c.business_type
group by 1,2,3,4,5,6,7
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_cheapest_${grass_region_without_quote} as
SELECT local_hour
     ,exp_group_id
     ,if(grouping(is_item_card) = 1, '__ALL__', is_item_card) is_item_card
     ,if(grouping(is_ads) = 1, '__ALL__', is_ads) is_ads
     ,mapping_general
     ,shop_scs_type
     ,business_type
     ,sum(item_imp_cnt) item_imp_cnt
     ,sum(item_click_cnt) item_click_cnt
     ,sum(item_order_cnt) item_order_cnt
     ,sum(item_gmv) item_gmv
     ,sum(model_order_cnt) model_order_cnt
     ,sum(model_gmv) model_gmv
    from exp_cheapest_step1_${grass_region_without_quote}
group by
    GROUPING SETS (
       (local_hour,exp_group_id,is_item_card,is_ads,mapping_general,shop_scs_type,business_type),
       (local_hour,exp_group_id,is_ads,mapping_general,shop_scs_type,business_type),
       (local_hour,exp_group_id,is_item_card,mapping_general,shop_scs_type,business_type),
       (local_hour,exp_group_id,mapping_general,shop_scs_type,business_type)
    )
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_exp_cspu_${grass_region_without_quote} as
select a.local_hour
     ,exp_group_id
     ,if(grouping(is_item_card) = 1, '__ALL__', is_item_card) is_item_card
     ,if(grouping(is_ads) = 1, '__ALL__', is_ads) is_ads
     ,mapping_general
     ,sum(case when d.item_id is not null then imp_cnt else 0 end) winner_cspu_imp_cnt
     ,sum(case when e.item_id is not null then imp_cnt else 0 end) cheapest_cspu_imp_cnt
     ,sum(case when d.item_id is not null or e.item_id is not null then imp_cnt else 0 end) platform_cspu_imp_cnt
     ,sum(case when b.model_id is not null then order_cnt else 0 end) winner_cspu_order_cnt
     ,sum(case when c.model_id is not null then order_cnt else 0 end) cheapest_cspu_order_cnt
     ,sum(case when b.model_id is not null or c.model_id is not null then order_cnt else 0 end) platform_cspu_order_cnt
from traffic_exp_aggr_${grass_region_without_quote} a
left join winner_cspu_model_list_${grass_region_without_quote} b
on a.local_hour = b.local_hour
and a.model_id = b.model_id
left join cheapest_cspu_model_list_${grass_region_without_quote} c
on a.local_hour = c.local_hour
and a.model_id = c.model_id
left join winner_cspu_item_list_${grass_region_without_quote} d
on a.local_hour = d.local_hour
and a.item_id = d.item_id
left join cheapest_cspu_item_list_${grass_region_without_quote} e
on a.local_hour = e.local_hour
and a.item_id = e.item_id
group by grouping sets(
    (a.local_hour,exp_group_id,is_item_card,is_ads,mapping_general),
    (a.local_hour,exp_group_id,is_ads,mapping_general),
    (a.local_hour,exp_group_id,is_item_card,mapping_general),
    (a.local_hour,exp_group_id,mapping_general)
    )
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW scene_995_threshold_${grass_region_without_quote} as
SELECT
    *
FROM srdi_mart.dws_sr_data_warehouse_tc_scene_995_threshold_1d
WHERE grass_region IN (${grass_region}) AND local_date = ${local_date}
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW scene_data_step1_${grass_region_without_quote} as
SELECT exp_group_id
     ,user_id
     ,is_item_card
     ,is_ads
     ,mapping_general
     ,sum(imp_cnt) imp_cnt
     ,sum(click_cnt) click_cnt
     ,sum(order_cnt) order_cnt
     ,sum(gmv) gmv
     ,sum(pc2_gmv) pc2_gmv
     ,coalesce(sum(gmv)/sum(order_cnt),0) as gpo
from traffic_exp_${grass_region_without_quote}
GROUP BY 1,2,3,4,5
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW scene_data_${grass_region_without_quote} as
select exp_group_id
     ,if(grouping(a.is_item_card) = 1, '__ALL__', a.is_item_card) is_item_card
     ,if(grouping(a.is_ads) = 1, '__ALL__', a.is_ads) is_ads
     ,a.mapping_general
     ,count(distinct case when imp_cnt>0 then user_id end) scene_imp_uv_1d
     ,sum(imp_cnt) scene_imp_cnt_1d
     ,sum(order_cnt) scene_order_cnt_1d
     ,sum(if(gpo<=gpo_pct,gmv,0)) scene_gmv_995_1d
     ,sum(pc2_gmv) scene_pc2_gmv_1d
     ,sum(gmv) scene_gmv_1d
from scene_data_step1_${grass_region_without_quote} a
left join scene_995_threshold_${grass_region_without_quote} b
on a.is_ads = b.is_ads
and a.is_item_card = b.is_item_card
and a.mapping_general = b.mapping_general
GROUP BY GROUPING SETS (
    (exp_group_id,a.is_item_card,a.is_ads,a.mapping_general),
    (exp_group_id,a.is_ads,a.mapping_general),
    (exp_group_id,a.is_item_card,a.mapping_general),
    (exp_group_id,a.mapping_general)
    )
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW ads_raw_step1_${grass_region_without_quote} as
select
    user_id
     ,expenditure_amt_usd as ads_revenue_usd
     ,c.traffic_type as common_feature
from mp_paidads.dwd_advertise_performance_di__reg_s0_live a
    left join (
    select
    entrance
        ,max(traffic_type) as traffic_type
    from mp_paidads.dim_entry_point_mapping_v2
    group by 1
    ) as c on a.entrance = c.entrance
where grass_region in (${grass_region}) and grass_date=${local_date} and tz_type='local'
  and c.traffic_type in ('Search','You May Also Like','Daily Discover','Post Purchase')
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW ads_raw_step2_${grass_region_without_quote} AS
select
    user_id
     ,common_feature
     ,sum(ads_revenue_usd) as ads_revenue_usd
from ads_raw_step1_${grass_region_without_quote}
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW ads_${grass_region_without_quote} as
select
    user_id
     ,common_feature
     ,ads_revenue_usd
from ads_raw_step2_${grass_region_without_quote}
union all
select
    user_id
     ,'S&R__ALL__' as common_feature
     ,sum(ads_revenue_usd) as ads_revenue_usd
from ads_raw_step2_${grass_region_without_quote}
group by 1,2
union all
select
    user_id
     ,'RCMD' as common_feature
     ,sum(ads_revenue_usd) as ads_revenue_usd
from ads_raw_step2_${grass_region_without_quote}
where common_feature in ('You May Also Like','Daily Discover','Post Purchase')
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_ads_${grass_region_without_quote} as
SELECT
    exp_group_id
     ,common_feature
     ,sum(ads_revenue_usd) as scene_ads_rev_usd_1d
FROM user_exp_${grass_region_without_quote} a
         left join ads_${grass_region_without_quote} b on a.user_id=b.user_id
GROUP BY 1,2
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_tc_pb_one_variation_exp_scene_general_upgrade_1d partition (grass_region = ${grass_region},local_date = ${local_date}, local_hour)
select a.exp_group_id
     ,a.is_ads
     ,a.is_item_card
     ,a.mapping_general
     ,shop_scs_type
     ,business_type
     ,coalesce(item_imp_cnt,0) item_imp_cnt
     ,coalesce(item_click_cnt,0) item_click_cnt
     ,coalesce(item_order_cnt,0) item_order_cnt
     ,coalesce(item_gmv,0) item_gmv
     ,coalesce(model_order_cnt,0) model_order_cnt
     ,coalesce(model_gmv,0) model_gmv
     ,null as scene_imp_uv
     ,null as scene_imp_cnt
     ,null as scene_order_cnt
     ,null as scene_gmv_995
     ,null as scene_pc2_gmv
     ,null as scene_ads_rev_usd
     ,coalesce(scene_imp_uv_1d,0) scene_imp_uv_1d
     ,coalesce(scene_imp_cnt_1d,0) scene_imp_cnt_1d
     ,coalesce(scene_order_cnt_1d,0) scene_order_cnt_1d
     ,coalesce(scene_gmv_995_1d,0) scene_gmv_995_1d
     ,coalesce(scene_pc2_gmv_1d,0) scene_pc2_gmv_1d
     ,scene_ads_rev_usd_1d
     ,coalesce(if(business_type in (3,4),winner_cspu_order_cnt,cheapest_cspu_order_cnt),0) cheapest_cspu_order_cnt
     ,coalesce(platform_cspu_order_cnt ,0) platform_cheapest_cspu_order_cnt
     ,coalesce(scene_gmv_1d,0) scene_gmv_1d
     ,coalesce(if(business_type in (3,4),winner_cspu_imp_cnt,cheapest_cspu_imp_cnt),0) cheapest_cspu_imp_cnt
     ,coalesce(platform_cspu_imp_cnt ,0) platform_cheapest_cspu_imp_cnt
     ,a.local_hour
from exp_cheapest_${grass_region_without_quote} a
left join scene_data_${grass_region_without_quote} b
on a.exp_group_id = b.exp_group_id
and a.is_item_card = b.is_item_card
and a.mapping_general = b.mapping_general
and a.is_ads = b.is_ads
left join exp_ads_${grass_region_without_quote} c
on a.exp_group_id = c.exp_group_id
and a.mapping_general = c.common_feature
and a.is_ads = '__ALL__'
and a.is_item_card = '__ALL__'
left join traffic_exp_cspu_${grass_region_without_quote} d
on a.local_hour = d.local_hour
and a.exp_group_id = d.exp_group_id
and a.is_item_card = d.is_item_card
and a.is_ads = d.is_ads
and a.mapping_general = d.mapping_general
;
