-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_duration_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_duration_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_duration_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_homepage_user_duration_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_homepage_user_duration_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_homepage_user_duration_1d.sql
-- deprecated: False
-- sha256: e02448bdbc0dd64d0c50c7e0de48fbbea98d3f5e2ec5aa94cf9f750d29930024

insert overwrite table ${schema}.ads_sr_data_warehouse_homepage_user_duration_1d
partition(grass_region=${grass_region}, local_date=${local_date})
select
     sum(dd_cover_duration_1d) as dd_cover_duration_1d
    ,sum(dd_pdp_duration_1d) as dd_pdp_duration_1d
    ,sum(dd_minifeed_duration_1d) as dd_minifeed_duration_1d
    ,sum(dd_video_duration_1d) as dd_video_duration_1d
    ,sum(dd_live_duration_1d) as dd_live_duration_1d
    ,sum(dd_mixfeed_duration_1d) as dd_mixfeed_duration_1d
    ,sum(dd_minifeed_pdp_duraion_1d) as dd_minifeed_pdp_duraion_1d
    ,sum(dd_video_pdp_duration_1d) as dd_video_pdp_duration_1d
    ,sum(dd_live_pdp_duration_1d) as dd_live_pdp_duration_1d
    ,sum(dd_mixfeed_pdp_duration_1d) as dd_mixfeed_pdp_duration_1d
    ,sum(platform_duration_1d) as platform_duration_1d
    ,sum(dd_video_landing_livestream_duration_1d) as dd_video_landing_livestream_duration_1d
    ,sum(dd_item_mix_landing_livestream_duration_1d) as dd_item_mix_landing_livestream_duration_1d
from ${schema}.dws_sr_data_warehouse_homepage_user_duration_1d
where grass_region = ${grass_region}
      and local_date = ${local_date}
