-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_platform_smart_ui_best_performance_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_platform_smart_ui_best_performance_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_platform_smart_ui_best_performance_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_platform_smart_ui_best_performance_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_platform_smart_ui_best_performance_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_platform_smart_ui_best_performance_1d.sql
-- deprecated: False
-- sha256: a3e7f4ee0b7dd2fd41dc1d33b01afc4f9bed3464ceb08e1b0c38aa0572fa9f7d
-- https://confluence.shopee.io/pages/viewpage.action?pageId=3013643154
CREATE TEMPORARY VIEW dim_item_${grass_region_without_quote} AS
SELECT
    item_id
    ,SPLIT(images,',')[0] AS image_id
    ,shop_id
FROM
    srdi_mart.dim_sr_data_warehouse_item
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_smart_ui_1d_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,a.image_id AS image_id
    ,MAX(b.shop_id) AS shop_id
    ,MAX(IF(c.image_id IS NOT NULL, TRUE, FALSE)) AS is_origin_cover
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_smart_ui_metrics_1d a
LEFT JOIN
    dim_item_${grass_region_without_quote} b
ON
    COALESCE(a.item_id, -1) = COALESCE(b.item_id, -1)
LEFT JOIN
    dim_item_${grass_region_without_quote} c
ON
    COALESCE(a.item_id, -1) = COALESCE(c.item_id, -1)
    AND COALESCE(a.image_id, 'NULL') = COALESCE(c.image_id, 'NULL')
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND target_type = 'item'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW smart_ui_1d_item_id_${grass_region_without_quote} AS
SELECT
    item_id
FROM
    dws_smart_ui_1d_${grass_region_without_quote}
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW smart_ui_180d_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,a.image_id AS image_id
    ,MAX(b.is_origin_cover) AS is_origin_cover
    ,SUM(a.imp_cnt) AS imp_cnt_180d
FROM
    srdi_mart.dws_sr_data_warehouse_search_smart_ui_metrics_1d a
JOIN
    dws_smart_ui_1d_${grass_region_without_quote} b
ON
    COALESCE(a.item_id, -1) = COALESCE(b.item_id, -1)
    AND COALESCE(a.image_id, 'NULL') = COALESCE(b.image_id, 'NULL')
WHERE
    a.grass_region = ${grass_region}
    AND a.local_date BETWEEN DATE_SUB(${local_date}, 179) AND ${local_date}
    AND a.target_type = 'item'
GROUP BY 
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_item_exp_status_${grass_region_without_quote} AS
SELECT
    item_id
    ,CASE
        WHEN MAX(IF(is_origin_cover = TRUE, imp_cnt_180d, 0)) >= 100
            AND MAX(IF(is_origin_cover = FALSE, imp_cnt_180d, 0)) >= 100
        THEN 1
        ELSE 0
    END AS exp_status
FROM
    smart_ui_180d_${grass_region_without_quote}
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_smart_ui_30d_image_level_metrics_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,a.image_id AS image_id
    ,SUM(a.imp_cnt) AS imp_cnt_30d
    ,SUM(a.click_cnt) AS click_cnt_30d
FROM
    srdi_mart.dws_sr_data_warehouse_search_smart_ui_metrics_1d a
JOIN
    dws_smart_ui_1d_${grass_region_without_quote} b
ON
    COALESCE(a.item_id, -1) = COALESCE(b.item_id, -1)
    AND COALESCE(a.image_id, 'NULL') = COALESCE(b.image_id, 'NULL')
WHERE
    a.grass_region = ${grass_region}
    AND a.local_date BETWEEN DATE_SUB(${local_date}, 29) AND ${local_date}
    AND a.target_type = 'item'
GROUP BY 
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_smart_ui_30d_item_level_metrics_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,SUM(imp_cnt) AS item_imp_cnt_30d
    ,SUM(click_cnt) AS item_click_cnt_30d
FROM
    srdi_mart.dws_sr_data_warehouse_search_smart_ui_metrics_1d a
JOIN
    smart_ui_1d_item_id_${grass_region_without_quote} b
ON
    COALESCE(a.item_id, -1) = COALESCE(b.item_id, -1)
WHERE
    a.grass_region = ${grass_region}
    AND a.local_date BETWEEN DATE_SUB(${local_date}, 29) AND ${local_date}
    AND a.target_type = 'item'
GROUP BY 
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_item_image_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,shop_id
    ,a.image_id AS image_id
    ,imp_cnt
    ,click_cnt
    ,IF(imp_cnt > 0, click_cnt * 1.0 / imp_cnt, 0) AS image_ctr
    ,DENSE_RANK() OVER (PARTITION BY a.item_id ORDER BY imp_cnt DESC) AS image_imp_rank_dense
    ,ROW_NUMBER() OVER (PARTITION BY a.item_id ORDER BY imp_cnt DESC, IF(imp_cnt > 0, click_cnt * 1.0 / imp_cnt, 0) DESC, a.image_id DESC) AS image_imp_rank_row_number
    ,DENSE_RANK() OVER (PARTITION BY a.item_id ORDER BY IF(imp_cnt > 0, click_cnt * 1.0 / imp_cnt, 0) DESC) AS image_ctr_rank_dense
    ,ROW_NUMBER() OVER (PARTITION BY a.item_id ORDER BY IF(imp_cnt > 0, click_cnt * 1.0 / imp_cnt, 0) DESC) AS image_ctr_rank_row_number
    ,order_cnt
    ,gmv
    ,is_origin_cover
    ,exp_status
    ,imp_cnt_30d
    ,click_cnt_30d
    ,1.0 * click_cnt_30d / imp_cnt_30d AS image_ctr_30d
    ,item_imp_cnt_30d
    ,item_click_cnt_30d
    ,1.0 * item_click_cnt_30d / item_imp_cnt_30d AS item_ctr_30d
FROM
    dws_smart_ui_1d_${grass_region_without_quote} a
LEFT JOIN
    dws_item_exp_status_${grass_region_without_quote} b
ON
    COALESCE(a.item_id, -1) = COALESCE(b.item_id, -1)
LEFT JOIN
    dws_smart_ui_30d_image_level_metrics_${grass_region_without_quote} c
ON
    COALESCE(a.item_id, -1) = COALESCE(c.item_id, -1)
    AND COALESCE(a.image_id, 'NULL') = COALESCE(c.image_id, 'NULL')
LEFT JOIN
    dws_smart_ui_30d_item_level_metrics_${grass_region_without_quote} d
ON
    COALESCE(a.item_id, -1) = COALESCE(d.item_id, -1);

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.ads_sr_data_warehouse_platform_smart_ui_best_performance_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
    ,scenario_tag
)
SELECT
    item_id
    ,shop_id
    ,image_id
    ,CASE
        WHEN exp_status = 1
            AND image_imp_rank_row_number = 1
        THEN TRUE
        ELSE FALSE
    END is_best_image
    ,imp_cnt
    ,image_imp_rank_dense
    ,image_imp_rank_row_number
    ,click_cnt
    ,image_ctr
    ,image_ctr_rank_dense
    ,image_ctr_rank_row_number
    ,order_cnt
    ,gmv
    ,is_origin_cover
    ,exp_status
    ,imp_cnt_30d
    ,click_cnt_30d
    ,image_ctr_30d
    ,item_imp_cnt_30d
    ,item_click_cnt_30d
    ,item_ctr_30d
    ,'Global Search' AS scenario_tag
FROM
    dws_item_image_${grass_region_without_quote};
