-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dim_sr_data_warehouse_user_label
-- physical_table: srdi_mart.dim_sr_data_warehouse_user_label
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dim_sr_data_warehouse_user_label
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dim/dim_sr_data_warehouse_user_label.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dim_sr_data_warehouse_user_label/analytics-mart-sr-data-warehouse/src/main/resources/dim/dim_sr_data_warehouse_user_label.sql
-- deprecated: False
-- sha256: e6ddfd8a257309aa1a7d7aaf597fd8b5a17efdcf0f5f659cc749d8589aba356e
create temporary view user_${grass_region_without_quote} as
select
    user_id
    ,gender
    ,age
    ,is_new_user
from srdi_mart.dim_sr_data_warehouse_user
where grass_region = ${grass_region}
    and local_date = ${local_date}

--sql_divide_splitter--
create temporary view user_abs_180d_${grass_region_without_quote} as
select
    buyer_id as user_id
    ,placed_order_cnt_180d as order_180d
    ,gmv_usd_180d as gmv_180d
    ,gmv_usd_180d / placed_order_cnt_180d as abs_180d
from mp_order.dws_buyer_gmv_nd__reg_s0_live
where grass_region = ${grass_region}
    and grass_date = ${local_date}
    and tz_type = 'local'
    and placed_order_cnt_180d > 0;

--sql_divide_splitter--
create temporary view abs_pct_${grass_region_without_quote} as
select
    case
        when ${grass_region} in ('BR') then approx_percentile(abs_180d, array(0.2, 0.35, 0.55, 0.75))
        else approx_percentile(abs_180d, array(0.25, 0.45, 0.65, 0.85))
    end as abs_pct_array
from
    user_abs_180d_${grass_region_without_quote}
;

--sql_divide_splitter--

create temporary view user_info_${grass_region_without_quote} as
select
    user_id
    ,sum(if(scenario_tag = '__ALL__',omni_click_cnt,0)) as item_click_cnt_30d
    ,size(collect_set(if(scenario_tag = '__ALL__' and imp_cnt>0, local_date, null))) as active_days_30d
    ,sum(if(scenario_tag = '__ALL__',order_cnt,0)) as order_30d
    ,sum(if(scenario_tag = '__ALL__',gmv,0)) as gmv_30d
    ,nvl(sum(if(scenario_tag = '__ALL__',gmv,0))/sum(if(scenario_tag='__ALL__',order_cnt,0)), 0) as backet_size
    ,sum(if(scenario_tag = 'DA_Daily Discover', click_cnt, null)) as dd_click_cnt_30d
    ,sum(if(scenario_tag = 'DA_Daily Discover', omni_click_cnt, 0)) as dd_omni_click_cnt_30d
    ,size(collect_set(if(imp_cnt>0 and scenario_tag = 'DA_Daily Discover', local_date, null))) as dd_active_days_30d
    ,sum(if(scenario_tag = 'DA_Daily Discover', order_cnt, 0)) as dd_order_30d
    ,sum(if(scenario_tag = 'DA_Daily Discover', gmv, 0)) as dd_gmv_30d
    ,nvl(sum(if(scenario_tag = 'DA_Daily Discover', gmv, 0))/sum(if(scenario_tag='DA_Daily Discover',order_cnt,0)), 0) as dd_backet_size
    ,sum(if(scenario_tag = 'DA_You May Also Like', omni_click_cnt, 0)) as ymal_omni_click_cnt_30d
    ,size(collect_set(if(imp_cnt>0 and scenario_tag = 'DA_You May Also Like', local_date, null))) as ymal_active_days_30d
    ,sum(if(scenario_tag = 'DA_You May Also Like', order_cnt, 0)) as ymal_order_30d
    ,sum(if(scenario_tag = 'DA_You May Also Like', gmv, 0)) as ymal_gmv_30d
    ,nvl(sum(if(scenario_tag = 'DA_You May Also Like', gmv, 0))/sum(if(scenario_tag = 'DA_You May Also Like', order_cnt, 0)), 0) as ymal_backet_size
    ,sum(if(scenario_tag = 'DA_Search', omni_click_cnt, 0)) as search_omni_click_cnt_30d
    ,size(collect_set(if(imp_cnt>0 and scenario_tag = 'DA_Search', local_date, null))) as search_active_days_30d
    ,sum(if(scenario_tag = 'DA_Search', order_cnt, 0)) as search_order_30d
    ,sum(if(scenario_tag = 'DA_Search', gmv, 0)) as search_gmv_30d
    ,nvl(sum(if(scenario_tag = 'DA_Search', gmv, 0))/sum(if(scenario_tag = 'DA_Search', order_cnt, 0)), 0) as search_backet_size
    ,nvl(sum(if(scenario_tag = 'DA_Daily Discover' and local_date between date_sub(${local_date}, 13) and ${local_date} and  feature_detail in ('home-daily_discover-item','home-daily_discover-item_feed_card'),imp_cnt,0 )),0) as dd_item_imp_cnt_14d
from srdi_mart.dws_sr_data_warehouse_platform_user_level_benchmark_1d
where grass_region = ${grass_region}
    and local_date between date_sub(${local_date}, 29) and ${local_date}
    and user_id > 0
    and( feature_detail = '__ALL__' and scenario_tag = '__ALL__'
        or feature_detail like 'home-daily_discover-%' and scenario_tag = 'DA_Daily Discover'
        or feature_detail like 'product-you_may_also_like-%' and scenario_tag = 'DA_You May Also Like'
        or feature_detail = '__ALL__' and scenario_tag = 'DA_Search'
        or (feature_detail in ('home-daily_discover-item','home-daily_discover-item_feed_card') and scenario_tag = 'DA_Daily Discover')
    )
group by user_id

--sql_divide_splitter--

create temporary view buyer_info_${grass_region_without_quote} as
select
    buyer_id as user_id
    , placed_order_cnt_td as total_order
from mp_order.dws_buyer_gmv_td__reg_s0_live
where tz_type = 'local'
    and grass_region = ${grass_region}
    and grass_date = ${local_date}

--sql_divide_splitter--

create temporary view income_info_${grass_region_without_quote} as
select
    user_id
    , predict_income_level as income_level
from mpi_data_mart.dws_a180_user_basic_predict_tags_df
where grass_region = ${grass_region}
    and grass_date = ${local_date}

--sql_divide_splitter--

create temporary view user_level_platform_app_version_${grass_region_without_quote} as
select
    user_id
    ,platform
    ,app_version
    ,substring_index(app_version, '.', 2) as app_version_prefix
    ,log_timestamp
from
   (
       select
           user_id
           ,platform
           ,app_version
           ,log_timestamp
           ,row_number() over (
               partition by user_id
               order by log_timestamp desc
           ) as rn
       from srdi_mart.dwd_sr_data_warehouse_platform
       where
           grass_region = ${grass_region}
           and local_date = ${local_date}
           and operation in ('click','impression','view')
           and user_id > 0
   )
where rn = 1

--sql_divide_splitter--
create temporary view user_purchase_type_${grass_region_without_quote} as
select
    user_id
    ,max(if(mp_new_user is null and dp_new_user is null, 0, 1)) as user_purchase_type -- 'Yes' has been replaced by %null% in the upstream table
from mpi_data_mart.dws_all_user_segmentation_tags_df
where
    grass_date = ${local_date}
    and grass_region = ${grass_region}
group by 1
;

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_platform_and_search_gmv_${grass_region_without_quote} AS
SELECT
    user_id
    ,SUM(IF(is_direct = TRUE, gmv, NULL)) AS platform_gmv
    ,SUM(IF(array_contains(dedup_scenario_tags, 'dpm business line Search'), gmv, NULL)) AS search_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_platform_order_benchmark_1d
WHERE
    grass_region = ${grass_region}
    AND local_date BETWEEN DATE_SUB(${local_date}, 179) AND ${local_date}
    AND user_id > 0
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_platform_and_search_gmv_pct_category_${grass_region_without_quote} AS
SELECT
    user_id
    ,CASE WHEN platform_gmv IS NOT NULL THEN
        NTILE(10) OVER (PARTITION BY (platform_gmv IS NOT NULL) ORDER BY platform_gmv ASC) - 1
    END AS platform_gmv_180d_pct_category
    ,CASE WHEN search_gmv IS NOT NULL THEN 
        NTILE(10) OVER (PARTITION BY (search_gmv IS NOT NULL) ORDER BY search_gmv ASC) - 1
    END AS search_gmv_180d_pct_category
    ,platform_gmv
    ,search_gmv
FROM
    user_platform_and_search_gmv_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_platform_and_search_duration_${grass_region_without_quote} AS
SELECT
    user_id
    ,SUM(IF(scenario_tag = 'platform', duration, NULL)) AS platform_duration
    ,SUM(IF(scenario_tag = 'search', duration, NULL)) AS search_duration
FROM
    srdi_mart.dwd_sr_data_warehouse_view_page_duration_di
WHERE
    grass_region = ${grass_region}
    AND local_date BETWEEN DATE_SUB(${local_date}, 179) AND ${local_date}
    AND user_id > 0
    AND is_analysis_log = 1
    AND scenario_tag IN ('search', 'platform')
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_platform_and_search_duration_pct_category_${grass_region_without_quote} AS
SELECT
    user_id
    ,CASE WHEN platform_duration IS NOT NULL THEN
        NTILE(10) OVER (PARTITION BY (platform_duration IS NOT NULL) ORDER BY platform_duration ASC) - 1
    END AS platform_duration_180d_pct_category
    ,CASE WHEN search_duration IS NOT NULL THEN 
        NTILE(10) OVER (PARTITION BY (search_duration IS NOT NULL) ORDER BY search_duration ASC) - 1
    END AS search_duration_180d_pct_category
    ,platform_duration
    ,search_duration
FROM
    user_platform_and_search_duration_${grass_region_without_quote};

--sql_divide_splitter--

insert overwrite table ${schema}.dim_sr_data_warehouse_user_label
partition(grass_region=${grass_region}, local_date=${local_date})
select
    user.user_id
    ,user.gender
    ,user.age
    ,user.is_new_user
    ,nvl(info.item_click_cnt_30d, 0) as item_click_cnt_30d
    ,case
        when info.item_click_cnt_30d >= 150 then '150+'
        when info.item_click_cnt_30d >= 40  then '40-149'
        when info.item_click_cnt_30d >= 6   then '6-39'
        else '0-5'
    end as item_click_level
    ,nvl(info.active_days_30d, 0) as active_days_30d
    ,case
        when info.active_days_30d >= 26 then '26-30'
        when info.active_days_30d >= 16 then '16-25'
        when info.active_days_30d >= 8 then '8-15'
        when info.active_days_30d >= 1 then '1-7'
        else '0'
    end as active_level
    ,nvl(info.dd_click_cnt_30d, 0) as dd_click_cnt_30d
    ,case
        when info.dd_click_cnt_30d >= 24 then '24+'
        when info.dd_click_cnt_30d >= 8 then '8-23'
        when info.dd_click_cnt_30d >= 3 then '3-7'
        else '0-2'
    end as dd_click_level
    ,nvl(info.dd_active_days_30d, 0) as dd_active_days_30d
    ,case
        when info.dd_active_days_30d >= 26 then '26-30'
        when info.dd_active_days_30d >= 16 then '16-25'
        when info.dd_active_days_30d >= 8 then '8-15'
        when info.dd_active_days_30d >= 1 then '1-7'
        else '0'
    end as dd_active_level
    ,nvl(info.order_30d, 0) as order_30d
    ,case
        when info.order_30d >= 11 then '11+'
        when info.order_30d >= 7 then '7-10'
        when info.order_30d >= 4 then '4-6'
        when info.order_30d >= 1 then '1-3'
        else '0'
    end as order_level
    ,nvl(info.gmv_30d, 0) as gmv_cnt
    ,nvl(buyer.total_order, 0) as total_order
    ,case
        when buyer.total_order >= 5 then 'mature'
        when buyer.total_order >= 1 then 'early'
        else 'new'
    end as life_cycle
    ,nvl(income.income_level, '') as income_level
    ,nvl(info.backet_size, 0) as backet_size
    ,case
        when info.backet_size > 4.5 then '(4.5, +)'
        when info.backet_size > 0.8 then '(0.8, 4.5]'
        when info.backet_size >0 then '(0, 0.8]'
        else '0'
    end as backet_level
    ,nvl(info.dd_omni_click_cnt_30d, 0) as dd_omni_click_cnt_30d
    ,nvl(info.dd_order_30d, 0) as dd_order_30d
    ,nvl(info.dd_gmv_30d, 0) as dd_gmv_30d
    ,nvl(info.dd_backet_size, 0) as dd_backet_size
    ,nvl(info.ymal_omni_click_cnt_30d, 0) as ymal_omni_click_cnt_30d
    ,nvl(info.ymal_active_days_30d, 0) as ymal_active_days_30d
    ,nvl(info.ymal_order_30d, 0) as ymal_order_30d
    ,nvl(info.ymal_gmv_30d, 0) as ymal_gmv_30d
    ,nvl(info.ymal_backet_size, 0) as ymal_backet_size
    ,nvl(info.search_omni_click_cnt_30d, 0) as search_omni_click_cnt_30d
    ,nvl(info.search_active_days_30d, 0) as search_active_days_30d
    ,nvl(info.search_order_30d, 0) as search_order_30d
    ,nvl(info.search_gmv_30d, 0) as search_gmv_30d
    ,nvl(info.search_backet_size, 0) as search_backet_size
    ,nvl(info.dd_item_imp_cnt_14d,0) as dd_item_imp_cnt_14d
    ,version.platform
    ,version.app_version
    ,version.app_version_prefix
    ,user_purchase_type.user_purchase_type
    ,abs.order_180d
    ,abs.gmv_180d
    ,case
        when abs.abs_180d is null then 0
        when abs.abs_180d <= abs_pct.abs_pct_array[0] then 1
        when abs.abs_180d <= abs_pct.abs_pct_array[1] then 2
        when abs.abs_180d <= abs_pct.abs_pct_array[2] then 3
        when abs.abs_180d <= abs_pct.abs_pct_array[3] then 4
        else 5
    end as abs_tier_180d
    ,platform_gmv_180d_pct_category
    ,search_gmv_180d_pct_category
    ,platform_duration_180d_pct_category
    ,search_duration_180d_pct_category
from
    user_${grass_region_without_quote} user
left join
    user_info_${grass_region_without_quote} info
on user.user_id = info.user_id

left join
    buyer_info_${grass_region_without_quote} buyer
on user.user_id = buyer.user_id

left join
    income_info_${grass_region_without_quote} income
on user.user_id = income.user_id

left join
    user_level_platform_app_version_${grass_region_without_quote} version
on user.user_id = version.user_id
left join
    user_purchase_type_${grass_region_without_quote} as user_purchase_type
on user.user_id = user_purchase_type.user_id
left join
    user_abs_180d_${grass_region_without_quote} abs
on user.user_id = abs.user_id
left join
    abs_pct_${grass_region_without_quote} abs_pct
on abs.abs_180d is not null
LEFT JOIN
    user_platform_and_search_gmv_pct_category_${grass_region_without_quote} gmv_pct
ON
    user.user_id = gmv_pct.user_id
LEFT JOIN
    user_platform_and_search_duration_pct_category_${grass_region_without_quote} gmv_dur
ON
    user.user_id = gmv_dur.user_id;
