-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d.sql
-- deprecated: False
-- sha256: 41da97015b43f653dac753f7238a0a332b210cf290f3c3399eac31c355723ef2
-- DRD: https://confluence.shopee.io/pages/viewpage.action?pageId=2745478450
CREATE TEMPORARY VIEW user_exp_mapping_${grass_region_without_quote} AS
SELECT
    user_id
    ,experiment_id
    ,exp_group_id
FROM
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND is_assignment_log = 1
    AND experiment_id = 148401;

--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_group_uu_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,COUNT(DISTINCT user_id) AS group_uu
FROM
    user_exp_mapping_${grass_region_without_quote}
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_search_volume_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,COUNT(DISTINCT IF(operation = 'view', a.user_id, NULL)) AS search_uu
    ,COUNT(DISTINCT IF(operation = 'view', (a.user_id, device_id, keyword), NULL)) AS search_volume
FROM
    srdi_mart.dwd_sr_data_warehouse_search a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND a.user_id > 0
    AND page_type IN ('global_search','search_in_pdp','search_prefill')
    AND page_section IS NULL
    AND operation = 'view'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_instant_filter_click_imp_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,b.exp_group_id AS exp_group_id
    ,COUNT(DISTINCT IF(operation = 'click', a.user_id, NULL)) AS instant_filter_uu
    ,COUNT(IF(operation = 'click', 1, NULL)) AS instant_filter_using_cnt
    ,COUNT(DISTINCT IF(operation = 'impression', a.user_id, NULL)) AS instant_filter_imp_uu
    ,COUNT(IF(operation = 'impression', 1, NULL)) AS instant_filter_imp_cnt
FROM
    srdi_mart.dwd_sr_data_warehouse_search a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND a.user_id > 0
    AND ((
        operation = 'click'
        AND original_operation = 'action_filter'
        AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
        AND page_section IS NULL
        AND target_type IS NULL
    ) OR (
        page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
        AND page_section[0] = 'search_filter_shortcut_bar'
        AND target_type = 'filter_button'
        AND operation = 'impression'
    ))
    AND EXISTS(TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
        ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery')
    )
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_no_results_metrics_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,b.exp_group_id AS exp_group_id
    ,COUNT(1) AS no_results_cnt
    ,COUNT(DISTINCT (a.user_id, device_id, keyword)) AS no_results_volume
    ,COUNT(IF(target_type = 'try_diff_address' OR (target_type = 'no_recall_with_filter' AND EXISTS(
        TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>')), x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery')
    )), 1, NULL)) AS instant_filter_no_results_cnt
    ,COUNT(DISTINCT IF(target_type = 'try_diff_address' OR (target_type = 'no_recall_with_filter' AND EXISTS(
        TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>')), x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery')
    )), (a.user_id, device_id, keyword), NULL)) AS instant_filter_no_results_volume
FROM
    srdi_mart.dwd_sr_data_warehouse_search a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND a.user_id > 0
    AND page_type IN ('global_search','search_in_pdp','search_prefill')
    AND (
        (page_section IS NULL AND target_type IN ('no_recall_general', 'no_recall_with_filter'))
        OR (page_section[0] = 'no_recall_with_filter' AND target_type = 'try_diff_address')
    )
    AND operation = 'impression'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_direct_broad_search_volume_${grass_region_without_quote} AS
SELECT
    CASE
        WHEN EXISTS(TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
            ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery')
        ) THEN 'true'
        ELSE 'false'
    END AS use_instant_filter_type
    ,COALESCE(CAST(layout_type AS STRING), '2') AS layout_type
    ,user_id
    ,device_id
    ,keyword
    ,page_section
    ,target_type
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    ANd user_id > 0
    AND page_type IN ('global_search','search_in_pdp','search_prefill')
    AND (
        (target_type IN ('item','video','livestream', 'curated_search', 'live_stream_floating_preview') AND page_section IS NULL)
        OR ((target_type LIKE 'shop%' OR target_type LIKE 'creator%') AND page_section IS NULL)
        OR (page_section[0] = 'creator')
    )
    AND operation = 'click';

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_direct_broad_search_volume_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,IF(use_instant_filter_type IS NOT NULL, use_instant_filter_type, '__ALL__') AS use_instant_filter_type 
    ,IF(layout_type IS NOT NULL, layout_type, '__ALL__') AS layout_type 
    ,COUNT(DISTINCT IF(page_section IS NULL AND target_type IN ('item','video','livestream'), (a.user_id, device_id, keyword), NULL)) AS direct_search_success_volume
    ,COUNT(DISTINCT (a.user_id, device_id, keyword)) AS broad_search_success_volume
FROM
    dwd_direct_broad_search_volume_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    experiment_id
    ,exp_group_id
    ,CUBE(use_instant_filter_type, layout_type);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_click_imp_order_metrics_${grass_region_without_quote} AS
SELECT
    user_id
    ,device_id
    ,keyword
    ,CASE WHEN EXISTS(TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
        ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery'))
    THEN 'true' ELSE 'false' END AS use_instant_filter_type
    ,COALESCE(CAST(layout_type AS STRING), '2') AS layout_type
    ,target_type AS card_type
    ,IF(SIZE(shop_layout_item_list) < 3, 1, NULL) AS has_empty_shop_layout_item
    ,operation_cnt
    ,place_order_gmv
    ,operation
    ,order_id
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND page_type IN ('global_search','search_in_pdp','search_prefill')
    AND (
        (page_section IS NULL AND target_type IN ('item', 'video', 'livestream'))
        OR (page_section[0] = 'results' AND target_type = 'shop')
    )
    AND operation IN ('impression', 'click', 'order')
UNION ALL
SELECT
    user_id
    ,device_id
    ,source1_keyword AS keyword
    ,CASE WHEN EXISTS(TRANSFORM(source1_search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
        ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery'))
    THEN 'true' ELSE 'false' END AS use_instant_filter_type
    ,COALESCE(CAST(source1_layout_type AS STRING), '2') AS layout_type
    ,source1_target_type AS card_type
    ,NULL AS has_empty_shop_layout_item
    ,operation_cnt
    ,place_order_gmv
    ,operation
    ,order_id
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND source1_page_type IN ('global_search','search_in_pdp','search_prefill')
    AND (
        (source1_page_section IS NULL AND source1_target_type IN ('item', 'video', 'livestream'))
        OR (source1_page_section[0] = 'results' AND source1_target_type = 'shop')
    )
    AND operation = 'order'
UNION ALL
SELECT
    user_id
    ,device_id
    ,source2_keyword AS keyword
    ,CASE WHEN EXISTS(TRANSFORM(source2_search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
        ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery'))
    THEN 'true' ELSE 'false' END AS use_instant_filter_type
    ,COALESCE(CAST(source2_layout_type AS STRING), '2') AS layout_type
    ,source2_target_type AS card_type
    ,NULL AS has_empty_shop_layout_item
    ,operation_cnt
    ,place_order_gmv
    ,operation
    ,order_id
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND source2_page_type IN ('global_search','search_in_pdp','search_prefill')
    AND (
        (source2_page_section IS NULL AND source2_target_type IN ('item', 'video', 'livestream'))
        OR (source2_page_section[0] = 'results' AND source2_target_type = 'shop')
    )
    AND operation = 'order';

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_click_imp_order_other_metrics_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,IF(GROUPING(use_instant_filter_type) = 1, '__ALL__', use_instant_filter_type) AS use_instant_filter_type
    ,IF(GROUPING(layout_type) = 1, '__ALL__', layout_type) AS layout_type
    ,IF(GROUPING(card_type) = 1, '__ALL__', card_type) AS card_type
    ,SUM(IF(operation = 'impression', operation_cnt, NULL)) AS imp_cnt
    ,COUNT(DISTINCT IF(operation = 'impression', a.user_id, NULL)) AS imp_uu
    ,SUM(IF(operation = 'click', operation_cnt, NULL)) AS click_cnt
    ,COUNT(DISTINCT IF(operation = 'click', a.user_id, NULL)) AS click_uu
    ,SUM(IF(operation = 'order' AND operation_cnt > 0, operation_cnt, NULL)) AS order_cnt
    ,COUNT(DISTINCT IF(operation = 'order' AND operation_cnt > 0, a.user_id, NULL)) AS order_uu
    ,SUM(IF(operation = 'order' AND operation_cnt > 0, place_order_gmv, NULL)) AS gmv
    ,CASE
        WHEN layout_type = '3'
        THEN COUNT(DISTINCT IF(operation = 'impression', (a.user_id, device_id, keyword), NULL))
        ELSE NULL
    END AS shop_search_volume
    ,CASE
        WHEN layout_type = '3' AND card_type = 'shop'
        THEN SUM(IF(operation = 'impression', has_empty_shop_layout_item, NULL))
        ELSE NULL
    END AS empty_shop_imp_cnt
FROM
    dwd_click_imp_order_metrics_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    experiment_id
    ,exp_group_id
    ,CUBE(use_instant_filter_type, layout_type, card_type);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_shop_item_fill_rate_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,use_instant_filter_type
    ,CAST(SUM(IF(card_type = 'item', imp_cnt, NULL)) AS DOUBLE) / (SUM(IF(card_type = 'shop', imp_cnt, NULL)) * 3.0) AS shop_item_fill_rate
FROM
    dws_click_imp_order_other_metrics_${grass_region_without_quote}
WHERE
    layout_type = '3'
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_edt_order_info_${grass_region_without_quote} AS
SELECT DISTINCT
    order_id
    ,edtmax_in_days
FROM
    sls_mart.dwd_edt_order_info_df_${grass_region_without_quote}
WHERE
    grass_date = (SELECT MAX(grass_date) FROM sls_mart.dwd_edt_order_info_df_${grass_region_without_quote})
    AND order_create_date = ${local_date};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_avg_edt_dim_${grass_region_without_quote} AS
SELECT
-- Each dimensional category row must have unique order_ids to join correctly without overcounting
    user_id
    ,IF(use_instant_filter_type IS NULL, '__ALL__', use_instant_filter_type) AS use_instant_filter_type
    ,IF(layout_type IS NULL, '__ALL__', layout_type) AS layout_type
    ,order_id
FROM
    dwd_click_imp_order_metrics_${grass_region_without_quote}
WHERE
    operation = 'order'
    AND order_id IS NOT NULL
GROUP BY GROUPING SETS (
    (user_id,use_instant_filter_type,layout_type,order_id)
    ,(user_id,layout_type,order_id)
    ,(user_id,use_instant_filter_type,order_id)
    ,(user_id,order_id)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_avg_edt_join_${grass_region_without_quote} AS
SELECT
    user_id
    ,use_instant_filter_type
    ,layout_type
    ,edtmax_in_days
FROM
    dwm_avg_edt_dim_${grass_region_without_quote} a
LEFT JOIN
    dwd_edt_order_info_${grass_region_without_quote} b
ON
    a.order_id = b.order_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_avg_edt_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,use_instant_filter_type
    ,layout_type
    ,AVG(edtmax_in_days) AS avg_edt
FROM
    dwm_avg_edt_join_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    experiment_id
    ,exp_group_id
    ,use_instant_filter_type
    ,layout_type;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_ads_revenue_link_${grass_region_without_quote} AS
SELECT
    request_id
    ,item_id
    ,COALESCE(layout_type, '2') AS layout_type
    ,CASE WHEN EXISTS(TRANSFORM(search_filter_string, x -> FROM_JSON(x, 'STRUCT<filter_name:STRING>'))
        ,x -> LOWER(x.filter_name) IN ('instant_delivery', 'fast_delivery'))
    THEN 'true' ELSE 'false' END AS use_instant_filter_type
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND page_section IS NULL
    AND target_type IN ('video', 'item', 'livestream')
    AND request_id IS NOT NULL
    AND item_id IS NOT NULL
GROUP BY
    1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_ads_revenue_${grass_region_without_quote} AS
SELECT
    user_id
    ,raw_request_id
    ,item_id
    ,SUM(expenditure_amt_usd) AS ads_rev
FROM
    mp_paidads.dwd_advertise_performance_di__reg_s0_live
WHERE
    grass_region = ${grass_region}
    AND grass_date = ${local_date}
    AND user_id > 0
    AND entrance = 1
    AND tz_type = 'local'
    AND expenditure_amt_usd IS NOT NULL
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_ads_revenue_${grass_region_without_quote} AS
SELECT
-- joining columns on both tables must be unique pairs in each table to avoid overcounting
    user_id
    ,COALESCE(layout_type, '2') AS layout_type
    ,COALESCE(use_instant_filter_type, 'false') AS use_instant_filter_type
    ,ads_rev
FROM
    dwd_ads_revenue_${grass_region_without_quote} a
LEFT JOIN
    dwm_ads_revenue_link_${grass_region_without_quote} b
ON
    a.raw_request_id = b.request_id
    AND a.item_id = b.item_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_ads_revenue_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,IF(use_instant_filter_type IS NOT NULL, use_instant_filter_type, '__ALL__') AS use_instant_filter_type
    ,IF(layout_type IS NOT NULL, layout_type, '__ALL__') AS layout_type
    ,SUM(ads_rev) AS ads_rev
FROM
    dwm_ads_revenue_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY GROUPING SETS (
    (experiment_id, exp_group_id, use_instant_filter_type, layout_type)
    ,(experiment_id, exp_group_id, use_instant_filter_type)
    ,(experiment_id, exp_group_id, layout_type)
    ,(experiment_id, exp_group_id)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW global_search_and_platform_metrics_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,SUM(CASE WHEN
            (reporting_business_line = 'Search' AND reporting_module = 'Global Search')
            OR (source1_reporting_business_line = 'Search' AND source1_reporting_module = 'Global Search')
            OR (source2_reporting_business_line = 'Search' AND source2_reporting_module = 'Global Search')
        THEN operation_cnt ELSE NULL
    END) AS global_search_order_cnt
    ,SUM(CASE WHEN
            (reporting_business_line = 'Search' AND reporting_module = 'Global Search')
            OR (source1_reporting_business_line = 'Search' AND source1_reporting_module = 'Global Search')
            OR (source2_reporting_business_line = 'Search' AND source2_reporting_module = 'Global Search')
        THEN place_order_gmv ELSE NULL
    END) AS global_search_gmv
    ,SUM(operation_cnt) AS platform_order_cnt
    ,SUM(place_order_gmv) AS platform_gmv
FROM
    srdi_mart.dwd_sr_data_warehouse_platform a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND operation = 'order'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_main_metrics_${grass_region_without_quote} AS
SELECT
    COALESCE(a.experiment_id, b.experiment_id, c.experiment_id, d.experiment_id) AS experiment_id
    ,COALESCE(a.exp_group_id, b.exp_group_id, c.exp_group_id, d.exp_group_id) AS exp_group_id
    ,COALESCE(a.use_instant_filter_type, b.use_instant_filter_type, c.use_instant_filter_type, d.use_instant_filter_type) AS use_instant_filter_type
    ,COALESCE(a.layout_type, b.layout_type, c.layout_type, d.layout_type) AS layout_type
    ,card_type
    ,direct_search_success_volume
    ,broad_search_success_volume
    ,imp_cnt
    ,imp_uu
    ,click_cnt
    ,click_uu
    ,order_cnt
    ,order_uu
    ,gmv
    ,avg_edt
    ,ads_rev
    ,shop_search_volume
    ,empty_shop_imp_cnt
FROM
    dws_click_imp_order_other_metrics_${grass_region_without_quote} a
FULL JOIN
    dws_direct_broad_search_volume_${grass_region_without_quote} b
ON
    a.experiment_id = b.experiment_id
    AND a.exp_group_id = b.exp_group_id
    AND a.use_instant_filter_type = b.use_instant_filter_type
    AND a.layout_type = b.layout_type
    AND a.card_type = '__ALL__'
FULL JOIN
    dws_avg_edt_${grass_region_without_quote} c
ON
    COALESCE(a.experiment_id, b.experiment_id) = c.experiment_id
    AND COALESCE(a.exp_group_id, b.exp_group_id) = c.exp_group_id
    AND COALESCE(a.use_instant_filter_type, b.use_instant_filter_type) = c.use_instant_filter_type
    AND COALESCE(a.layout_type, b.layout_type) = c.layout_type
    AND a.card_type = '__ALL__'
FULL JOIN
    dws_ads_revenue_${grass_region_without_quote} d
ON
    COALESCE(a.experiment_id, b.experiment_id, c.experiment_id) = d.experiment_id
    AND COALESCE(a.exp_group_id, b.exp_group_id, c.exp_group_id) = d.exp_group_id
    AND COALESCE(a.use_instant_filter_type, b.use_instant_filter_type, c.use_instant_filter_type) = d.use_instant_filter_type
    AND COALESCE(a.layout_type, b.layout_type, c.layout_type) = d.layout_type
    AND a.card_type = '__ALL__';

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_abtest_srp_layout_instant_filter_metrics_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
    a.experiment_id
    ,a.exp_group_id
    ,a.use_instant_filter_type
    ,a.layout_type

    ,group_uu
    ,search_uu
    ,search_volume
    ,instant_filter_uu
    ,instant_filter_using_cnt
    ,no_results_cnt
    ,no_results_volume
    ,instant_filter_no_results_cnt
    ,instant_filter_no_results_volume

    ,direct_search_success_volume
    ,broad_search_success_volume
    ,imp_cnt
    ,imp_uu
    ,click_cnt
    ,click_uu
    ,order_cnt
    ,order_uu
    ,gmv
    ,avg_edt
    ,ads_rev

    ,card_type
    ,instant_filter_imp_uu
    ,instant_filter_imp_cnt
    ,shop_search_volume
    ,empty_shop_imp_cnt
    ,shop_item_fill_rate
    ,global_search_order_cnt
    ,global_search_gmv
    ,platform_order_cnt
    ,platform_gmv
FROM
    dws_main_metrics_${grass_region_without_quote} a
LEFT JOIN
    exp_group_uu_${grass_region_without_quote} b
ON
    a.experiment_id = b.experiment_id
    AND a.exp_group_id = b.exp_group_id
    AND a.use_instant_filter_type = '__ALL__'
    AND a.layout_type = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_search_volume_${grass_region_without_quote} c
ON
    a.experiment_id = c.experiment_id
    AND a.exp_group_id = c.exp_group_id
    AND a.use_instant_filter_type = '__ALL__'
    AND a.layout_type = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_instant_filter_click_imp_${grass_region_without_quote} d
ON
    a.experiment_id = d.experiment_id
    AND a.exp_group_id = d.exp_group_id
    AND a.use_instant_filter_type = '__ALL__'
    AND a.layout_type = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_no_results_metrics_${grass_region_without_quote} e
ON
    a.experiment_id = e.experiment_id
    AND a.exp_group_id = e.exp_group_id
    AND a.use_instant_filter_type = '__ALL__'
    AND a.layout_type = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_shop_item_fill_rate_${grass_region_without_quote} f
ON
    a.experiment_id = f.experiment_id
    AND a.exp_group_id = f.exp_group_id
    AND a.use_instant_filter_type = f.use_instant_filter_type
    AND a.layout_type = '3'
    AND a.card_type = '__ALL__'
LEFT JOIN
    global_search_and_platform_metrics_${grass_region_without_quote} g
ON
    a.experiment_id = g.experiment_id
    AND a.exp_group_id = g.exp_group_id
    AND a.use_instant_filter_type = '__ALL__'
    AND a.layout_type = '__ALL__'
    AND a.card_type = '__ALL__';
