-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
-- physical_table: srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf/analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf.sql
-- deprecated: False
-- sha256: d855393d0e3cbe6bf73ed6f14f9a704d808fbe048767e7d7224fec4035d6f0bf
CREATE TEMPORARY VIEW traffic_tag_metrics_${grass_region_without_quote} AS
select -- 因为要配合下游做减法和顺序操作，之所以这个任务也需要顺序执行
     cspu_id
    ,item_id
    ,split(tag_concat,':')[1] as exp_tag
    ,split(tag_concat,':')[0] as traffic_tag
    ,if(split(tag_concat,':')[1]='control',0,version_array[pos]) as version_date -- 双重兜底
    ,imp_cnt_array[pos] as imp_cnt_nd
    ,clk_cnt_array[pos] as click_cnt_nd
    ,atc_cnt_array[pos] as atc_cnt_nd
from(
    select
         *
    from paimon.srdi_mart.cheapest_item_replacement_statistics_search_v2_dump
    where country in (${grass_region})
) a
lateral view posexplode(tag_array) b as pos, tag_concat
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW current_version_${grass_region_without_quote} AS
select -- honggen的表里是点对点触发版本重置，多个traffic_tag下有可能会有两个版本，我们取最新版本
     cspu_id
    ,item_id
    ,exp_tag
    ,max(version_date) as version_date
from traffic_tag_metrics_${grass_region_without_quote}
group by
     cspu_id
    ,item_id
    ,exp_tag
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
partition(grass_region = ${grass_region}, local_date, local_hour, regional_date,regional_hour)
SELECT
     a.exp_tag
    ,a.cspu_id
    ,a.item_id
    ,a.traffic_tag
    ,a.version_date
    ,a.imp_cnt_nd
    ,a.click_cnt_nd
    ,a.atc_cnt_nd

    ,date(date_timezone_convert(${regional_date},${regional_hour},'SG',${grass_region},"yyyy-MM-dd")) as local_date
    ,cast(date_timezone_convert(${regional_date},${regional_hour},'SG',${grass_region},"HH") as int) as local_hour
    ,cast(${regional_date} as date) as regional_date
    ,cast(${regional_hour} as int) as regional_hour
from traffic_tag_metrics_${grass_region_without_quote} a
inner join current_version_${grass_region_without_quote} b on a.item_id=b.item_id and a.cspu_id=b.cspu_id and a.exp_tag=b.exp_tag
      and a.version_date=b.version_date -- 只要当前最新版本的记录
;
