-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_item_realtime_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_item_realtime_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_item_realtime_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_ni_boost_item_realtime_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_ni_boost_item_realtime_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_ni_boost_item_realtime_1d.sql
-- deprecated: False
-- sha256: e29e37a6c6a1b2bb71a0401947d95d5843b0654422b65f51e1c1f79108dade0f
--********************************************************************--
-- Author:         yue.feng@shopee.com
-- Created Time:   2025-12-18T06:56:53.685Z
-- Description:    Write your description here
--********************************************************************--

-- 注册解析pb格式ub的 udf function
CREATE FUNCTION NewItemBoostParseUb AS 'com.shopee.sr.data.intelligence.mart.udf.NewItemBoostParseUb';

create table user_behavior(
     kafka_key STRING
    ,raw_bytes BYTES
    ,kafka_time TIMESTAMP_LTZ(3) METADATA FROM 'timestamp'
    ,WATERMARK FOR kafka_time AS kafka_time - INTERVAL '10' SECOND
) with (
    'connector' = 'kafka',
    'topic' = 'srdi.user_behavior_id;srdi.user_behavior_vn;srdi.user_behavior_ph;srdi.user_behavior_my;srdi.user_behavior_th',
    'properties.bootstrap.servers' = 'di-kafka01-bg1-bootstrap01-cptl-sg.data-infra.shopee.io:9093,di-kafka01-bg1-bootstrap02-cptl-sg.data-infra.shopee.io:9093,di-kafka01-bg1-bootstrap03-cptl-sg.data-infra.shopee.io:9093',
    'properties.group.id' = 'srdi_mart_sr_data_warehouse_de_ni',
    'properties.security.protocol' = 'SASL_PLAINTEXT',
    'properties.sasl.mechanism' = 'PLAIN',
    'properties.sasl.jaas.config' = 'org.apache.kafka.common.security.plain.PlainLoginModule required username="srdi_mart" password="a7T9khHqzlEa";',
    'key.format' = 'raw',
    'key.fields' = 'kafka_key',
    'value.format' = 'raw',
    'value.fields-include' = 'EXCEPT_KEY' -- 核心：告诉 Value 格式，排除掉 Key 字段，只把剩下的部分填入 Value
);

create temporary view user_behavior_parse as
SELECT
     kafka_time
    ,FROM_UNIXTIME(ub.log_timestamp, 'yyyy-MM-dd') AS regional_date
    ,ub.item_id
    ,ub.grass_region
    ,ub.feature_detail
    ,case
         when (ARRAY_CONTAINS(ub.ab_list,'627728') and ub.grass_region='ID') -- ID
             or (ARRAY_CONTAINS(ub.ab_list,'640343') and ub.grass_region='VN') -- VN
             or (ARRAY_CONTAINS(ub.ab_list,'655654') and ub.grass_region='PH') -- PH
             or (ARRAY_CONTAINS(ub.ab_list,'655641') and ub.grass_region='TH') -- TH
             or (ARRAY_CONTAINS(ub.ab_list,'662593') and ub.grass_region='MY') -- MY
             then 'T1'
         when ARRAY_CONTAINS(ub.ab_list,'378802') then 'C1'
         else 'OTHER'
     end as exp_tag
    ,if(ub.operation='impression',1,0) as imp_cnt
    ,if(ub.operation='click',1,0) as click_cnt
    ,if(ub.operation='omni_order',attribution_cnt,0) as order_cnt
    ,PROCTIME() AS proc_time
FROM (
    SELECT
         NewItemBoostParseUb(raw_bytes) AS ub
        ,kafka_time
    FROM user_behavior
    where SPLIT_INDEX(kafka_key, '|', 1) in ('impression','click','omni_order')
    and SPLIT_INDEX(kafka_key, '|', 2) ='RCMD'
) a
where ub.operation in ('impression','click','omni_order')
and (ub.is_ads=false or ub.is_ads is null) and ub.item_id>0
and ( -- 限定主要卡片类型
       ub.target_type = 'item'
    or (ub.page_type = 'home' and ub.page_section = 'daily_discover' and ub.target_type in ('item_feed_card','item_mix_feed_card','repurchase_mix_feed_card'))
)
;
create temporary view user_behavior_filter as
select
     u.*
from user_behavior_parse u
join paimon.srdi_mart.dim_sr_data_warehouse_fd_mapping_scenario_lookup --使用join近似方案来圈选场景
    /*+ OPTIONS(
        'lookup.cache' = 'FULL',
        'lookup.cache-file-retention' ='1d',
        'streaming-read-overwrite'='true',
        'lookup.bootstrap-parallelism'='200',
        'lookup.cache-max-memory-size'='2G'
    ) */
FOR SYSTEM_TIME AS OF proc_time AS n
ON u.feature_detail = n.feature_detail and u.grass_region=n.grass_region
where
(--只要推荐场景的
       (n.reporting_business_line = 'Rcmd' and n.reporting_module = 'User Scenario' and n.reporting_object = 'you may also like')
    or (n.reporting_business_line = 'Homepage' and n.reporting_module = 'Daily Discover')
    or (n.reporting_business_line = 'Rcmd' and n.reporting_module = 'User Scenario' and n.reporting_object = 'post purchase')
)
;
INSERT INTO paimon.srdi_mart.dws_sr_data_warehouse_ni_boost_item_realtime_1d
SELECT
     exp_tag
    ,item_id
    ,UNIX_TIMESTAMP(DATE_FORMAT(window_end, 'yyyy-MM-dd HH:mm:ss')) as window_end
    ,SUM(imp_cnt)   AS explore_imp_cnt
    ,SUM(click_cnt) AS explore_click_cnt
    ,SUM(order_cnt) AS explore_order_cnt

    ,regional_date
    ,grass_region
FROM TABLE(
    TUMBLE(TABLE user_behavior_filter, DESCRIPTOR(kafka_time), INTERVAL '10' MINUTES)
)
GROUP BY window_start, window_end, exp_tag, item_id, grass_region, regional_date
;
