-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_query_cat_count_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_query_cat_count_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_query_cat_count_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_query_cat_count_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_keyword_query_cat_count_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_query_cat_count_1d.sql
-- deprecated: False
-- sha256: ec09b6dda1f0315d6a9e38ecf7d30285b62753123202b0b68e9e4f8df6b31098
CREATE TEMPORARY VIEW item_cats_${grass_region_without_quote} AS
SELECT
    item_id
    ,INLINE(ARRAY(
        STRUCT(COALESCE(level1_global_be_category_id, 0) AS category_id, 1 AS level)
        ,STRUCT(COALESCE(level2_global_be_category_id, 0) AS category_id, 2 AS level)
        ,STRUCT(COALESCE(level3_global_be_category_id, 0) AS category_id, 3 AS level)
        ,STRUCT(COALESCE(level4_global_be_category_id, 0) AS category_id, 4 AS level)
        ,STRUCT(COALESCE(level5_global_be_category_id, 0) AS category_id, 5 AS level)
    ))
FROM
    srdi_mart.dim_sr_data_warehouse_item
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
UNION ALL 
SELECT
    a.item_id 
    ,INLINE(ARRAY(
        STRUCT(COALESCE(a.level1_global_be_category_id, 0) AS category_id, 1 AS level)
        ,STRUCT(COALESCE(a.level2_global_be_category_id, 0) AS category_id, 2 AS level)
        ,STRUCT(COALESCE(a.level3_global_be_category_id, 0) AS category_id, 3 AS level)
        ,STRUCT(COALESCE(a.level4_global_be_category_id, 0) AS category_id, 4 AS level)
        ,STRUCT(COALESCE(a.level5_global_be_category_id, 0) AS category_id, 5 AS level)
    ))
FROM
    mp_item.dim_dp_item__reg_s0_live a
    LEFT JOIN srdi_mart.dim_sr_data_warehouse_item b
    ON a.grass_region = b.grass_region
    AND a.grass_date = b.local_date 
    AND a.item_id = b.item_id
WHERE
    a.grass_region = ${grass_region}
    AND a.grass_date = ${local_date}
    AND a.tz_type = 'local'
    AND b.item_id IS NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW clk_imp_counts_${grass_region_without_quote} AS
SELECT
    TRIM(LOWER(keyword)) AS keyword
    ,item_id
    ,operation
    ,SUM(operation_cnt) AS count
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND keyword IS NOT NULL
    AND page_type IN ('global_search')
    AND COALESCE(is_ads, false) = false
    AND target_type = 'item'
    AND sort_type = 'relevancy'
    AND operation IN ('click', 'impression')
GROUP BY
    1,2,3;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_keyword_query_cat_count_1d
PARTITION (
    country = ${grass_region}
    ,dt = ${local_date}
    ,operation
)
SELECT
    keyword
    ,category_id
    ,true
    ,level
    ,SUM(count)
    ,'click'
FROM
    clk_imp_counts_${grass_region_without_quote} a
JOIN
    item_cats_${grass_region_without_quote} b
ON
    a.item_id = b.item_id
WHERE
    a.operation = 'click'
GROUP BY
    keyword
    ,level
    ,category_id
UNION ALL
SELECT
    keyword
    ,category_id
    ,true
    ,level
    ,SUM(count)
    ,'impression'
FROM
    clk_imp_counts_${grass_region_without_quote} a
JOIN
    item_cats_${grass_region_without_quote} b
ON
    a.item_id = b.item_id
WHERE
    a.operation = 'impression'
GROUP BY
    keyword
    ,level
    ,category_id;
