-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_mab_layer_metrics_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_search_mab_layer_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_mab_layer_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_mab_layer_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_search_mab_layer_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_mab_layer_metrics_1d.sql
-- deprecated: False
-- sha256: 4aa960b0ea4b6f865e205bb276243d2880611e682a49ae6b918accb444b3f5af
CREATE TEMPORARY VIEW raw_dim_and_metrics_${grass_region_without_quote} AS
SELECT
    item_id
    ,COALESCE(CAST(level1_global_be_category_id AS STRING), '') AS level1_global_be_category_id
    ,CAST(has_video AS STRING) AS has_video
    ,CAST(skip_mab AS STRING) AS skip_mab
    ,card_type
    ,COUNT(DISTINCT CASE WHEN content_id = '__ALL__' THEN NULL ELSE content_id END) AS content_id_count
    ,SUM(IF(content_id = '__ALL__', imp_cnt, 0)) AS imp_cnt
    ,SUM(IF(content_id = '__ALL__', click_cnt, 0)) AS click_cnt
    ,SUM(IF(content_id = '__ALL__', order_cnt, 0)) AS order_cnt
    ,SUM(IF(content_id = '__ALL__', gmv, 0)) AS gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND sub_product_type = '__ALL__'
GROUP BY
    1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_item_cat_${grass_region_without_quote} AS
SELECT DISTINCT
    COALESCE(level1_global_be_category, '') AS level1_global_be_category
    ,COALESCE(CAST(level1_global_be_category_id AS STRING), '') AS level1_global_be_category_id
FROM
    srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND card_type = '__ALL__'
    AND content_id = '__ALL__'
    AND sub_product_type = '__ALL__';

--sql_divide_splitter--

CREATE TEMPORARY VIEW calculated_dim_raw_${grass_region_without_quote} AS
SELECT
    item_id
    ,MAX(IF(card_type = '__ALL__' AND content_id = '__ALL__' AND sub_product_type = '__ALL__' AND order_cnt > 0.0, 'true', 'false')) AS has_order
    ,MAX(item_cum_order_prop) AS item_cum_order_prop
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'video' AND content_id = '__ALL__' AND sub_product_type = '__ALL__', ctr_x_cr, NULL), TRUE) AS avg_video_card_ctr_x_cr
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'item' AND content_id = '__ALL__' AND sub_product_type = 'not_ads', ctr_x_cr, NULL), TRUE) AS avg_org_item_ctr_x_cr
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'item' AND content_id = '__ALL__' AND sub_product_type = 'roi2.0', ctr_x_cr, NULL), TRUE) AS avg_roi2_item_ctr_x_cr
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'video' AND content_id != '__ALL__' AND sub_product_type = '__ALL__' AND video_ctr_x_cr_rank = 1, ctr_x_cr, NULL), TRUE) AS best_video_card_ctr_x_cr
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'item' AND content_id != '__ALL__' AND sub_product_type = 'not_ads' AND image_ctr_x_cr_rank = 1, ctr_x_cr, NULL), TRUE) AS best_org_item_ctr_x_cr
    ,FIRST(IF(imp_cnt > 0 AND card_type = 'item' AND content_id != '__ALL__' AND sub_product_type = 'roi2.0' AND image_ctr_x_cr_rank = 1, ctr_x_cr, NULL), TRUE) AS best_roi2_item_ctr_x_cr
    ,COUNT(DISTINCT IF(card_type = 'item' AND content_id != '__ALL__' AND sub_product_type = '__ALL__', content_id, NULL)) AS image_cnt
    ,COUNT(DISTINCT IF(card_type = 'video' AND content_id != '__ALL__' AND sub_product_type = '__ALL__', content_id, NULL)) AS video_cnt
FROM
    srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW calculated_dim_mid_${grass_region_without_quote} AS
SELECT
    item_id
    ,has_order
    ,CASE
        WHEN item_cum_order_prop <= 0.1 THEN 'top10%'
        WHEN item_cum_order_prop > 0.1 AND item_cum_order_prop <= 0.2 THEN 'top20%'
        WHEN item_cum_order_prop > 0.2 AND item_cum_order_prop <= 0.3 THEN 'top30%'
        WHEN item_cum_order_prop > 0.3 AND item_cum_order_prop <= 0.4 THEN 'top40%'
        WHEN item_cum_order_prop > 0.4 AND item_cum_order_prop <= 0.5 THEN 'top50%'
        WHEN item_cum_order_prop > 0.5 AND item_cum_order_prop <= 0.6 THEN 'top60%'
        WHEN item_cum_order_prop > 0.6 AND item_cum_order_prop <= 0.7 THEN 'top70%'
        WHEN item_cum_order_prop > 0.7 AND item_cum_order_prop <= 0.8 THEN 'top80%'
        WHEN item_cum_order_prop > 0.8 AND item_cum_order_prop <= 0.9 THEN 'top90%'
        ELSE 'top100%'
    END AS cum_order_prop_layer
    ,avg_video_card_ctr_x_cr / avg_org_item_ctr_x_cr AS avg_video_org_competiveness
    ,avg_video_card_ctr_x_cr / avg_roi2_item_ctr_x_cr AS avg_video_roi2_competiveness
    ,best_video_card_ctr_x_cr / best_org_item_ctr_x_cr AS best_video_org_competiveness
    ,best_video_card_ctr_x_cr / best_roi2_item_ctr_x_cr AS best_video_roi2_competiveness

    -- Below 4 lines for '>100%' which more specifically means a > b where b can be 0.0 instead of a / b > 1.0
    ,CASE
        WHEN avg_video_card_ctr_x_cr > avg_org_item_ctr_x_cr THEN 'true'
        ELSE 'false'
    END AS is_avg_video_org_100p
    ,CASE
        WHEN avg_video_card_ctr_x_cr > avg_roi2_item_ctr_x_cr THEN 'true'
        ELSE 'false'
    END AS is_avg_video_roi2_100p
    ,CASE
        WHEN best_video_card_ctr_x_cr > best_org_item_ctr_x_cr THEN 'true'
        ELSE 'false'
    END AS is_best_video_org_100p
    ,CASE
        WHEN best_video_card_ctr_x_cr > best_roi2_item_ctr_x_cr THEN 'true'
        ELSE 'false'
    END AS is_best_video_roi2_100p

    -- Below 4 lines depends on dws_sr_data_warehouse_search_card_mab_analysis_1d
    -- using COALESCE(SUM(order_cnt) / SUM(imp_cnt), 0) for ctr_x_cr
    -- therefore as long as IS NOT NULL there was impression to be counted in 'overall' category
    ,IF(avg_video_card_ctr_x_cr IS NOT NULL AND avg_org_item_ctr_x_cr IS NOT NULL, 'true', 'false') AS is_overall_avg_video_org
    ,IF(avg_video_card_ctr_x_cr IS NOT NULL AND avg_roi2_item_ctr_x_cr IS NOT NULL, 'true', 'false') AS is_overall_avg_video_roi2
    ,IF(best_video_card_ctr_x_cr IS NOT NULL AND best_org_item_ctr_x_cr IS NOT NULL, 'true', 'false') AS is_overall_best_video_org
    ,IF(best_video_card_ctr_x_cr IS NOT NULL AND best_roi2_item_ctr_x_cr IS NOT NULL, 'true', 'false') AS is_overall_best_video_roi2
    ,image_cnt
    ,video_cnt
FROM
    calculated_dim_raw_${grass_region_without_quote};

--sql_divide_splitter--
CREATE TEMPORARY VIEW calculated_dim_${grass_region_without_quote} AS
SELECT
    item_id
    ,has_order
    ,cum_order_prop_layer
    ,CASE
        WHEN 2.0 <= avg_video_org_competiveness THEN '>=200%'
        WHEN 1.8 <= avg_video_org_competiveness AND avg_video_org_competiveness < 2.0 THEN '180%-200%'
        WHEN 1.6 <= avg_video_org_competiveness AND avg_video_org_competiveness < 1.8 THEN '160%-180%'
        WHEN 1.4 <= avg_video_org_competiveness AND avg_video_org_competiveness < 1.6 THEN '140%-160%'
        WHEN 1.2 <= avg_video_org_competiveness AND avg_video_org_competiveness < 1.4 THEN '120%-140%'
        WHEN 1.0 <= avg_video_org_competiveness AND avg_video_org_competiveness < 1.2 THEN '100%-120%'
        WHEN 0.8 <= avg_video_org_competiveness AND avg_video_org_competiveness < 1.0 THEN '80%-100%'
        WHEN avg_video_org_competiveness < 0.8 THEN '<80%'
        WHEN avg_video_org_competiveness IS NULL THEN 'NULL'
    END AS avg_video_org_competiveness_layer
    ,CASE
        WHEN 2.0 <= avg_video_roi2_competiveness THEN '>=200%'
        WHEN 1.8 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 2.0 THEN '180%-200%'
        WHEN 1.6 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 1.8 THEN '160%-180%'
        WHEN 1.4 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 1.6 THEN '140%-160%'
        WHEN 1.2 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 1.4 THEN '120%-140%'
        WHEN 1.0 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 1.2 THEN '100%-120%'
        WHEN 0.8 <= avg_video_roi2_competiveness AND avg_video_roi2_competiveness < 1.0 THEN '80%-100%'
        WHEN avg_video_roi2_competiveness < 0.8 THEN '<80%'
        WHEN avg_video_roi2_competiveness IS NULL THEN 'NULL'
    END AS avg_video_roi2_competiveness_layer
    ,CASE
        WHEN 2.0 <= best_video_org_competiveness THEN '>=200%'
        WHEN 1.8 <= best_video_org_competiveness AND best_video_org_competiveness < 2.0 THEN '180%-200%'
        WHEN 1.6 <= best_video_org_competiveness AND best_video_org_competiveness < 1.8 THEN '160%-180%'
        WHEN 1.4 <= best_video_org_competiveness AND best_video_org_competiveness < 1.6 THEN '140%-160%'
        WHEN 1.2 <= best_video_org_competiveness AND best_video_org_competiveness < 1.4 THEN '120%-140%'
        WHEN 1.0 <= best_video_org_competiveness AND best_video_org_competiveness < 1.2 THEN '100%-120%'
        WHEN 0.8 <= best_video_org_competiveness AND best_video_org_competiveness < 1.0 THEN '80%-100%'
        WHEN best_video_org_competiveness < 0.8 THEN '<80%'
        WHEN best_video_org_competiveness IS NULL THEN 'NULL'
    END AS best_video_org_competiveness_layer
    ,CASE
        WHEN 2.0 <= best_video_roi2_competiveness THEN '>=200%'
        WHEN 1.8 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 2.0 THEN '180%-200%'
        WHEN 1.6 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 1.8 THEN '160%-180%'
        WHEN 1.4 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 1.6 THEN '140%-160%'
        WHEN 1.2 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 1.4 THEN '120%-140%'
        WHEN 1.0 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 1.2 THEN '100%-120%'
        WHEN 0.8 <= best_video_roi2_competiveness AND best_video_roi2_competiveness < 1.0 THEN '80%-100%'
        WHEN best_video_roi2_competiveness < 0.8 THEN '<80%'
        WHEN best_video_roi2_competiveness IS NULL THEN 'NULL'
    END AS best_video_roi2_competiveness_layer
    ,is_avg_video_org_100p
    ,is_avg_video_roi2_100p
    ,is_best_video_org_100p
    ,is_best_video_roi2_100p
    ,is_overall_avg_video_org
    ,is_overall_avg_video_roi2
    ,is_overall_best_video_org
    ,is_overall_best_video_roi2
    ,CASE
        WHEN COALESCE(image_cnt, 0) > COALESCE(video_cnt, 0) THEN 'image'
        WHEN COALESCE(image_cnt, 0) < COALESCE(video_cnt, 0) THEN 'video'
        ELSE 'others'
    END AS main_type
FROM
    calculated_dim_mid_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW raw_join_calculated_dim_${grass_region_without_quote} AS
SELECT
    a.item_id AS item_id
    ,card_type
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,has_order
    ,cum_order_prop_layer
    ,avg_video_org_competiveness_layer
    ,avg_video_roi2_competiveness_layer
    ,best_video_org_competiveness_layer
    ,best_video_roi2_competiveness_layer
    ,is_avg_video_org_100p
    ,is_avg_video_roi2_100p
    ,is_best_video_org_100p
    ,is_best_video_roi2_100p
    ,is_overall_avg_video_org
    ,is_overall_avg_video_roi2
    ,is_overall_best_video_org
    ,is_overall_best_video_roi2
    ,main_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv
    ,content_id_count
FROM
    raw_dim_and_metrics_${grass_region_without_quote} a
JOIN
    calculated_dim_${grass_region_without_quote} b
ON
    a.item_id = b.item_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW grouped_metrics_mid_${grass_region_without_quote} AS
SELECT
    card_type
    ,IF(level1_global_be_category_id IS NOT NULL, level1_global_be_category_id, '__ALL__') AS level1_global_be_category_id
    ,IF(has_video IS NOT NULL, has_video, '__ALL__') AS has_video
    ,IF(skip_mab IS NOT NULL, skip_mab, '__ALL__') AS skip_mab
    ,IF(has_order IS NOT NULL, has_order, '__ALL__') AS has_order
    ,IF(cum_order_prop_layer IS NOT NULL, cum_order_prop_layer, '__ALL__') AS cum_order_prop_layer
    ,is_overall_avg_video_org
    ,is_avg_video_org_100p
    ,avg_video_org_competiveness_layer
    ,is_overall_avg_video_roi2
    ,is_avg_video_roi2_100p
    ,avg_video_roi2_competiveness_layer
    ,is_overall_best_video_org
    ,is_best_video_org_100p
    ,best_video_org_competiveness_layer
    ,is_overall_best_video_roi2
    ,is_best_video_roi2_100p
    ,best_video_roi2_competiveness_layer
    ,main_type
    ,SUM(IF(imp_cnt > 0, 1, 0)) AS imp_item_cnt
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(IF(card_type = 'item', content_id_count, 0)) AS avg_image_cnt_numerator
    ,SUM(IF(card_type = 'item', 1, 0)) AS avg_image_cnt_denominator
    ,SUM(IF(card_type = 'video', content_id_count, 0)) AS avg_video_cnt_numerator
    ,SUM(IF(card_type = 'video', 1, 0)) AS avg_video_cnt_denominator
FROM
    raw_join_calculated_dim_${grass_region_without_quote}
GROUP BY
    card_type -- upstream already has __ALL__
    ,CUBE(level1_global_be_category_id, has_video, skip_mab, has_order, cum_order_prop_layer)
    ,is_overall_avg_video_org
    ,is_avg_video_org_100p
    ,avg_video_org_competiveness_layer
    ,is_overall_avg_video_roi2
    ,is_avg_video_roi2_100p
    ,avg_video_roi2_competiveness_layer
    ,is_overall_best_video_org
    ,is_best_video_org_100p
    ,best_video_org_competiveness_layer
    ,is_overall_best_video_roi2
    ,is_best_video_roi2_100p
    ,best_video_roi2_competiveness_layer
    ,main_type;

--sql_divide_splitter--

CREATE TEMPORARY VIEW grouped_metrics_${grass_region_without_quote} AS
SELECT
    card_type
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,has_order
    ,cum_order_prop_layer
    ,CASE
        WHEN is_overall_avg_video_org = 'true' THEN 'overall'
        WHEN is_avg_video_org_100p = 'true' THEN '>100%'
        WHEN avg_video_org_competiveness_layer IS NOT NULL THEN avg_video_org_competiveness_layer
        ELSE '__ALL__'
    END AS avg_video_org_competiveness_layer
    ,CASE
        WHEN is_overall_avg_video_roi2 = 'true' THEN 'overall'
        WHEN is_avg_video_roi2_100p = 'true' THEN '>100%'
        WHEN avg_video_roi2_competiveness_layer IS NOT NULL THEN avg_video_roi2_competiveness_layer
        ELSE '__ALL__'
    END AS avg_video_roi2_competiveness_layer
    ,CASE
        WHEN is_overall_best_video_org = 'true' THEN 'overall'
        WHEN is_best_video_org_100p = 'true' THEN '>100%'
        WHEN best_video_org_competiveness_layer IS NOT NULL THEN best_video_org_competiveness_layer
        ELSE '__ALL__'
    END AS best_video_org_competiveness_layer
    ,CASE
        WHEN is_overall_best_video_roi2 = 'true' THEN 'overall'
        WHEN is_best_video_roi2_100p = 'true' THEN '>100%'
        WHEN best_video_roi2_competiveness_layer IS NOT NULL THEN best_video_roi2_competiveness_layer
        ELSE '__ALL__'
    END AS best_video_roi2_competiveness_layer
    ,main_type
    ,SUM(imp_item_cnt) AS imp_item_cnt
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(avg_image_cnt_numerator) AS avg_image_cnt_numerator
    ,SUM(avg_image_cnt_denominator) AS avg_image_cnt_denominator
    ,SUM(avg_video_cnt_numerator) AS avg_video_cnt_numerator
    ,SUM(avg_video_cnt_denominator) AS avg_video_cnt_denominator
FROM
    grouped_metrics_mid_${grass_region_without_quote}
GROUP BY
    card_type
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,has_order
    ,cum_order_prop_layer
    ,CUBE(is_overall_avg_video_org, is_avg_video_org_100p, avg_video_org_competiveness_layer
         ,is_overall_avg_video_roi2, is_avg_video_roi2_100p, avg_video_roi2_competiveness_layer
         ,is_overall_best_video_org, is_best_video_org_100p, best_video_org_competiveness_layer
         ,is_overall_best_video_roi2, is_best_video_roi2_100p, best_video_roi2_competiveness_layer)
    ,main_type
HAVING
-- For each of the 4 layer columns, either is
-- 1. original layer category
-- 2. 'overall' category when is_overall_xxx = 'true'
-- 3. '>100%' category when is_xxx_100p = 'true'
    (
        (is_overall_avg_video_org IS NULL AND is_avg_video_org_100p IS NULL)
        OR (is_overall_avg_video_org = 'true' AND is_avg_video_org_100p IS NULL AND avg_video_org_competiveness_layer IS NULL)
        OR (is_overall_avg_video_org IS NULL AND is_avg_video_org_100p = 'true' AND avg_video_org_competiveness_layer IS NULL)
    ) AND (
        (is_overall_avg_video_roi2 IS NULL AND is_avg_video_roi2_100p IS NULL)
        OR (is_overall_avg_video_roi2 = 'true' AND is_avg_video_roi2_100p IS NULL AND avg_video_roi2_competiveness_layer IS NULL)
        OR (is_overall_avg_video_roi2 IS NULL AND is_avg_video_roi2_100p = 'true' AND avg_video_roi2_competiveness_layer IS NULL)
    ) AND (
        (is_overall_best_video_org IS NULL AND is_best_video_org_100p IS NULL)
        OR (is_overall_best_video_org = 'true' AND is_best_video_org_100p IS NULL AND best_video_org_competiveness_layer IS NULL)
        OR (is_overall_best_video_org IS NULL AND is_best_video_org_100p = 'true' AND best_video_org_competiveness_layer IS NULL)
    ) AND (
        (is_overall_best_video_roi2 IS NULL AND is_best_video_roi2_100p IS NULL)
        OR (is_overall_best_video_roi2 = 'true' AND is_best_video_roi2_100p IS NULL AND best_video_roi2_competiveness_layer IS NULL)
        OR (is_overall_best_video_roi2 IS NULL AND is_best_video_roi2_100p = 'true' AND best_video_roi2_competiveness_layer IS NULL)
    );

--sql_divide_splitter--

CREATE TEMPORARY VIEW pct_denominator_${grass_region_without_quote} AS
SELECT
    card_type
    ,SUM(imp_cnt) AS imp_cnt_denominator
    ,SUM(order_cnt) AS order_cnt_denominator
FROM
    srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND content_id = '__ALL__'
    AND sub_product_type = '__ALL__'
GROUP BY
    1;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.ads_sr_data_warehouse_search_mab_layer_metrics_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
/*+ BROADCASTJOIN(b) */
/*+ BROADCASTJOIN(c) */
    a.card_type AS card_type
    ,IF(b.level1_global_be_category_id IS NOT NULL, b.level1_global_be_category, '__ALL__') AS level1_global_be_category
    ,a.level1_global_be_category_id AS level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,has_order
    ,cum_order_prop_layer
    ,avg_video_org_competiveness_layer
    ,avg_video_roi2_competiveness_layer
    ,best_video_org_competiveness_layer
    ,best_video_roi2_competiveness_layer
    ,main_type
    ,imp_item_cnt
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv
    ,avg_image_cnt_numerator / avg_image_cnt_denominator AS avg_image_cnt
    ,avg_video_cnt_numerator / avg_video_cnt_denominator AS avg_video_cnt
    ,order_cnt / order_cnt_denominator AS order_pct
    ,imp_cnt / imp_cnt_denominator AS imp_pct
FROM
    grouped_metrics_${grass_region_without_quote} a
LEFT JOIN
    dim_item_cat_${grass_region_without_quote} b
ON
    a.level1_global_be_category_id = b.level1_global_be_category_id
LEFT JOIN
    pct_denominator_${grass_region_without_quote} c
ON
    a.card_type = c.card_type;
