-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_level_metrics_30d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_keyword_level_metrics_30d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_level_metrics_30d.sql
-- deprecated: False
-- sha256: de2a44c4410fafc3bc0d6501c56396ce4d15be09b41738f6fd0f17bc806a0caf
CACHE TABLE dws_search_volume_30d_${grass_region_without_quote} OPTIONS ('storageLevel' 'DISK_ONLY') AS 
SELECT
    trim(lower(keyword)) AS keyword
    ,COUNT(DISTINCT CASE WHEN view_cnt != 0 AND local_date = ${local_date} THEN (device_id, user_id) END) AS search_volume_1d
    ,COUNT(DISTINCT CASE WHEN view_cnt != 0 AND local_date >= date_sub(${local_date}, 6) THEN (device_id, user_id) END) AS search_volume_7d
    ,COUNT(DISTINCT CASE WHEN view_cnt != 0 AND local_date >= date_sub(${local_date}, 29) THEN (device_id, user_id) END) AS search_volume_30d
FROM
    srdi_mart.dws_sr_data_warehouse_search_srp_user_benchmark_1d
WHERE
    local_date BETWEEN date_sub(${local_date}, 29) AND ${local_date}
    AND grass_region = ${grass_region}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND view_cnt > 0
    AND keyword != ''
    AND keyword is not null
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW keyword_search_rank_pct_${grass_region_without_quote} AS
SELECT
    keyword
    ,search_volume_1d
    ,RANK() OVER(ORDER BY search_volume_1d DESC) as keyword_search_volume_rank
    ,SUM(search_volume_1d) OVER(ORDER BY search_volume_1d DESC) / sum(search_volume_1d) OVER() AS keyword_cumulative_search_volume_percentile
FROM
    dws_search_volume_30d_${grass_region_without_quote}
WHERE
    search_volume_1d > 0;

--sql_divide_splitter--

CACHE TABLE keyword_search_rank_pct_type_${grass_region_without_quote} OPTIONS ('storageLevel' 'DISK_ONLY') AS
SELECT 
    keyword
    ,search_volume_1d
    ,keyword_search_volume_rank
    ,keyword_cumulative_search_volume_percentile
    ,CASE
        WHEN search_volume_1d = 1 THEN '6.volume=1'
        WHEN keyword_search_volume_rank <= 300 THEN '1.top 300'
        WHEN keyword_cumulative_search_volume_percentile <= 0.2 THEN '2.0%-20%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.5 THEN '3.20%-50%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.8 THEN '4.50%-80%'
        WHEN keyword_cumulative_search_volume_percentile <= 1.0 THEN '5.80%-100%'
        ELSE NULL
    END AS keyword_search_volume_type
FROM
    keyword_search_rank_pct_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_search_user_keyword_${grass_region_without_quote} AS 
SELECT
    user_id
    ,device_id
    ,trim(lower(keyword)) AS keyword
    ,if(target_type IS NOT NULL, target_type, 'NA') AS target_type
    ,IF(is_ads IS NOT NULL, cast(is_ads AS STRING), 'false') AS is_ads
    ,local_date
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_srp_user_benchmark_1d
WHERE
    local_date BETWEEN date_sub(${local_date}, 29) AND ${local_date}
    AND grass_region = ${grass_region}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND (
        target_type IN ('item', 'video', 'livestream')
        OR view_cnt > 0
    )
    AND COALESCE(keyword, '') != ''
GROUP BY
    1,2,3,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_keyword_30d_${grass_region_without_quote} AS 
SELECT
    user_id
    ,keyword
    ,if(target_type IS NOT NULL, target_type, '__ALL__') AS target_type
    ,if(is_ads IS NOT NULL, cast(is_ads AS STRING), '__ALL__') AS is_ads
    ,MAX(CASE WHEN local_date = ${local_date} THEN TRUE ELSE FALSE END) AS is_search_1d
    ,MAX(CASE WHEN local_date >= date_sub(${local_date}, 6) THEN TRUE ELSE FALSE END) AS is_search_7d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN imp_cnt ELSE NULL END) AS imp_cnt_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN imp_cnt ELSE NULL END) imp_cnt_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN imp_cnt ELSE NULL END) imp_cnt_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN click_cnt ELSE NULL END) AS click_cnt_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN click_cnt ELSE NULL END) click_cnt_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN click_cnt ELSE NULL END) click_cnt_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN ppv_cnt ELSE NULL END) AS ppv_cnt_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN ppv_cnt ELSE NULL END) ppv_cnt_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN ppv_cnt ELSE NULL END) ppv_cnt_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN cart_cnt ELSE NULL END) AS cart_cnt_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN cart_cnt ELSE NULL END) cart_cnt_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN cart_cnt ELSE NULL END) cart_cnt_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN order_cnt ELSE NULL END) AS order_cnt_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN order_cnt ELSE NULL END) order_cnt_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN order_cnt ELSE NULL END) order_cnt_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN gmv ELSE NULL END) AS gmv_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN gmv ELSE NULL END) gmv_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN gmv ELSE NULL END) gmv_30d
    ,SUM(CASE WHEN local_date = ${local_date}  THEN pc2_gmv ELSE NULL END) AS pc2_gmv_1d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 6)  THEN pc2_gmv ELSE NULL END) pc2_gmv_7d
    ,SUM(CASE WHEN local_date >= date_sub(${local_date}, 29)  THEN pc2_gmv ELSE NULL END) pc2_gmv_30d
FROM
    dwm_search_user_keyword_${grass_region_without_quote}
GROUP BY GROUPING SETS
(
    (user_id, keyword, target_type, is_ads), (user_id, keyword, target_type),(user_id, keyword, is_ads), (user_id, keyword)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_keyword_${grass_region_without_quote} AS 
SELECT
    keyword,
    keyword_cluster,
    level1_keyword_category,
    level2_keyword_category
FROM
    (
        SELECT
            *,
            row_number() over (partition by keyword order by local_date DESC) as rn
        FROM
            srdi_mart.dim_sr_data_warehouse_keyword_di
        WHERE 
            local_date BETWEEN date_sub(${local_date}, 29) AND ${local_date}
            AND grass_region = ${grass_region}
    )
WHERE 
    rn = 1;

--sql_divide_splitter--

CACHE TABLE dws_keyword_metrics_${grass_region_without_quote} OPTIONS ('storageLevel' 'DISK_ONLY') AS 
SELECT
    a.keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,target_type AS card_type
    ,is_ads
    ,MAX(is_search_1d) AS is_search_1d
    ,MAX(is_search_7d) AS is_search_7d
    ,SUM(IF(is_search_1d = TRUE AND a.user_id > 0, 1, NULL)) AS user_count_1d
    ,SUM(IF(is_search_7d = TRUE AND a.user_id > 0, 1, NULL)) AS user_count_7d
    ,SUM(IF(a.user_id > 0, 1, NULL)) AS user_count_30d
    ,SUM(imp_cnt_1d) AS imp_cnt_1d
    ,SUM(imp_cnt_7d) imp_cnt_7d
    ,SUM(imp_cnt_30d) AS imp_cnt_30d
    ,SUM(click_cnt_1d) AS click_cnt_1d
    ,SUM(click_cnt_7d) click_cnt_7d
    ,SUM(click_cnt_30d) click_cnt_30d
    ,SUM(ppv_cnt_1d) AS ppv_cnt_1d
    ,SUM(ppv_cnt_7d) ppv_cnt_7d
    ,SUM(ppv_cnt_30d) ppv_cnt_30d
    ,SUM(cart_cnt_1d) AS cart_cnt_1d
    ,SUM(cart_cnt_7d) cart_cnt_7d
    ,SUM(cart_cnt_30d) cart_cnt_30d
    ,SUM(order_cnt_1d) AS order_cnt_1d
    ,SUM(order_cnt_7d) AS order_cnt_7d
    ,SUM(order_cnt_30d) AS order_cnt_30d
    ,SUM(gmv_1d) AS gmv_1d
    ,SUM(gmv_7d) AS gmv_7d
    ,SUM(gmv_30d) AS gmv_30d
    ,SUM(pc2_gmv_1d) AS pc2_gmv_1d
    ,SUM(pc2_gmv_7d) AS pc2_gmv_7d
    ,SUM(pc2_gmv_30d) AS pc2_gmv_30d
    ,SUM(IF(imp_cnt_1d > 0 AND a.user_id > 0, 1, NULL)) AS imp_uu_1d
    ,SUM(IF(imp_cnt_7d > 0 AND a.user_id > 0, 1, NULL)) AS imp_uu_7d
    ,SUM(IF(imp_cnt_30d > 0 AND a.user_id > 0, 1, NULL)) AS imp_uu_30d
    ,SUM(IF(click_cnt_1d > 0 AND a.user_id > 0, 1, NULL)) AS click_uu_1d
    ,SUM(IF(click_cnt_7d > 0 AND a.user_id > 0, 1, NULL)) AS click_uu_7d
    ,SUM(IF(click_cnt_30d > 0 AND a.user_id > 0, 1, NULL)) AS click_uu_30d
    ,SUM(IF(ppv_cnt_1d > 0 AND a.user_id > 0, 1, NULL)) AS ppv_uu_1d
    ,SUM(IF(ppv_cnt_7d > 0 AND a.user_id > 0, 1, NULL)) AS ppv_uu_7d
    ,SUM(IF(ppv_cnt_30d > 0 AND a.user_id > 0, 1, NULL)) AS ppv_uu_30d
    ,SUM(IF(cart_cnt_1d > 0 AND a.user_id > 0, 1, NULL)) AS cart_uu_1d
    ,SUM(IF(cart_cnt_7d > 0 AND a.user_id > 0, 1, NULL)) AS cart_uu_7d
    ,SUM(IF(cart_cnt_30d > 0 AND a.user_id > 0, 1, NULL)) AS cart_uu_30d
    ,SUM(IF(order_cnt_1d > 0 AND a.user_id > 0, 1, NULL)) AS order_uu_1d
    ,SUM(IF(order_cnt_7d > 0 AND a.user_id > 0, 1, NULL)) AS order_uu_7d
    ,SUM(IF(order_cnt_30d > 0 AND a.user_id > 0, 1, NULL)) AS order_uu_30d
FROM
    dws_keyword_30d_${grass_region_without_quote} a
    LEFT JOIN dim_keyword_${grass_region_without_quote} b
    ON a.keyword = b.keyword
GROUP BY 1,2,3,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_search_user_cnt_30d_${grass_region_without_quote} AS
SELECT
    keyword
    ,MAX(CASE WHEN card_type = '__ALL__' AND is_ads = '__ALL__' THEN user_count_1d ELSE NULL END) AS user_count_1d
    ,MAX(CASE WHEN card_type = '__ALL__' AND is_ads = '__ALL__' THEN user_count_7d ELSE NULL END)  AS user_count_7d
    ,MAX(CASE WHEN card_type = '__ALL__' AND is_ads = '__ALL__' THEN user_count_30d ELSE NULL END) AS user_count_30d
FROM
    dws_keyword_metrics_${grass_region_without_quote}
GROUP BY 
    1;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_keyword_level_metrics_30d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
    ,time_range = 1
)
SELECT
    a.keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,a.is_ads
    ,a.card_type

    ,imp_cnt_1d AS imp_cnt
    ,click_cnt_1d AS click_cnt
    ,ppv_cnt_1d AS ppv_cnt
    ,cart_cnt_1d AS cart_cnt
    ,order_cnt_1d AS order_cnt
    ,gmv_1d AS gmv
    ,pc2_gmv_1d AS pc2_gmv
    
    ,imp_uu_1d AS imp_uu
    ,click_uu_1d AS click_uu
    ,ppv_uu_1d AS ppv_uu
    ,cart_uu_1d AS cart_uu
    ,order_uu_1d AS order_uu
    ,c.search_volume_1d AS search_volume
    ,b.user_count_1d AS user_count
    ,RANK() OVER (PARTITION BY level1_keyword_category, a.is_ads, a.card_type
        ORDER BY c.search_volume_1d DESC) AS search_volume_rank
    ,c.keyword_search_volume_rank AS keyword_search_volume_rank
    ,c.keyword_cumulative_search_volume_percentile as keyword_cumulative_search_volume_percentile
    ,c.keyword_search_volume_type as keyword_search_volume_type
FROM
    dws_keyword_metrics_${grass_region_without_quote} a
LEFT JOIN
    keyword_search_rank_pct_type_${grass_region_without_quote} c
ON
    a.keyword = c.keyword
LEFT JOIN
    dws_search_user_cnt_30d_${grass_region_without_quote} b
ON
    a.keyword = b.keyword
WHERE
    is_search_1d = TRUE;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_keyword_level_metrics_30d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
    ,time_range = 7
)
SELECT
    a.keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,a.is_ads
    ,a.card_type

    ,imp_cnt_7d AS imp_cnt
    ,click_cnt_7d AS click_cnt
    ,ppv_cnt_7d AS ppv_cnt
    ,cart_cnt_7d AS cart_cnt
    ,order_cnt_7d AS order_cnt
    ,gmv_7d AS gmv
    ,pc2_gmv_7d AS pc2_gmv
    
    ,imp_uu_7d AS imp_uu
    ,click_uu_7d AS click_uu
    ,ppv_uu_7d AS ppv_uu
    ,cart_uu_7d AS cart_uu
    ,order_uu_7d AS order_uu
    ,c.search_volume_7d AS search_volume
    ,b.user_count_7d AS user_count
    ,RANK() OVER (PARTITION BY level1_keyword_category, a.is_ads, a.card_type
        ORDER BY c.search_volume_7d DESC) AS search_volume_rank
    ,NULL AS keyword_search_volume_rank
    ,NULL as keyword_cumulative_search_volume_percentile
    ,NULL as keyword_search_volume_type
FROM
    dws_keyword_metrics_${grass_region_without_quote} a
LEFT JOIN
    dws_search_volume_30d_${grass_region_without_quote} c
ON
    a.keyword = c.keyword
LEFT JOIN
    dws_search_user_cnt_30d_${grass_region_without_quote} b
ON
    a.keyword = b.keyword
WHERE
    is_search_7d = TRUE;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_keyword_level_metrics_30d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
    ,time_range = 30
)
SELECT
    a.keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,a.is_ads
    ,a.card_type

    ,imp_cnt_30d AS imp_cnt
    ,click_cnt_30d AS click_cnt
    ,ppv_cnt_30d AS ppv_cnt
    ,cart_cnt_30d AS cart_cnt
    ,order_cnt_30d AS order_cnt
    ,gmv_30d AS gmv
    ,pc2_gmv_30d AS pc2_gmv
    
    ,imp_uu_30d AS imp_uu
    ,click_uu_30d AS click_uu
    ,ppv_uu_30d AS ppv_uu
    ,cart_uu_30d AS cart_uu
    ,order_uu_30d AS order_uu
    ,c.search_volume_30d AS search_volume
    ,b.user_count_30d AS user_count
    ,RANK() OVER (PARTITION BY level1_keyword_category, a.is_ads, a.card_type
        ORDER BY c.search_volume_30d DESC) AS search_volume_rank
    ,NULL AS keyword_search_volume_rank
    ,NULL as keyword_cumulative_search_volume_percentile
    ,NULL as keyword_search_volume_type
FROM
    dws_keyword_metrics_${grass_region_without_quote} a
LEFT JOIN
    dws_search_volume_30d_${grass_region_without_quote} c
ON
    a.keyword = c.keyword
LEFT JOIN
    dws_search_user_cnt_30d_${grass_region_without_quote} b
ON
    a.keyword = b.keyword;
