-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_keyword_top_rel_item_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_search_keyword_top_rel_item_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_keyword_top_rel_item_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_keyword_top_rel_item_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_search_keyword_top_rel_item_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_keyword_top_rel_item_1d.sql
-- deprecated: False
-- sha256: f1c77e7985f050a51fd89531564b0e6cc5af10e2819883737456a48018b17010
CREATE TEMPORARY VIEW keyword_search_rank_pct_${grass_region_without_quote} AS
SELECT
    keyword
    ,search_volume
    ,RANK() OVER(ORDER BY search_volume DESC) as keyword_search_volume_rank
    ,SUM(search_volume) OVER(ORDER BY search_volume DESC) / sum(search_volume) OVER() AS keyword_cumulative_search_volume_percentile
FROM
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND is_ads = '__ALL__'
    AND card_type = '__ALL__'
    AND time_range = 7
    and search_volume > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW filter_keyword_${grass_region_without_quote} AS 
SELECT 
    keyword
    ,search_volume
    ,keyword_search_volume_rank
    ,keyword_cumulative_search_volume_percentile
    ,CASE
        WHEN keyword_cumulative_search_volume_percentile <= 0.2 THEN '2.0%-20%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.5 THEN '3.20%-50%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.8 THEN '4.50%-80%'
    END AS keyword_search_volume_type
FROM
    keyword_search_rank_pct_${grass_region_without_quote}
WHERE
    keyword_cumulative_search_volume_percentile <= 0.8;

--sql_divide_splitter--

CREATE TEMPORARY VIEW base_table_${grass_region_without_quote} AS
SELECT 
    a.keyword 
    ,item_id
    ,keyword_search_volume_type
    ,max(shop_id) as shop_id
    ,sum(imp_cnt) as imp_cnt
    ,sum(click_cnt) as click_cnt
    ,sum(order_cnt) as order_cnt
    ,(cast(sum(imp_cnt) as double)/10000) + (cast(sum(click_cnt) as double) / 100) + (sum(order_cnt)*10) as rank_score
FROM
    srdi_mart.dwd_fp_search_base_1d a
    INNER JOIN filter_keyword_${grass_region_without_quote} b
    ON a.keyword = b.keyword
WHERE
    country = ${grass_region}
    AND dt BETWEEN date_sub(${local_date}, 6) AND ${local_date}
    AND rel_lx = 2
    AND user_id > 0
GROUP BY 
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW rank_table_${grass_region_without_quote} AS
SELECT 
    keyword 
    ,item_id 
    ,shop_id
    ,keyword_search_volume_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,rank_score
    ,ROW_NUMBER() OVER (partition by keyword ORDER BY rank_score DESC) AS item_rank
FROM
    base_table_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW sort_table_${grass_region_without_quote} AS
SELECT 
    *
FROM 
    rank_table_${grass_region_without_quote}
WHERE
    item_rank <= 30
ORDER BY 
    keyword, item_rank;
    
--sql_divide_splitter--

INSERT OVERWRITE TABLE srdi_mart.ads_sr_data_warehouse_search_keyword_top_rel_item_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
    keyword
    ,transform(collect_list(struct(item_id, shop_id)), x -> to_json(named_struct('shop_id', x.shop_id, 'item_id', x.item_id))) AS item_list
    ,transform(collect_list(struct(imp_cnt, click_cnt, order_cnt,item_rank)), x -> to_json(named_struct('imp_cnt', x.imp_cnt, 'click_cnt', x.click_cnt, 'order_cnt', x.order_cnt, 'item_rank', x.item_rank)) ) AS debug_list
FROM
    sort_table_${grass_region_without_quote}
GROUP BY 
    keyword
;
