-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_tc_all_cspu_link_df
-- physical_table: srdi_mart.dwd_sr_data_warehouse_tc_all_cspu_link_df
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_tc_all_cspu_link_df
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_tc_all_cspu_link_df.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dwd_sr_data_warehouse_tc_all_cspu_link_df/analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_tc_all_cspu_link_df.sql
-- deprecated: False
-- sha256: f6d1c6a62b3e86036297f620d2362c7cfa1961813aede6e08d15d00cfbaa9dc1
CREATE TEMPORARY VIEW cspu_model_${grass_region_without_quote} AS
select
    model_id
   ,cspu_id
   ,item_id
   ,shop_id
   ,biz_tag
from paimon.rcmd_feature.ods_sr_data_warehouse_tc_cspu_model_link
where grass_region in (${grass_region}) and status=1
-- by 20250429：biz_tag 不包含winner和cheapest的row，cspuid会被置null（手动删除也会是null，但是手动删除其余非modelid字段也是null）
and cspu_id is not null
-- by 20250807: biz_tag=0 的也释放进来了，这个属于释放了一些非high quality的modelid 进来，能分法到现有的就分发到现有的cspuid里去，不能的就新建cspuid，其biz_tag=0
-- by 20260130:newnew cspu更新了识别方式，包含退场为biz_tag=256，不包含退场为biz_tag=512
and ( (biz_tag & 1 > 0) or (biz_tag & 4 > 0) or (biz_tag & 8 > 0) )
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cspu_label_${grass_region_without_quote} AS
select
     cspu_id
    ,cspu_pr_rate
from srdi_mart.dws_sr_data_warehouse_tc_pb_cspu_level_1d
where grass_region in (${grass_region}) and local_date= ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW shop_type_${grass_region_without_quote} AS
select
     shop_id
    ,type as shop_scs_type
from regds_listing.dim_scs_shop_list_df
where grass_region in (${grass_region}) and type in ('scs-local','scs-cb')
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_model_${grass_region_without_quote} AS
select
     model_id
    ,model_status
    ,seller_status
    ,shop_status
    ,item_status
    ,model_stock
    ,item_stock
    ,model_price
    ,model_price_usd
    ,item_price
    ,item_price_usd
from mp_item.dim_model__reg_s0_live
where grass_region in (${grass_region})  and tz_type = 'local' and grass_date= ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_item_${grass_region_without_quote} AS
select
     item_id
    ,rating_score
    ,sold_cnt
from mp_item.dim_item__reg_s0_live
where grass_region in (${grass_region})  and tz_type = 'local' and grass_date= ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW model_order_${grass_region_without_quote} AS
select
     model_id
    ,max(placed_order_cnt_td) as placed_order_cnt_td
from mp_order.dws_sku_gmv_td__reg_s0_live
where grass_region in (${grass_region})  and tz_type = 'local' and grass_date= ${local_date}
group by
     model_id
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dwd_sr_data_warehouse_tc_all_cspu_link_df
PARTITION (grass_region = ${grass_region}, local_date = ${local_date})
select /*+ BROADCAST(b) */
     a.cspu_id
    ,a.model_id
    ,a.item_id
    ,a.shop_id
    ,a.biz_tag
    ,b.shop_scs_type
    ,f.cspu_pr_rate
    ,c.model_status
    ,c.seller_status
    ,c.shop_status
    ,c.item_status
    ,c.model_stock
    ,c.item_stock
    ,c.model_price
    ,c.model_price_usd
    ,c.item_price
    ,c.item_price_usd
    ,d.rating_score
    ,d.sold_cnt
    ,e.placed_order_cnt_td
    ,(case when model_status=1 and seller_status=1 and shop_status=1 and item_status=1 and model_price >0 then 1 else 0 end) as is_valid_model
from cspu_model_${grass_region_without_quote} a
left join cspu_label_${grass_region_without_quote} f on a.cspu_id=f.cspu_id -- 用这种方式暂时获得cspu_pr_rate
left join shop_type_${grass_region_without_quote} b on a.shop_id=b.shop_id
left join dim_model_${grass_region_without_quote} c on a.model_id=c.model_id
left join dim_item_${grass_region_without_quote}  d on a.item_id=d.item_id
left join model_order_${grass_region_without_quote} e on a.model_id=e.model_id
