-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_tc_item_group_di
-- physical_table: srdi_mart.dwd_sr_data_warehouse_tc_item_group_di
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_tc_item_group_di
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_tc_item_group_di.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dwd_sr_data_warehouse_tc_item_group_di/analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_tc_item_group_di.sql
-- deprecated: False
-- sha256: 512b7a01a8cf4055d0945c969669825e60b25f9f318185119047468dd6a229eb
CREATE TEMPORARY VIEW item_group_${grass_region_without_quote} AS
select
     *
    ,row_number() over (partition by rule_id,item_group_id, shop_id, item_id  order by local_hour desc) as rn
    ,max(item_group_if_ongoing) over (partition by rule_id,item_group_id, shop_id, item_id ) as today_item_group_if_ongoing
from srdi_mart.dwd_sr_data_warehouse_tc_item_group_hi
where grass_region IN (${grass_region}) and local_date = ${local_date}
and (target_type=5 or item_group_id is not null) --exclude dirty data and from 20231115 shouldn't have dirty data
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dwd_sr_data_warehouse_tc_item_group_di partition(grass_region = ${grass_region}, local_date=${local_date})
select
     item_id
    ,rule_id
    ,shop_id
    ,item_group_id
    ,target_group
    ,scenes
    ,item_group_start_time
    ,rule_start_time
    ,rule_end_time
    ,mtime
    ,task_status
    ,today_item_group_if_ongoing as item_group_if_ongoing
    ,item_group_target
from item_group_${grass_region_without_quote}
where rn=1
;
