-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d.sql
-- deprecated: False
-- sha256: 44f5af57b1efab4ee875b837bfde9c20ef4546af4d5fe117522b380cc87ce3ab
insert overwrite table ${schema}.dws_sr_data_warehouse_content_antifraud_scenario_level_order_metrics_1d
partition(grass_region = ${grass_region}, local_date)

select
    scenario
    ,is_ads
    ,antifraud_tag

    ,sum(order_cnt) as order_cnt
    ,sum(gmv) as gmv

    ,local_date
from
    srdi_mart.dws_sr_data_warehouse_content_antifraud_user_item_level_order_metrics_1d
where
    grass_region in (${grass_region})
    and local_date between date_add(date(${local_date}), -14) and date(${local_date})
group by
    scenario
    ,is_ads
    ,antifraud_tag
    ,local_date
;
