-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_platform_exp_level_report_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_platform_exp_level_report_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_platform_exp_level_report_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_platform_exp_level_report_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_platform_exp_level_report_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_platform_exp_level_report_1d.sql
-- deprecated: False
-- sha256: 52178e38b0a77e1d6c1e49525083140c69776e0ff50664128b16fc52d0294412
INSERT OVERWRITE TABLE srdi_mart.ads_sr_data_warehouse_platform_exp_level_report_1d
PARTITION (grass_region = ${grass_region}, local_date = ${local_date})
SELECT
    exp_group_id        as group_id
    ,case
        when scenario_tag = '__ALL__' then '__ALL__'
        else substring(scenario_tag, locate('business line ', scenario_tag) + length('business line '))
        end as report_business_line
    ,case
        when scenario_tag = '__ALL__' then '__ALL__'
        when scenario_tag like 'dpm business line %' then '__ALL__'
        else trim(substring(scenario_tag, locate('module ', scenario_tag) + length('module '), locate('business line ',scenario_tag) - locate('module ', scenario_tag) - length('module ')))
        end as report_module
    ,case
        when scenario_tag = '__ALL__' then '__ALL__'
        when scenario_tag like 'dpm business line %' then '__ALL__'
        when scenario_tag like 'dpm module %' then '__ALL__'
        else trim(substring(scenario_tag, locate('object ', scenario_tag) + length('object '), locate('module ',scenario_tag) - locate('object ', scenario_tag) - length('object ')))
        end as report_object
    , platform
    , is_ads

    ,imp_cnt
    ,click_cnt
    ,item_imp_cnt
    ,item_click_cnt
    ,ppv_cnt_exclude_isback as ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv

    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu

    ,omni_imp_cnt
    ,omni_click_cnt
    ,squared_imp_cnt
    ,squared_click_cnt
    ,squared_order_cnt
    ,squared_ppv_cnt_exclude_isback AS squared_ppv_cnt
    ,pc2_gmv

FROM 
    srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
WHERE
    grass_region = ${grass_region} 
    AND local_date = ${local_date}
    AND target_type = '__ALL__'
    AND feature_detail = '__ALL__'
    AND exp_type = 'assign_log_join'
    AND
    (scenario_tag like 'dpm business line %'
        OR scenario_tag like 'dpm reporting object %'
        OR scenario_tag like 'dpm module %'
        OR scenario_tag like '__ALL__'
    );
