-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d.sql
-- deprecated: False
-- sha256: fc6f696075251892eeda6a1aced8ae8ac1af5e60c2f4e081ae8fdd0f3f55a6ce
CREATE TEMPORARY VIEW user_exp_mapping_${grass_region_without_quote} AS
SELECT
    user_id
    ,exp_group_id
    ,experiment_id  
FROM
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND is_assignment_log = 1
    AND is_search_whitelist = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_item_${grass_region_without_quote}  AS
SELECT
    item_id
    ,level1_global_be_category_id
    ,level2_global_be_category_id
    ,level1_global_be_category
    ,level2_global_be_category
FROM
    srdi_mart.dim_sr_data_warehouse_item
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_search_${grass_region_without_quote} AS
SELECT
    user_id
    ,trim(lower(keyword)) AS keyword
    ,CASE
        WHEN platform in( 'android_app' ,'ios_app','android_app_lite','pc_web','android_web','ios_web') THEN platform
        ELSE 'other'
    END AS platform
    ,device_id
    ,COALESCE(cast(level1_global_be_category_id AS STRING), 'NA') AS level1_global_be_category_id
    ,COALESCE(cast(level2_global_be_category_id AS STRING), 'NA') AS level2_global_be_category_id
    ,COALESCE(cast(level1_global_be_category AS STRING), 'NA') AS level1_global_be_category
    ,COALESCE(cast(level2_global_be_category AS STRING), 'NA') AS level2_global_be_category
    
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(view_cnt) AS view_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    srdi_mart.dws_sr_data_warehouse_platform_user_item_keyword_benchmark_1d a
    LEFT JOIN dim_item_${grass_region_without_quote} b 
    ON a.item_id = b.item_id
WHERE 
    grass_region IN (${grass_region})
    AND local_date = ${local_date}
    AND feature_detail IN ('global_search', 'search_in_pdp', 'search_prefill',
    'global_search-item', 'search_in_pdp-item', 'search_prefill-item',
    'global_search-video', 'search_in_pdp-video', 'search_prefill-video',
    'global_search-livestream', 'search_in_pdp-livestream', 'search_prefill-livestream')
GROUP BY 
    1,2,3,4,5,6,7,8;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_exp_search_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,experiment_id
    ,COALESCE(platform, '__ALL__') AS platform
    ,COALESCE(level1_global_be_category_id, '__ALL__') AS level1_global_be_category_id
    ,COALESCE(level2_global_be_category_id, '__ALL__') AS level2_global_be_category_id
    ,COALESCE(level1_global_be_category, '__ALL__') AS level1_global_be_category
    ,COALESCE(level2_global_be_category, '__ALL__') AS level2_global_be_category

    ,SUM(imp_cnt) AS imp_cnt
    ,COUNT(DISTINCT (IF(imp_cnt > 0, a.user_id, NULL))) AS imp_uu
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    dwm_search_${grass_region_without_quote} a
    INNER JOIN user_exp_mapping_${grass_region_without_quote} b 
    ON a.user_id = b.user_id
GROUP BY GROUPING SETS
(
    (exp_group_id, experiment_id, platform, level1_global_be_category_id, level2_global_be_category_id, level1_global_be_category, level2_global_be_category)
    ,(exp_group_id, experiment_id, level1_global_be_category_id, level2_global_be_category_id, level1_global_be_category, level2_global_be_category)
    ,(exp_group_id, experiment_id, platform, level2_global_be_category_id, level2_global_be_category)
    ,(exp_group_id, experiment_id, level2_global_be_category_id, level2_global_be_category)
    ,(exp_group_id, experiment_id, platform, level1_global_be_category_id, level1_global_be_category)
    ,(exp_group_id, experiment_id, level1_global_be_category_id, level1_global_be_category)
    ,(exp_group_id, experiment_id, platform)
    ,(exp_group_id, experiment_id)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_exp_vol_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,experiment_id
    ,COALESCE(platform, '__ALL__') AS platform

    ,COUNT(DISTINCT (IF(view_cnt > 0, (a.user_id, device_id, keyword), NULL))) AS search_vol
    ,COUNT(DISTINCT (IF(click_cnt > 0, (a.user_id, device_id, keyword), NULL))) AS search_success_vol
FROM 
    dwm_search_${grass_region_without_quote} a
    INNER JOIN user_exp_mapping_${grass_region_without_quote} b 
    ON a.user_id = b.user_id
GROUP BY 
    exp_group_id
    ,experiment_id
    ,CUBE(platform);

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_ads_${grass_region_without_quote} AS
SELECT 
    user_id
    ,COALESCE(platform, 'other') AS platform
    ,COALESCE(cast(level1_global_be_category_id AS STRING), 'NA') AS level1_global_be_category_id
    ,COALESCE(cast(level2_global_be_category_id AS STRING), 'NA') AS level2_global_be_category_id
    ,COALESCE(cast(level1_global_be_category AS STRING), 'NA') AS level1_global_be_category
    ,COALESCE(cast(level2_global_be_category AS STRING), 'NA') AS level2_global_be_category
    ,sum(revenue_usd) as revenue_usd
FROM 
    srdi_mart.dws_sr_data_warehouse_ads_request_benchmark_advv_1d a
    LEFT JOIN dim_item_${grass_region_without_quote} b 
    ON a.item_id = b.item_id
WHERE 
    local_date = ${local_date}
    and grass_region = ${grass_region}
    and entrance = 1 --global search
GROUP BY 
    1,2,3,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_ads_performance_${grass_region_without_quote} AS 
SELECT
    exp_group_id
    ,experiment_id
    ,COALESCE(platform, '__ALL__') AS platform
    ,COALESCE(level1_global_be_category_id, '__ALL__') AS level1_global_be_category_id
    ,COALESCE(level2_global_be_category_id, '__ALL__') AS level2_global_be_category_id
    ,COALESCE(level1_global_be_category, '__ALL__') AS level1_global_be_category
    ,COALESCE(level2_global_be_category, '__ALL__') AS level2_global_be_category
    
    ,sum(revenue_usd) as revenue_usd
FROM 
    dws_ads_${grass_region_without_quote} a
    INNER JOIN user_exp_mapping_${grass_region_without_quote} user_exp
        ON a.user_id = user_exp.user_id
GROUP BY GROUPING SETS
(
    (exp_group_id, experiment_id, platform, level1_global_be_category_id, level2_global_be_category_id, level1_global_be_category, level2_global_be_category)
    ,(exp_group_id, experiment_id, level1_global_be_category_id, level2_global_be_category_id, level1_global_be_category, level2_global_be_category)
    ,(exp_group_id, experiment_id, platform, level2_global_be_category_id, level2_global_be_category)
    ,(exp_group_id, experiment_id, level2_global_be_category_id, level2_global_be_category)
    ,(exp_group_id, experiment_id, platform, level1_global_be_category_id, level1_global_be_category)
    ,(exp_group_id, experiment_id, level1_global_be_category_id, level1_global_be_category)
    ,(exp_group_id, experiment_id, platform)
    ,(exp_group_id, experiment_id)
);

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_abtest_item_category_platform_metrics_1d
PARTITION (
    grass_region=${grass_region},
    local_date=${local_date}
)
SELECT 
    a.exp_group_id
    ,a.experiment_id
    ,a.platform
    ,a.level1_global_be_category_id
    ,a.level2_global_be_category_id
    ,a.level1_global_be_category
    ,a.level2_global_be_category

    ,imp_cnt
    ,imp_uu
    ,click_cnt 
    ,order_cnt 
    ,gmv 
    ,pc2_gmv 
    ,search_vol
    ,search_success_vol
    ,revenue_usd AS ads_revenue_usd
FROM 
    dws_exp_search_${grass_region_without_quote} a
    LEFT JOIN dws_exp_vol_${grass_region_without_quote} b
        ON a.exp_group_id = b.exp_group_id
        AND a.platform = b.platform 
        AND a.level1_global_be_category = '__ALL__'
        AND a.level2_global_be_category = '__ALL__'
    LEFT JOIN exp_ads_performance_${grass_region_without_quote} c 
        ON a.exp_group_id = c.exp_group_id
        AND a.platform = c.platform 
        AND a.level1_global_be_category_id = c.level1_global_be_category_id
        AND a.level2_global_be_category_id = c.level2_global_be_category_id;
