-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
-- source_count: 3
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_exp_base_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d.sql
-- deprecated: False
-- sha256: e4ff692e73c23528656ae0c495f03fec846c00ba757ae5ca4cbd122e0ca1b589
CREATE TEMPORARY VIEW exp_filter_${grass_region_without_quote} as
select
    exp_group_id
from
    srdi_mart.dim_sr_data_warehouse_abtest_group
where
    local_date = ${local_date}
    and is_rcmd_whitelist = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_table_${grass_region_without_quote} AS
SELECT
    coalesce(platform, 'NULL') AS platform
    ,user_id
    ,feature_detail
    ,source1_feature_detail
    ,source2_feature_detail
    ,FILTER(scenario_tags,
        value -> value like '%DA_%'
            or value in (
                'dpm module Global Search business line Search'
                ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                ,'dpm module Daily Discover business line Homepage'
                ,'dpm module Private Domin business line Rcmd'
            )
    ) as scenario_tags
    ,FILTER(source1_scenario_tags,
        value -> value like '%DA_%'
            or value in (
                'dpm module Global Search business line Search'
                ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                ,'dpm module Daily Discover business line Homepage'
                ,'dpm module Private Domin business line Rcmd'
            )
    ) as source1_scenario_tags
    ,FILTER(source2_scenario_tags,
        value -> value like '%DA_%'
            or value in (
                'dpm module Global Search business line Search'
                ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                ,'dpm module Daily Discover business line Homepage'
                ,'dpm module Private Domin business line Rcmd'
            )
    ) as source2_scenario_tags
    ,cast(coalesce(is_ads, false) as string)   as is_ads
    ,exp_group_ids
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(if(is_back, 0, ppv_cnt)) AS ppv_cnt_exclude_isback
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(if(imp_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', imp_cnt, 0)) AS item_imp_cnt
    ,SUM(if(click_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', click_cnt, 0)) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM srdi_mart.dwm_sr_data_warehouse_platform_user_item
WHERE grass_region = ${grass_region} AND local_date = ${local_date}
    AND operation IN ('impression', 'click', 'ppv', 'cart', 'order')
GROUP BY
    1,2,3,4,5,6,7,8,9,10;

--sql_divide_splitter--

CREATE TEMPORARY VIEW explode_table_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,source1_feature_detail
    ,source2_feature_detail
    ,scenario_tags
    ,source1_scenario_tags
    ,source2_scenario_tags
    ,explode(exp_group_ids) AS exp_group_id
    ,user_id
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,ppv_cnt_exclude_isback
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,atc_same_day_order_cnt
    ,atc_within_3day_order_cnt
    ,atc_same_day_gmv
    ,atc_within_3day_gmv
    ,pc2_gmv
FROM dwm_table_${grass_region_without_quote};

--sql_divide_splitter--

CACHE TABLE base_table_${grass_region_without_quote} OPTIONS('storageLevel'='MEMORY_AND_DISK_SER') AS
SELECT
/*+ BROADCAST(exp_filter) */
    platform
    ,is_ads
    ,feature_detail
    ,source1_feature_detail
    ,source2_feature_detail
    ,scenario_tags
    ,source1_scenario_tags
    ,source2_scenario_tags
    ,filter_data.exp_group_id
    ,user_id
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,ppv_cnt_exclude_isback
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,atc_same_day_order_cnt
    ,atc_within_3day_order_cnt
    ,atc_same_day_gmv
    ,atc_within_3day_gmv
    ,pc2_gmv
FROM 
    explode_table_${grass_region_without_quote} filter_data
    INNER JOIN exp_filter_${grass_region_without_quote} exp_filter
    ON filter_data.exp_group_id = exp_filter.exp_group_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW raw_data_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,exp_group_id
    ,user_id
    ,scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    exp_group_id IS NOT NULL
    AND feature_detail IS NOT NULL
    AND size(scenario_tags) > 0
GROUP BY 1,2,3,4,5,6

UNION ALL
SELECT
    platform
    ,is_ads
    ,source1_feature_detail AS feature_detail
    ,exp_group_id
    ,user_id
    ,source1_scenario_tags AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    exp_group_id IS NOT NULL
    AND nvl(source1_feature_detail, '') != '' 
    AND source1_feature_detail != feature_detail
    AND size(source1_scenario_tags) > 0
GROUP BY 1,2,3,4,5,6

UNION ALL
SELECT
    platform
    ,is_ads
    ,source2_feature_detail AS feature_detail
    ,exp_group_id
    ,user_id
    ,source2_scenario_tags  AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    exp_group_id IS NOT NULL
    AND nvl(source2_feature_detail, '') != '' 
    AND source2_feature_detail != source1_feature_detail 
    AND source2_feature_detail != feature_detail
    AND size(source2_scenario_tags) > 0
GROUP BY 1,2,3,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_all_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,exp_group_id
    ,user_id
    ,'__ALL__' AS scenario_tag
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    base_table_${grass_region_without_quote} a
WHERE 
    exp_group_id IS NOT NULL
GROUP BY 1,2,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,exp_group_id
    ,user_id
    ,array_union(array_union( COALESCE(scenario_tags, array()), COALESCE(source1_scenario_tags, array())), COALESCE(source2_scenario_tags, array())) AS union_scenario_tags
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    base_table_${grass_region_without_quote}
GROUP BY  1,2,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW filter_tag_data_${grass_region_without_quote} AS
SELECT
    *,
    if(split(feature_detail,'-')[2] IS NOT NULL, split(feature_detail,'-')[2], split(feature_detail,'-')[1]) as target_type
FROM
    raw_data_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_table_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM filter_tag_data_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    -- Base dimension exp_group_id,feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7),

    --Base dimension exp_group_id,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,5,6,7), (1,3,5,6,7), 
    (1,4,5,6,7), (1,3,4,5,6,7)
)
UNION ALL
SELECT
    exp_group_id
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    dws_all_tag_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    -- Base dimension exp_group_id,feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
)
UNION ALL
SELECT
    exp_group_id
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    dws_tag_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(union_scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    --Base dimension exp_group_id,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
)
;

--sql_divide_splitter--

CREATE TEMPORARY VIEW metric_table_${grass_region_without_quote} AS
select 
    exp_group_id
    ,if(feature_detail IS NULL, '__ALL__', feature_detail) AS feature_detail
    ,if(is_ads IS NULL, '__ALL__', is_ads) AS is_ads
    ,if(platform IS NULL, '__ALL__', platform) AS platform
    ,if(target_type IS NULL, '__ALL__', target_type) AS target_type
    ,scenario_tag
    ,SUM(IF(imp_cnt > 0 and user_id > 0, 1, NULL)) AS imp_uu
    ,SUM(IF(click_cnt > 0 and user_id > 0, 1, NULL)) AS click_uu
    ,SUM(IF(ppv_cnt > 0 and user_id > 0, 1, NULL)) AS ppv_uu
    ,SUM(IF(cart_cnt > 0 and user_id > 0, 1, NULL)) AS cart_uu
    ,SUM(IF(order_cnt > 0 and user_id > 0, 1, NULL)) AS order_uu
    ,SUM(IF(item_imp_cnt > 0 and user_id > 0, 1, NULL)) AS item_imp_uu
    ,SUM(IF(item_click_cnt > 0 and user_id > 0, 1, NULL)) AS item_click_uu
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(IF(user_id > 0, imp_cnt, 0)) AS imp_login_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(IF(user_id > 0, click_cnt, 0)) AS click_login_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(IF(user_id > 0, ppv_cnt, 0)) AS ppv_login_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(IF(user_id > 0, cart_cnt, 0)) AS cart_login_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(IF(user_id > 0, order_cnt, 0)) AS order_login_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(IF(user_id > 0, ppv_cnt_exclude_isback, 0)) AS ppv_exclude_isback_login_cnt
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(IF(user_id > 0, item_imp_cnt, 0)) AS item_imp_login_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(IF(user_id > 0, item_click_cnt, 0)) AS item_click_login_cnt
    ,SUM(gmv) AS gmv
    ,SUM(IF(user_id > 0, gmv, 0)) AS gmv_login
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(IF(user_id > 0, atc_same_day_order_cnt, 0)) AS atc_same_day_order_login_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(IF(user_id > 0, atc_within_3day_order_cnt, 0)) AS atc_within_3day_order_login_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(IF(user_id > 0, atc_same_day_gmv, 0)) AS atc_same_day_gmv_login
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(IF(user_id > 0, atc_within_3day_gmv, 0)) AS atc_within_3day_gmv_login
    ,SUM(pc2_gmv) AS pc2_gmv
    ,SUM(IF(user_id > 0, pc2_gmv, 0)) AS pc2_gmv_login
FROM 
    cube_table_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6;

--sql_divide_splitter--

create temporary view benchmark_w_cube_ads_load_temp_${grass_region_without_quote} as
    select *
    ,sum(case when is_ads = 'true' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as ads_imp_cnt
    ,sum(case when is_ads = '__ALL__' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as all_imp_cnt
    from metric_table_${grass_region_without_quote};

--sql_divide_splitter--

create temporary view res_${grass_region_without_quote} as
   select *,
          case when is_ads = 'true' then 1
               when is_ads = 'false' then 0
               when is_ads = '__ALL__' then ads_imp_cnt/all_imp_cnt
          end as ads_load
   from benchmark_w_cube_ads_load_temp_${grass_region_without_quote};
 
--sql_divide_splitter--

INSERT OVERWRITE TABLE srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
PARTITION (grass_region = ${grass_region}, local_date = ${local_date}, exp_type = 'traffic')
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,scenario_tag
    ,target_type
    ,exp_group_id
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,item_imp_uu
    ,item_click_uu
    ,ads_load
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,atc_same_day_order_cnt
    ,atc_within_3day_order_cnt
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,atc_same_day_gmv AS atc_same_day_order_gmv
    ,atc_within_3day_gmv
    ,pc2_gmv

    ,imp_login_cnt
    ,item_imp_login_cnt
    ,click_login_cnt
    ,item_click_login_cnt
    ,ppv_login_cnt
    ,cart_login_cnt
    ,order_login_cnt
    ,ppv_exclude_isback_login_cnt
    ,gmv_login
    ,atc_same_day_order_login_cnt
    ,atc_within_3day_order_login_cnt
    ,atc_same_day_gmv_login
    ,atc_within_3day_gmv_login
    ,pc2_gmv_login

    ,NULL AS omni_imp_cnt
    ,NULL AS omni_click_cnt
    ,NULL AS squared_imp_cnt
    ,NULL AS squared_click_cnt
    ,NULL AS squared_order_cnt
    ,NULL AS squared_ppv_cnt_exclude_isback

FROM res_${grass_region_without_quote}

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
-- source_index: 2
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d_assign_log_join.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_exp_base_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d_assign_log_join.sql
-- deprecated: False
-- sha256: 4a68fdca5fdb41f8e2873374e1581bf26644edd9240aaa816b5c937d1b36e059
CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
select
    user_id
    ,collect_list(exp_group_id) as exp_group_ids
from
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
where
    grass_region in (${grass_region})
    and local_date = ${local_date}
    and is_assignment_log = 1
    and is_rcmd_whitelist = 1
group by user_id
;

--sql_divide_splitter--

CACHE TABLE base_table_${grass_region_without_quote}  OPTIONS('storageLevel'='DISK_ONLY') AS
SELECT
    coalesce(platform, 'NULL') AS platform
    ,user_id
    ,feature_detail
    ,source1_feature_detail
    ,source2_feature_detail
    ,FILTER(scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as scenario_tags
    ,FILTER(source1_scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as source1_scenario_tags
    ,FILTER(source2_scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as source2_scenario_tags
    ,cast(coalesce(is_ads, false) as string)   as is_ads
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(if(is_back, 0, ppv_cnt)) AS ppv_cnt_exclude_isback
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(if(imp_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', imp_cnt, 0)) AS item_imp_cnt
    ,SUM(if(click_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', click_cnt, 0)) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM srdi_mart.dwm_sr_data_warehouse_platform_user_item
WHERE grass_region = ${grass_region} AND local_date = ${local_date}
    AND operation IN ('impression', 'click', 'ppv', 'cart', 'order', 'omni_impression', 'omni_click')
    AND user_id > 0
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW raw_data_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,user_id
    ,FILTER(scenario_tags,
        value -> value like '%DA_%'
            or value in (
                'dpm module Global Search business line Search'
                ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                ,'dpm module Daily Discover business line Homepage'
                ,'dpm module Private Domin business line Rcmd'
            )
    ) as scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE
    feature_detail IS NOT NULL
    AND size(scenario_tags) > 0
GROUP BY 1,2,3,4,5

UNION ALL
SELECT
    platform
    ,is_ads
    ,source1_feature_detail AS feature_detail
    ,user_id
    ,FILTER(source1_scenario_tags,
         value -> value like '%DA_%'
             or value in (
                 'dpm module Global Search business line Search'
                 ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                 ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                 ,'dpm module Daily Discover business line Homepage'
                 ,'dpm module Private Domin business line Rcmd'
             )
    ) AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE
    nvl(source1_feature_detail, '') != ''
    AND source1_feature_detail != feature_detail
    AND size(source1_scenario_tags) > 0
GROUP BY 1,2,3,4,5

UNION ALL
SELECT
    platform
    ,is_ads
    ,source2_feature_detail AS feature_detail
    ,user_id
    ,FILTER(source2_scenario_tags,
         value -> value like '%DA_%'
             or value in (
                 'dpm module Global Search business line Search'
                 ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                 ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                 ,'dpm module Daily Discover business line Homepage'
                 ,'dpm module Private Domin business line Rcmd'
             )
    ) AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE
    nvl(source2_feature_detail, '') != ''
    AND source2_feature_detail != source1_feature_detail
    AND source2_feature_detail != feature_detail
    AND size(source2_scenario_tags) > 0
GROUP BY 1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_all_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,user_id
    ,'__ALL__' AS scenario_tag
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    base_table_${grass_region_without_quote} a
GROUP BY 1,2,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,user_id
    ,array_union(array_union( COALESCE(scenario_tags, array()), COALESCE(source1_scenario_tags, array())), COALESCE(source2_scenario_tags, array())) AS union_scenario_tags
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    base_table_${grass_region_without_quote}
GROUP BY  1,2,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW filter_tag_data_${grass_region_without_quote} AS
SELECT
    *,
    if(split(feature_detail,'-')[2] IS NOT NULL, split(feature_detail,'-')[2], split(feature_detail,'-')[1]) as target_type
FROM
    raw_data_${grass_region_without_quote}
WHERE
    size(scenario_tags) > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_table_${grass_region_without_quote} AS
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM filter_tag_data_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    -- Base dimension feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7),
    (1,2,4,5,6,7), (1,2,3,4,5,6,7),

    --Base dimension target_type,scenario_tag. Cube dimension is_ads,platform
    -- 感觉这里去掉(2->feature_detail)的话,数据因该重复了，因为target 不能阻止数据重复，需要再来三个union all 拼一下合理
    (1,5,6,7), (1,3,5,6,7),
    (1,4,5,6,7), (1,3,4,5,6,7)
)
UNION ALL
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    dws_all_tag_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    -- Base dimension feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7),
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
)
UNION ALL
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    dws_tag_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(union_scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    --Base dimension scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7),
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
);

--sql_divide_splitter--
CREATE TEMPORARY VIEW squared_data_${grass_region_without_quote} AS
SELECT
    *
    ,IF(imp_cnt > 0 and user_id > 0, 1, 0) AS imp_uu
    ,IF(click_cnt > 0 and user_id > 0, 1, 0) AS click_uu
    ,IF(ppv_cnt > 0 and user_id > 0, 1, 0) AS ppv_uu
    ,IF(cart_cnt > 0 and user_id > 0, 1, 0) AS cart_uu
    ,IF(order_cnt > 0 and user_id > 0, 1, 0) AS order_uu
    ,IF(item_imp_cnt > 0 and user_id > 0, 1, 0) AS item_imp_uu
    ,IF(item_click_cnt > 0 and user_id > 0, 1, 0) AS item_click_uu
    ,power(imp_cnt,2) AS squared_imp_cnt
    ,power(click_cnt,2) AS squared_click_cnt
    ,power(order_cnt,2) AS squared_order_cnt
    ,power(ppv_cnt_exclude_isback,2) AS squared_ppv_cnt_exclude_isback
FROM
    cube_table_${grass_region_without_quote};

--sql_divide_splitter--
create TEMPORARY VIEW map_data_${grass_region_without_quote} as
select
    feature_detail
     ,is_ads
     ,platform
     ,target_type
     ,user_id
     ,scenario_tag
     ,array(
        imp_uu
        ,click_uu
        ,ppv_uu
        ,cart_uu
        ,order_uu
        ,item_imp_uu
        ,item_click_uu
        ,imp_cnt
        ,click_cnt
        ,ppv_cnt
        ,cart_cnt
        ,order_cnt
        ,ppv_cnt_exclude_isback
        ,item_imp_cnt
        ,item_click_cnt
        ,gmv
        ,atc_same_day_order_cnt
        ,atc_within_3day_order_cnt
        ,atc_same_day_gmv
        ,atc_within_3day_gmv
        ,pc2_gmv
        ,omni_imp_cnt
        ,omni_click_cnt
        ,squared_imp_cnt
        ,squared_click_cnt
        ,squared_order_cnt
        ,squared_ppv_cnt_exclude_isback
      ) as metrics
from
    squared_data_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW explode_metric_table_${grass_region_without_quote} AS
SELECT
    if(feature_detail IS NULL, '__ALL__', feature_detail) AS feature_detail
    ,if(is_ads IS NULL, '__ALL__', is_ads) AS is_ads
    ,if(platform IS NULL, '__ALL__', platform) AS platform
    ,if(target_type IS NULL, '__ALL__', target_type) AS target_type
    ,scenario_tag
    ,exp_sum(b.exp_group_ids, a.metrics) as exp_metrics
FROM
    map_data_${grass_region_without_quote} a
    JOIN user_exp_${grass_region_without_quote} b
    ON a.user_id = b.user_id
GROUP BY
    1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW metric_table_${grass_region_without_quote} AS
SELECT
    feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,scenario_tag
    ,exp_info.exp_group_id as exp_group_id
    ,cast(exp_info.fields[0] as bigint) as imp_uu
    ,cast(exp_info.fields[1] as bigint) as click_uu
    ,cast(exp_info.fields[2] as bigint) as ppv_uu
    ,cast(exp_info.fields[3] as bigint) as cart_uu
    ,cast(exp_info.fields[4] as bigint) as order_uu
    ,cast(exp_info.fields[5] as bigint) as item_imp_uu
    ,cast(exp_info.fields[6] as bigint) as item_click_uu
    ,cast(exp_info.fields[7] as bigint) as imp_cnt
    ,cast(exp_info.fields[8] as bigint) as click_cnt
    ,cast(exp_info.fields[9] as bigint) as ppv_cnt
    ,cast(exp_info.fields[10] as bigint) as cart_cnt
    ,exp_info.fields[11] as order_cnt
    ,cast (exp_info.fields[12] as bigint) as ppv_cnt_exclude_isback
    ,cast (exp_info.fields[13] as bigint) as item_imp_cnt
    ,cast (exp_info.fields[14] as bigint) as item_click_cnt
    ,exp_info.fields[15] as gmv
    ,exp_info.fields[16] as atc_same_day_order_cnt
    ,exp_info.fields[17] as atc_within_3day_order_cnt
    ,exp_info.fields[18] as atc_same_day_gmv
    ,exp_info.fields[19] as atc_within_3day_gmv
    ,exp_info.fields[20] as pc2_gmv
    ,cast (exp_info.fields[21] as bigint) as omni_imp_cnt
    ,cast (exp_info.fields[22] as bigint) as omni_click_cnt
    ,exp_info.fields[23] as squared_imp_cnt
    ,exp_info.fields[24] as squared_click_cnt
    ,exp_info.fields[25] as squared_order_cnt
    ,exp_info.fields[26] as squared_ppv_cnt_exclude_isback
from
    explode_metric_table_${grass_region_without_quote}
    LATERAL VIEW EXPLODE(exp_metrics) as exp_info;

--sql_divide_splitter--

create temporary view benchmark_w_cube_ads_load_temp_${grass_region_without_quote} as
    select *
    ,sum(case when is_ads = 'true' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as ads_imp_cnt
    ,sum(case when is_ads = '__ALL__' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as all_imp_cnt
    from metric_table_${grass_region_without_quote};

--sql_divide_splitter--

create temporary view res_${grass_region_without_quote} as
   select *,
          case when is_ads = 'true' then 1
               when is_ads = 'false' then 0
               when is_ads = '__ALL__' then ads_imp_cnt/all_imp_cnt
          end as ads_load
   from benchmark_w_cube_ads_load_temp_${grass_region_without_quote};

--sql_divide_splitter--

INSERT OVERWRITE TABLE srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
PARTITION (grass_region = ${grass_region}, local_date = ${local_date}, exp_type = 'assign_log_join')
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,scenario_tag
    ,target_type
    ,exp_group_id
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,item_imp_uu
    ,item_click_uu
    ,ads_load
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,atc_same_day_order_cnt
    ,atc_within_3day_order_cnt
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,atc_same_day_gmv AS atc_same_day_order_gmv
    ,atc_within_3day_gmv
    ,pc2_gmv

    ,imp_cnt AS imp_login_cnt
    ,item_imp_cnt AS item_imp_login_cnt
    ,click_cnt AS click_login_cnt
    ,item_click_cnt AS item_click_login_cnt
    ,ppv_cnt AS ppv_login_cnt
    ,cart_cnt AS cart_login_cnt
    ,order_cnt AS order_login_cnt
    ,ppv_cnt_exclude_isback AS ppv_exclude_isback_login_cnt
    ,gmv AS gmv_login
    ,atc_same_day_order_cnt AS atc_same_day_order_login_cnt
    ,atc_within_3day_order_cnt AS atc_within_3day_order_login_cnt
    ,atc_same_day_gmv AS atc_same_day_gmv_login
    ,atc_within_3day_gmv AS atc_within_3day_gmv_login
    ,pc2_gmv AS pc2_gmv_login

    ,omni_imp_cnt
    ,omni_click_cnt
    ,squared_imp_cnt
    ,squared_click_cnt
    ,squared_order_cnt
    ,squared_ppv_cnt_exclude_isback

FROM res_${grass_region_without_quote}

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
-- source_index: 3
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d_dim_join.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_exp_base_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_base_metrics_1d_dim_join.sql
-- deprecated: False
-- sha256: 5c8b466e978ce801ee653c340316e1d589a1055d36d9a8d12165e3002e99d43f
CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
select
    user_id
    ,collect_list(exp_group_id) as exp_group_ids
from
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
where
    grass_region in (${grass_region})
    and local_date = ${local_date}
    and is_dim_join = 1
    and is_rcmd_whitelist = 1
group by user_id
;

--sql_divide_splitter--

CACHE TABLE base_table_${grass_region_without_quote}  OPTIONS('storageLevel'='DISK_ONLY') AS
SELECT
    coalesce(platform, 'NULL') AS platform
    ,user_id
    ,feature_detail
    ,source1_feature_detail
    ,source2_feature_detail
    ,FILTER(scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as scenario_tags
    ,FILTER(source1_scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as source1_scenario_tags
    ,FILTER(source2_scenario_tags, value -> value not like 'Page%' and value not like '%mapping group%') as source2_scenario_tags
    ,cast(coalesce(is_ads, false) as string)   as is_ads
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(if(is_back, 0, ppv_cnt)) AS ppv_cnt_exclude_isback
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(if(imp_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', imp_cnt, 0)) AS item_imp_cnt
    ,SUM(if(click_cnt>0 AND if(split(feature_detail, '-')[2] IS NOT NULL, split(feature_detail, '-')[2], split(feature_detail, '-')[1])='item', click_cnt, 0)) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM srdi_mart.dwm_sr_data_warehouse_platform_user_item
WHERE grass_region = ${grass_region} AND local_date = ${local_date}
    AND operation IN ('impression', 'click', 'ppv', 'cart', 'order', 'omni_impression', 'omni_click')
    AND user_id > 0
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW raw_data_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,user_id
    ,FILTER(scenario_tags,
        value -> value like '%DA_%'
            or value in (
                'dpm module Global Search business line Search'
                ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                ,'dpm module Daily Discover business line Homepage'
                ,'dpm module Private Domin business line Rcmd'
            )
    ) as scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    feature_detail IS NOT NULL
    AND size(scenario_tags) > 0
GROUP BY 1,2,3,4,5

UNION ALL
SELECT
    platform
    ,is_ads
    ,source1_feature_detail AS feature_detail
    ,user_id
    ,FILTER(source1_scenario_tags,
         value -> value like '%DA_%'
             or value in (
                 'dpm module Global Search business line Search'
                 ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                 ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                 ,'dpm module Daily Discover business line Homepage'
                 ,'dpm module Private Domin business line Rcmd'
             )
    ) AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    nvl(source1_feature_detail, '') != '' 
    AND source1_feature_detail != feature_detail
    AND size(source1_scenario_tags) > 0
GROUP BY 1,2,3,4,5

UNION ALL
SELECT
    platform
    ,is_ads
    ,source2_feature_detail AS feature_detail
    ,user_id
    ,FILTER(source2_scenario_tags,
         value -> value like '%DA_%'
             or value in (
                 'dpm module Global Search business line Search'
                 ,'dpm reporting object you may also like module User Scenario business line Rcmd'
                 ,'dpm reporting object post purchase module User Scenario business line Rcmd'
                 ,'dpm module Daily Discover business line Homepage'
                 ,'dpm module Private Domin business line Rcmd'
             )
    ) AS scenario_tags
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM base_table_${grass_region_without_quote}
WHERE 
    nvl(source2_feature_detail, '') != '' 
    AND source2_feature_detail != source1_feature_detail 
    AND source2_feature_detail != feature_detail
    AND size(source2_scenario_tags) > 0
GROUP BY 1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_all_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,user_id
    ,'__ALL__' AS scenario_tag
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    base_table_${grass_region_without_quote} a
GROUP BY 1,2,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_tag_${grass_region_without_quote} AS
SELECT
    platform
    ,is_ads
    ,'__ALL__' AS feature_detail
    ,user_id
    ,array_union(array_union( COALESCE(scenario_tags, array()), COALESCE(source1_scenario_tags, array())), COALESCE(source2_scenario_tags, array())) AS union_scenario_tags
    ,'__ALL__' AS target_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    base_table_${grass_region_without_quote}
GROUP BY  1,2,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW filter_tag_data_${grass_region_without_quote} AS
SELECT
    *,
    if(split(feature_detail,'-')[2] IS NOT NULL, split(feature_detail,'-')[2], split(feature_detail,'-')[1]) as target_type
FROM
    raw_data_${grass_region_without_quote}
WHERE
    size(scenario_tags) > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_table_${grass_region_without_quote} AS
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM filter_tag_data_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    -- Base dimension feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7),

    --Base dimension target_type,scenario_tag. Cube dimension is_ads,platform
    (1,5,6,7), (1,3,5,6,7), 
    (1,4,5,6,7), (1,3,4,5,6,7)
)
UNION ALL
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    dws_all_tag_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    -- Base dimension feature_detail,target_type,scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
)
UNION ALL
SELECT
    ''
    ,feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(omni_imp_cnt) AS omni_imp_cnt
    ,SUM(omni_click_cnt) AS omni_click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(ppv_cnt_exclude_isback) AS ppv_cnt_exclude_isback
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(atc_same_day_order_cnt) AS atc_same_day_order_cnt
    ,SUM(atc_within_3day_order_cnt) AS atc_within_3day_order_cnt
    ,SUM(atc_same_day_gmv) AS atc_same_day_gmv
    ,SUM(atc_within_3day_gmv) AS atc_within_3day_gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM 
    dws_tag_${grass_region_without_quote}
LATERAL VIEW OUTER EXPLODE(FILTER(union_scenario_tags, value -> value is not null)) AS scenario_tag
GROUP BY GROUPING SETS (
    --Base dimension scenario_tag. Cube dimension is_ads,platform
    (1,2,5,6,7), (1,2,3,5,6,7), 
    (1,2,4,5,6,7), (1,2,3,4,5,6,7)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW squared_data_${grass_region_without_quote} AS
SELECT
    *
    ,IF(imp_cnt > 0 and user_id > 0, 1, 0) AS imp_uu
    ,IF(click_cnt > 0 and user_id > 0, 1, 0) AS click_uu
    ,IF(ppv_cnt > 0 and user_id > 0, 1, 0) AS ppv_uu
    ,IF(cart_cnt > 0 and user_id > 0, 1, 0) AS cart_uu
    ,IF(order_cnt > 0 and user_id > 0, 1, 0) AS order_uu
    ,IF(item_imp_cnt > 0 and user_id > 0, 1, 0) AS item_imp_uu
    ,IF(item_click_cnt > 0 and user_id > 0, 1, 0) AS item_click_uu
    ,power(imp_cnt,2) AS squared_imp_cnt
    ,power(click_cnt,2) AS squared_click_cnt
    ,power(order_cnt,2) AS squared_order_cnt
    ,power(ppv_cnt_exclude_isback,2) AS squared_ppv_cnt_exclude_isback
FROM
    cube_table_${grass_region_without_quote};


--sql_divide_splitter--
create TEMPORARY VIEW map_data_${grass_region_without_quote} as
select
    feature_detail
     ,is_ads
     ,platform
     ,target_type
     ,user_id
     ,scenario_tag
     ,array(
        imp_uu
        ,click_uu
        ,ppv_uu
        ,cart_uu
        ,order_uu
        ,item_imp_uu
        ,item_click_uu
        ,imp_cnt
        ,click_cnt
        ,ppv_cnt
        ,cart_cnt
        ,order_cnt
        ,ppv_cnt_exclude_isback
        ,item_imp_cnt
        ,item_click_cnt
        ,gmv
        ,atc_same_day_order_cnt
        ,atc_within_3day_order_cnt
        ,atc_same_day_gmv
        ,atc_within_3day_gmv
        ,pc2_gmv
        ,omni_imp_cnt
        ,omni_click_cnt
        ,squared_imp_cnt
        ,squared_click_cnt
        ,squared_order_cnt
        ,squared_ppv_cnt_exclude_isback
      ) as metrics
from
    squared_data_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW explode_metric_table_${grass_region_without_quote} AS
SELECT
    if(feature_detail IS NULL, '__ALL__', feature_detail) AS feature_detail
    ,if(is_ads IS NULL, '__ALL__', is_ads) AS is_ads
    ,if(platform IS NULL, '__ALL__', platform) AS platform
    ,if(target_type IS NULL, '__ALL__', target_type) AS target_type
    ,scenario_tag
    ,exp_sum(b.exp_group_ids, a.metrics) as exp_metrics
FROM
    map_data_${grass_region_without_quote} a
    JOIN user_exp_${grass_region_without_quote} b
    ON a.user_id = b.user_id
GROUP BY
    1,2,3,4,5;

--sql_divide_splitter--

create TEMPORARY VIEW metric_table_${grass_region_without_quote} as
select
    feature_detail
    ,is_ads
    ,platform
    ,target_type
    ,scenario_tag
    ,exp_info.exp_group_id as exp_group_id
    ,cast(exp_info.fields[0] as bigint) as imp_uu
    ,cast(exp_info.fields[1] as bigint) as click_uu
    ,cast(exp_info.fields[2] as bigint) as ppv_uu
    ,cast(exp_info.fields[3] as bigint) as cart_uu
    ,cast(exp_info.fields[4] as bigint) as order_uu
    ,cast(exp_info.fields[5] as bigint) as item_imp_uu
    ,cast(exp_info.fields[6] as bigint) as item_click_uu
    ,cast(exp_info.fields[7] as bigint) as imp_cnt
    ,cast(exp_info.fields[8] as bigint) as click_cnt
    ,cast(exp_info.fields[9] as bigint) as ppv_cnt
    ,cast(exp_info.fields[10] as bigint) as cart_cnt
    ,exp_info.fields[11] as order_cnt
    ,cast (exp_info.fields[12] as bigint) as ppv_cnt_exclude_isback
    ,cast (exp_info.fields[13] as bigint) as item_imp_cnt
    ,cast (exp_info.fields[14] as bigint) as item_click_cnt
    ,exp_info.fields[15] as gmv
    ,exp_info.fields[16] as atc_same_day_order_cnt
    ,exp_info.fields[17] as atc_within_3day_order_cnt
    ,exp_info.fields[18] as atc_same_day_gmv
    ,exp_info.fields[19] as atc_within_3day_gmv
    ,exp_info.fields[20] as pc2_gmv
    ,cast (exp_info.fields[21] as bigint) as omni_imp_cnt
    ,cast (exp_info.fields[22] as bigint) as omni_click_cnt
    ,exp_info.fields[23] as squared_imp_cnt
    ,exp_info.fields[24] as squared_click_cnt
    ,exp_info.fields[25] as squared_order_cnt
    ,exp_info.fields[26] as squared_ppv_cnt_exclude_isback
from
    explode_metric_table_${grass_region_without_quote}
    LATERAL VIEW EXPLODE(exp_metrics) as exp_info;

--sql_divide_splitter--

create temporary view benchmark_w_cube_ads_load_temp_${grass_region_without_quote} as
    select *
    ,sum(case when is_ads = 'true' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as ads_imp_cnt
    ,sum(case when is_ads = '__ALL__' then imp_cnt else 0 end) over (partition by feature_detail, scenario_tag, exp_group_id, platform, target_type) as all_imp_cnt
    from metric_table_${grass_region_without_quote};

--sql_divide_splitter--

create temporary view res_${grass_region_without_quote} as
   select *,
          case when is_ads = 'true' then 1
               when is_ads = 'false' then 0
               when is_ads = '__ALL__' then ads_imp_cnt/all_imp_cnt
          end as ads_load
   from benchmark_w_cube_ads_load_temp_${grass_region_without_quote};

--sql_divide_splitter--

INSERT OVERWRITE TABLE srdi_mart.dws_sr_data_warehouse_platform_exp_base_metrics_1d
PARTITION (grass_region = ${grass_region}, local_date = ${local_date}, exp_type = 'dim_join')
SELECT
    platform
    ,is_ads
    ,feature_detail
    ,scenario_tag
    ,target_type
    ,exp_group_id
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,item_imp_uu
    ,item_click_uu
    ,ads_load
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,atc_same_day_order_cnt
    ,atc_within_3day_order_cnt
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,atc_same_day_gmv AS atc_same_day_order_gmv
    ,atc_within_3day_gmv
    ,pc2_gmv

    ,imp_cnt AS imp_login_cnt
    ,item_imp_cnt AS item_imp_login_cnt
    ,click_cnt AS click_login_cnt
    ,item_click_cnt AS item_click_login_cnt
    ,ppv_cnt AS ppv_login_cnt
    ,cart_cnt AS cart_login_cnt
    ,order_cnt AS order_login_cnt
    ,ppv_cnt_exclude_isback AS ppv_exclude_isback_login_cnt
    ,gmv AS gmv_login
    ,atc_same_day_order_cnt AS atc_same_day_order_login_cnt
    ,atc_within_3day_order_cnt AS atc_within_3day_order_login_cnt
    ,atc_same_day_gmv AS atc_same_day_gmv_login
    ,atc_within_3day_gmv AS atc_within_3day_gmv_login
    ,pc2_gmv AS pc2_gmv_login

    ,omni_imp_cnt
    ,omni_click_cnt
    ,squared_imp_cnt
    ,squared_click_cnt
    ,squared_order_cnt
    ,squared_ppv_cnt_exclude_isback

FROM res_${grass_region_without_quote}
