-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_srp_other_feature_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_srp_other_feature_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_srp_other_feature_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_srp_other_feature_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_srp_other_feature_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_srp_other_feature_metrics_1d.sql
-- deprecated: False
-- sha256: b32bcab8401df1403ab22adbd843f69c3136ba64a72777420270a18b5aed8ee6
INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_srp_other_feature_metrics_1d
PARTITION (
    grass_region = ${grass_region},
    local_date = ${local_date}
)
SELECT 
    user_id
    ,device_id
    ,CASE 
        WHEN operation IN ('impression', 'click') AND feature_detail IN ('global_search-ai_topic_card', 'search_in_pdp-ai_topic_card', 'search_prefill-ai_topic_card') THEN array('ai_topic_card_union')
        WHEN operation IN ('order') AND feature_detail IN ('ai_topic_landing-topic_result-add_to_cart_button', 'ai_topic_landing-topic_result-item')  then array('ai_topic_landing-topic_result-item_union','ai_topic_card_union')
        WHEN operation IN ('click') AND feature_detail IN ('ai_topic_landing-topic_result-add_to_cart_button', 'ai_topic_landing-topic_result-item','global_search-topic_result-add_to_cart_button', 'global_search-topic_result-item'
            ,'search_in_pdp-topic_result-add_to_cart_button', 'search_in_pdp-topic_result-item','search_prefill-topic_result-add_to_cart_button', 'search_prefill-topic_result-item')  then array('ai_topic_landing-topic_result-item_union')
        WHEN operation IN ('impression') AND feature_detail IN ('ai_topic_landing-topic_result-item', 'global_search-topic_result-item', 'search_in_pdp-topic_result-item', 'search_prefill-topic_result-item')  then array('ai_topic_landing-topic_result-item_union')
        WHEN operation IN ('impression', 'click') AND feature_detail IN ('video-video_product_impression','video-video_product_click', 'video-atc_click', 'video-buynow_click') AND content_type = 'item' AND sv_source_page IN ('iaa_srp_ai_card', 'iaa_srp_hashtag_card') AND position_current_page IN ('srp_ai_card_page', 'hashtag_mix_feed_page') THEN array('video-item_card')
        WHEN operation IN ('impression', 'click') AND feature_detail IN ('video-video_product_impression','video-video_product_click', 'video-atc_click', 'video-buynow_click') AND business_id = 1003 AND sv_source_page IN ('iaa_srp_ai_card', 'iaa_srp_hashtag_card') AND position_current_page IN ('srp_ai_card_page', 'hashtag_mix_feed_page') THEN array('video-video_card')
        WHEN operation IN ('order') AND (
            (source1_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card') AND content_type = 'item')
            OR (source2_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card') AND source1_content_type = 'item')
        ) THEN array('video-item_card')
        WHEN operation IN ('order') AND (
            (source1_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card') AND business_id = '1003')
            OR (source2_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card') AND source1_business_id = '1003')
        ) THEN array('video-video_card')
        ELSE array('unknow')
    END AS target_types
    ,keyword
    ,if(is_ads IS NOT NULL, cast(is_ads AS STRING), 'false') AS is_ads
    ,if(sort_type IS NOT NULL, cast(sort_type AS STRING), 'NA') AS sort_type
    ,sum( if (operation = 'impression', operation_cnt, null)) AS imp_cnt
    ,sum( if (operation = 'click', operation_cnt, null)) AS click_cnt
    ,NULL AS ppv_cnt
    ,NULL AS cart_cnt
    ,sum( if (operation = 'order', operation_cnt, null)) AS order_cnt
    ,sum( if (operation = 'order', place_order_gmv, null)) AS gmv
    ,sum( if (operation = 'order', pc2_gmv, null)) AS pc2_gmv
FROM
    srdi_mart.dwd_sr_data_warehouse_platform
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND operation IN ('click', 'impression', 'order')
    AND 
    (
        (feature_detail IN ('video-video_product_click', 'video-atc_click', 'video-buynow_click', 'video-video_product_impression')
        AND (content_type = 'item' OR business_id = 1003)
        )
        OR (
            feature_detail IN ('global_search-topic_result-add_to_cart_button', 'global_search-topic_result-item'
    ,'search_in_pdp-topic_result-add_to_cart_button', 'search_in_pdp-topic_result-item'
    ,'search_prefill-topic_result-add_to_cart_button', 'search_prefill-topic_result-item'
    ,'ai_topic_landing-topic_result-add_to_cart_button', 'ai_topic_landing-topic_result-item', 'global_search-ai_topic_card', 'search_in_pdp-ai_topic_card', 'search_prefill-ai_topic_card')
        )
        OR (
            source1_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card')
        )OR (
            source2_feature_detail IN ('global_search-ai_minifeed_card','search_in_pdp-ai_minifeed_card', 'search_prefill-ai_minifeed_card')
        )
    )
GROUP BY 1,2,3,4,5,6;
