-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_srp_performance_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_srp_performance_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_srp_performance_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_srp_performance_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_srp_performance_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_srp_performance_1d.sql
-- deprecated: False
-- sha256: 8c649c7b592c2f4d98985122b19a1d928485665bc63e31f1fe0975973c1f5a5a
-- DRD root page: https://confluence.shopee.io/pages/viewpage.action?pageId=2197481668
-- Relies on below google sheet mapping values
-- https://docs.google.com/spreadsheets/d/1XIFb9ZHedjcTiNaT6joYbznzhy4zZ8bbe1FZRZRjIks/edit?usp=sharing
CREATE TEMPORARY VIEW dim_search_feature_mapping_${grass_region_without_quote} AS
SELECT 
    page_type
    ,page_section
    ,target_type
    ,search_mid
    ,search_entrance
    ,split(IF(split(search_mid, '!')[0] = 'in', split(search_mid, '!')[1], NULL), ',') AS in_search_mid
    ,split(IF(split(search_entrance, '!')[0] = 'in', split(search_entrance, '!')[1], NULL), ',') AS in_search_entrance
    ,COLLECT_SET(operation) AS operation
    ,max(feature_tag) AS feature_tag
FROM 
    srdi_mart.dim_sr_data_warehouse_search_feature_tags_mapping_v2
WHERE
    feature_type = 'srp_performance'
    AND operation IN ('impression', 'click', 'order')
GROUP BY
    1,2,3,4,5,6,7;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_user_keyword_${grass_region_without_quote} AS
SELECT
    COALESCE(platform, 'NA') AS platform
    ,page_type
    ,COALESCE(page_section, 'null') AS page_section
    ,COALESCE(target_type, 'null') AS target_type
    ,IF(is_ads IS NOT NULL, is_ads, 'false') AS is_ads
    ,location_type
    ,COALESCE(IF(search_entrance = '', NULL, search_entrance), 'NA') AS search_entrance
    ,COALESCE(IF(search_mid = '', NULL, search_mid), 'NA') AS search_mid
    ,is_llm_deepthinking

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_srp_user_benchmark_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND user_id > 0
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_search_with_feature_${grass_region_without_quote} AS
SELECT 
    platform
    ,is_ads
    ,location_type
    ,t1.search_entrance
    ,CASE
        WHEN feature_tag = 'item' AND is_llm_deepthinking = TRUE THEN 'deepthinking_card'
        WHEN feature_tag = 'item' AND is_llm_deepthinking = FALSE THEN 'item'
        ELSE feature_tag
    END AS feature

    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'impression'),imp_cnt, null)) AS imp_cnt
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'click'),click_cnt, null)) AS click_cnt
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'click'),ppv_cnt, null)) AS ppv_cnt
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'click'),cart_cnt, null)) AS cart_cnt
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'order'),order_cnt, null))AS order_cnt
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'order'),gmv, null)) AS gmv
    ,SUM(if(ARRAY_CONTAINS(t2.operation, 'order'),pc2_gmv, null)) AS pc2_gmv
FROM 
    dws_user_keyword_${grass_region_without_quote} t1 
    INNER JOIN dim_search_feature_mapping_${grass_region_without_quote} t2
        ON t1.page_type = t2.page_type
        AND (
            t1.page_section  = t2.page_section
            OR t2.page_section = ''
        )
        AND (
            t1.target_type = t2.target_type
            OR t2.target_type = ''
        )AND (
            ARRAY_CONTAINS(t2.in_search_entrance, t1.search_entrance)
            OR t2.search_entrance = ''
        )
        AND (
            ARRAY_CONTAINS(t2.in_search_mid, t1.search_mid)
            OR t2.search_mid = ''
        )AND (
            (imp_cnt > 0 AND ARRAY_CONTAINS(t2.operation, 'impression'))
            OR ((click_cnt > 0 OR ppv_cnt > 0 OR cart_cnt > 0) AND ARRAY_CONTAINS(t2.operation, 'click'))
            OR ((order_cnt > 0 OR gmv > 0 OR pc2_gmv > 0) AND ARRAY_CONTAINS(t2.operation, 'order'))
        )
GROUP BY
    1,2,3,4,5;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_srp_performance_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
    platform
    ,search_entrance
    ,location_type
    ,is_ads
    ,feature
    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
FROM
    dws_search_with_feature_${grass_region_without_quote};
