-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_pb_search_replace_status_v2_nd
-- physical_table: srdi_mart.dws_sr_data_warehouse_pb_search_replace_status_v2_nd
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_pb_search_replace_status_v2_nd
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_pb_search_replace_status_v2_nd.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_pb_search_replace_status_v2_nd/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_pb_search_replace_status_v2_nd.sql
-- deprecated: False
-- sha256: 7db665aee6858bc4448542cdd839b8c8834c4fe85a923739e10199b862c4107c
CREATE TEMPORARY VIEW cheapest_list_${grass_region_without_quote} AS
select
     cspu_id
    ,item_id
    ,exp_tag
from(
    SELECT
         cspu_id
        ,item_id
    FROM srdi_mart.dim_sr_data_warehouse_pb_one_variation_model_analysis_hf
    WHERE grass_region = ${grass_region} AND local_date = ${local_date}
    group by
         cspu_id
        ,item_id
) a
lateral view explode(array('exp_1')) b as exp_tag
;
--sql_divide_splitter--

set max_partition_${grass_region_without_quote} = (
select -- DI取最大分区不支持5级分区，采用普通最值方法
    max(time_str) as max_time_str
from(
    SELECT
        concat(local_date,'_',if(local_hour<10,concat('0',local_hour),local_hour)) as  time_str
    FROM srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
    where grass_region in (${grass_region}) and local_date = ${local_date}
    group by local_date,local_hour -- daily 指标对齐tracker，采用local时间结算一天
) a
);
--sql_divide_splitter--

CREATE TEMPORARY VIEW max_explore_${grass_region_without_quote} AS
SELECT
     exp_tag
    ,cspu_id
    ,item_id
    ,version_date
    ,coalesce(imp_cnt_nd,0) as explore_imp_cnt
    ,coalesce(click_cnt_nd,0) as explore_click_cnt
FROM srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
where grass_region in (${grass_region}) and local_date = split(${max_partition_${grass_region_without_quote}},'_')[0]
and local_hour = cast(split(${max_partition_${grass_region_without_quote}},'_')[1] as int)
and traffic_tag ='explore'
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW max_cspu_${grass_region_without_quote} AS
SELECT
     exp_tag
    ,cspu_id
    ,item_id
    ,coalesce(imp_cnt_nd,0) as cspu_imp_cnt
    ,coalesce(click_cnt_nd,0) as cspu_click_cnt
FROM srdi_mart.dwd_sr_data_warehouse_pb_search_replace_realtime_metrics_hf
where grass_region in (${grass_region}) and local_date = split(${max_partition_${grass_region_without_quote}},'_')[0]
and local_hour = cast(split(${max_partition_${grass_region_without_quote}},'_')[1] as int)
and traffic_tag ='base'
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW current_version_status_${grass_region_without_quote} AS
SELECT
     exp_tag
    ,cspu_id
    ,item_id
    ,pruning_tag
    ,version_date
    ,exploration_status
FROM srdi_mart.dwd_sr_data_warehouse_pb_search_replace_status_hf
where grass_region in (${grass_region}) and regional_date = ${local_date}
and regional_hour = data_infra.max_pt('srdi_mart.dwd_sr_data_warehouse_pb_search_replace_status_hf', 'regional_hour', "grass_region=${grass_region} and regional_date = ${local_date}")
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW item_tag_status_${grass_region_without_quote} AS
select
    item_id
   ,exp_tag
   ,split(max(exploration_status_concat),'#')[1] as item_exploration_status
from (
    select
        *
        ,case
          when exploration_status='preferred'        then concat('3#', exploration_status)
          when exploration_status='non_preferred'    then concat('2#', exploration_status)
          when exploration_status='explore'          then concat('1#', exploration_status)
          when exploration_status='prepare'          then concat('0#', exploration_status)
         end as exploration_status_concat
     from current_version_status_${grass_region_without_quote}
) a
group by
    item_id
   ,exp_tag
;
--sql_divide_splitter--
INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_pb_search_replace_status_v2_nd partition(grass_region = ${grass_region}, local_date=${local_date})
SELECT
     d.exp_tag
    ,d.cspu_id
    ,d.item_id
    ,d.pruning_tag
    ,d.version_date
    ,d.exploration_status
    ,d.item_exploration_status
    ,e.explore_imp_cnt
    ,e.explore_click_cnt
    ,f.cspu_imp_cnt
    ,f.cspu_click_cnt
from(
    select
         a.exp_tag
        ,a.cspu_id
        ,a.item_id
        ,b.pruning_tag
        ,b.exploration_status
        ,b.version_date
        ,c.item_exploration_status
    FROM cheapest_list_${grass_region_without_quote} a
    left join current_version_status_${grass_region_without_quote} b on a.item_id=b.item_id and a.cspu_id=b.cspu_id and a.exp_tag=b.exp_tag
    left join item_tag_status_${grass_region_without_quote} c on a.item_id=c.item_id and a.exp_tag=c.exp_tag
) d
left join max_explore_${grass_region_without_quote} e on d.item_id=e.item_id and d.cspu_id=e.cspu_id and d.exp_tag=e.exp_tag and d.version_date=e.version_date
left join max_cspu_${grass_region_without_quote} f on d.item_id=f.item_id and d.cspu_id=f.cspu_id and f.exp_tag='control'
;
