-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd.sql
-- deprecated: False
-- sha256: 58c915c50ae3fd22885f0abaae943c42cfda0a6a5196afacb3e12054ae187caf
create temporary view llm_cluster_version_config_${grass_region_without_quote} as
select 'TW' as region, 'v2.4' as cluster_ver
union all select 'TH', 'v2.5'
union all select 'SG', 'v2.2'
union all select 'MY', 'v2.2'
union all select 'PH', 'v2.2'
union all select 'VN', 'v2.2'
union all select 'BR', 'v2.2'
union all select 'ID', 'v3.0'
union all select 'MX', 'v2.2' -- no actual data
union all select 'CL', 'v2.2' -- no actual data
union all select 'CO', 'v2.2' -- no actual data
union all select 'AR', 'v2.2' -- no actual data
union all select 'KH', 'v2.2' -- no actual data
union all select 'MM', 'v2.2' -- no actual data
union all select 'LA', 'v2.2' -- no actual data
;
--sql_divide_splitter--
create temporary view item_llm_cluster_${grass_region_without_quote} as
select
    item_id
    ,virtual_category_cluster_id as item_llm_cluster_id
from
    mpi_data_mart.adm_sr_item_llm_virtual_category_tags_reg_v2_df
where
    grass_region = ${grass_region}
    and cluster_version = (select cluster_ver from llm_cluster_version_config_${grass_region_without_quote} where region = ${grass_region})
    and grass_date = (
        select
            max(grass_date)
        from
            mpi_data_mart.adm_sr_item_llm_virtual_category_tags_reg_v2_df
        where
            grass_region = ${grass_region}
            and cluster_version = (select cluster_ver from llm_cluster_version_config_${grass_region_without_quote} where region = ${grass_region})
    )
    and item_id > 0
;

--sql_divide_splitter--
create temporary view user_item_raw_${grass_region_without_quote} as
select
    user_id
    ,case when is_ads = true then 'true' else 'false' end as is_ads
    ,if(split(feature_detail, '-')[2] is not null, split(feature_detail, '-')[2], split(feature_detail, '-')[1]) as target_type
    ,case
        when reporting_module = 'Daily Discover' and reporting_business_line = 'Homepage' then 'DD'
        when reporting_object = 'post purchase' and reporting_business_line = 'Rcmd' then 'PP'
        else 'Others'
    end as scene_type
    ,request_id
    ,item_id
    ,1 as dedup_imp_cnt
from
    srdi_mart.dwd_sr_data_warehouse_platform
where
    grass_region in (${grass_region})
    and local_date between date_sub(${local_date}, ${date_offset}) and ${local_date}
    and operation = 'impression'
    and user_id > 0
    and item_id > 0
    and (
        (reporting_module = 'Daily Discover' and reporting_business_line = 'Homepage')
        or (reporting_object = 'post purchase' and reporting_business_line = 'Rcmd')
    )
group by 1, 2, 3, 4, 5, 6;

--sql_divide_splitter--
create temporary view user_item_with_cluster_${grass_region_without_quote} as
select
    user_id
    ,is_ads
    ,target_type
    ,scene_type
    ,dedup_imp_cnt
    ,item_llm_cluster_id
from
    user_item_raw_${grass_region_without_quote} as t1
left join
    item_llm_cluster_${grass_region_without_quote} as t2
on t1.item_id = t2.item_id
;

--sql_divide_splitter--
create temporary view user_item_processed_${grass_region_without_quote} as
select
    user_id
    ,is_ads
    ,case
        when target_type in ('item', 'item_mix_feed_card') then 'item + mixfeed'
        when target_type = 'video' then 'video'
        when coalesce(target_type, '') = '' then null
        else 'others'
     end as card_type
    ,scene_type
    ,dedup_imp_cnt
    ,item_llm_cluster_id
from
    user_item_with_cluster_${grass_region_without_quote}
;

--sql_divide_splitter--
create temporary view user_cluster_agg_${grass_region_without_quote} as
select
    user_id
    ,is_ads
    ,item_llm_cluster_id
    ,'__ALL__' as card_type
    ,scene_type
    ,sum(dedup_imp_cnt) as dedup_imp_cnt
from
    user_item_processed_${grass_region_without_quote}
group by 1, 2, 3, 5

union all
select
    user_id
    ,is_ads
    ,item_llm_cluster_id
    ,card_type
    ,scene_type
    ,sum(dedup_imp_cnt) as dedup_imp_cnt
from
    user_item_processed_${grass_region_without_quote}
where
    card_type in ('item + mixfeed', 'video')
group by 1, 2, 3, 4, 5

union all
select
    user_id
    ,is_ads
    ,item_llm_cluster_id
    ,if(card_type in ('item + mixfeed', 'video'), 'item + mixfeed + video', 'others') as card_type
    ,scene_type
    ,sum(dedup_imp_cnt) as dedup_imp_cnt
from
    user_item_processed_${grass_region_without_quote}
group by 1, 2, 3, 4, 5

union all
select
    user_id
    ,is_ads
    ,case
        when item_llm_cluster_id is null then null
        when card_type = 'video' then concat('v#', item_llm_cluster_id)
        else item_llm_cluster_id
    end as item_llm_cluster_id
    ,'item + mixfeed + video - no dedup' as card_type
    ,scene_type
    ,sum(dedup_imp_cnt) as dedup_imp_cnt
from
    user_item_processed_${grass_region_without_quote}
where
    card_type in ('item + mixfeed', 'video')
    and scene_type in ('DD', 'PP')
group by 1, 2, 3, 4, 5
;

--sql_divide_splitter--
create temporary view cubed_data_${grass_region_without_quote} as
select
    user_id
    ,coalesce(is_ads, '__ALL__') as is_ads
    ,card_type
    ,scene_type
    ,sum(dedup_imp_cnt) as dedup_imp_cnt
    ,count(distinct case when dedup_imp_cnt > 0 then item_llm_cluster_id else null end) as imp_llm_cat_count_per_uu
from
    user_cluster_agg_${grass_region_without_quote}
group by
    user_id
    ,cube(is_ads)
    ,card_type
    ,scene_type
;

--sql_divide_splitter--
insert overwrite table ${schema}.dws_sr_data_warehouse_platform_scenario_card_level_diversity_dedup_nd
partition (grass_region = ${grass_region}, local_date = ${local_date}, num_day)
select
    scene_type
    ,card_type
    ,is_ads

    ,sum(dedup_imp_cnt) as dedup_imp_cnt
    ,sum(if(dedup_imp_cnt > 0, 1, 0)) as imp_uu
    ,sum(imp_llm_cat_count_per_uu) as imp_llm_cat_cnt

    ,${date_offset} + 1 as num_day
from
    cubed_data_${grass_region_without_quote}
group by scene_type, card_type, is_ads;
