-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_cspu_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_cspu_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_cspu_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_cspu_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_cspu_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_cspu_1d.sql
-- deprecated: False
-- sha256: d8223fa320ba149e591d20efbeb0092c32f54846a862c099de4e3623cb143151
CREATE TEMPORARY VIEW all_cspu_model_${grass_region_without_quote} AS
SELECT
     cspu_id
    ,model_id
    ,item_id
from srdi_mart.dim_sr_data_warehouse_pb_all_cspu_link_analysis_hf
where grass_region in (${grass_region})  and local_date = ${local_date}
group by
     cspu_id
    ,model_id
    ,item_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW civ_data_${grass_region_without_quote} as
SELECT
     item_id
    ,sum(if(operation = 'impression' ,operation_cnt,0))  AS imp_cnt
    ,sum(if(operation = 'click' ,operation_cnt,0)) AS click_cnt
FROM srdi_mart.dwd_sr_data_warehouse_platform
WHERE grass_region IN (${grass_region}) AND local_date = ${local_date}  and operation in ('impression','click')
group by
     item_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW order_data_${grass_region_without_quote} as
SELECT
     model_id
    ,sum(if(operation = 'order',operation_cnt,0)) AS order_cnt
FROM srdi_mart.dwd_sr_data_warehouse_platform
WHERE grass_region IN (${grass_region}) AND local_date = ${local_date}  and operation in ('order')
group by
     model_id
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_platform_cspu_1d partition (grass_region = ${grass_region},local_date = ${local_date})
select
     cspu_id
    ,sum(imp_cnt)   AS imp_cnt
    ,sum(click_cnt) AS click_cnt
    ,sum(order_cnt) as order_cnt
from(
    select
         cspu_id
        ,sum(order_cnt) as order_cnt
        ,0 AS imp_cnt
        ,0 AS click_cnt
    from all_cspu_model_${grass_region_without_quote} a
    left join order_data_${grass_region_without_quote} b on a.model_id = b.model_id
    group by cspu_id
    union all
    select
         cspu_id
        ,0 as order_cnt
        ,sum(imp_cnt)  AS imp_cnt
        ,sum(click_cnt) AS click_cnt
    from (
        select
             cspu_id
            ,item_id
        from all_cspu_model_${grass_region_without_quote}
        group by cspu_id,item_id
    ) a
    left join civ_data_${grass_region_without_quote} b on a.item_id = b.item_id
    group by
         cspu_id
) c
group by cspu_id
