-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d.sql
-- deprecated: False
-- sha256: 31d69e10971f3571234a649691c2bed4996b9c6d65f364b29a3a8a818c913f55
CREATE TEMPORARY VIEW exchange_rate_${grass_region_without_quote} AS
select exchange_rate
from mp_order.dim_exchange_rate__reg_s0_live
where grass_region in (${grass_region})
  and grass_date = ${regional_date}
;
--sql_divide_splitter--
CREATE TEMPORARY VIEW ecpm_label_step1_${grass_region_without_quote} AS
select
    item_id,
    case when entrance = 1 then 'Search'
         when entrance = 3 then 'Daily Discover'
         when entrance = 4 then 'You May Also Like'
        end as mapping_general,
    avg(ecpm)/max(exchange_rate) as ecpm_usd
from srdi_mart.dwd_sr_data_warehouse_roi2_ads_search_log
left join exchange_rate_${grass_region_without_quote}
on 1=1
where grass_region IN (${grass_region})
  and regional_date = ${regional_date}
  and roi_item_type in ('SIMPLE_ROI2','TARGET_ROI2')
  and entrance in (1,3,4)
  and ecpm > 0
group by 1,2
;
--sql_divide_splitter--
CREATE TEMPORARY VIEW ecpm_label_step2_${grass_region_without_quote} AS
select mapping_general
     ,ecpm_pct_arr[0] as ecpm_pct_10
     ,ecpm_pct_arr[1] as ecpm_pct_20
     ,ecpm_pct_arr[2] as ecpm_pct_30
     ,ecpm_pct_arr[3] as ecpm_pct_40
     ,ecpm_pct_arr[4] as ecpm_pct_50
     ,ecpm_pct_arr[5] as ecpm_pct_60
     ,ecpm_pct_arr[6] as ecpm_pct_70
     ,ecpm_pct_arr[7] as ecpm_pct_80
     ,ecpm_pct_arr[8] as ecpm_pct_90
from (
      SELECT mapping_general
           , APPROX_PERCENTILE(ecpm_usd, ARRAY(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)) as ecpm_pct_arr
      FROM ecpm_label_step1_${grass_region_without_quote}
      GROUP BY 1
)x
;
--sql_divide_splitter--
CREATE TEMPORARY VIEW ecpm_label_${grass_region_without_quote} AS
select item_id
 ,map_from_entries(
    collect_list(
            struct(mapping_general,array(ecpm_tier_tag,ecpm_usd))
    )
  ) as ecpm_tag
from (
      SELECT item_id
           , a.mapping_general
           , ecpm_usd
           , CASE
                 WHEN ecpm_usd < ecpm_pct_10 THEN 0.1
                 WHEN ecpm_usd < ecpm_pct_20 THEN 0.2
                 WHEN ecpm_usd < ecpm_pct_30 THEN 0.3
                 WHEN ecpm_usd < ecpm_pct_40 THEN 0.4
                 WHEN ecpm_usd < ecpm_pct_50 THEN 0.5
                 WHEN ecpm_usd < ecpm_pct_60 THEN 0.6
                 WHEN ecpm_usd < ecpm_pct_70 THEN 0.7
                 WHEN ecpm_usd < ecpm_pct_80 THEN 0.8
                 WHEN ecpm_usd < ecpm_pct_90 THEN 0.9
                 WHEN ecpm_usd >= ecpm_pct_90 THEN 1.0
        END AS ecpm_tier_tag
      FROM ecpm_label_step1_${grass_region_without_quote} a
      LEFT JOIN ecpm_label_step2_${grass_region_without_quote} b
      ON a.mapping_general = b.mapping_general
)x
group by 1
;
--sql_divide_splitter--
insert overwrite table ${schema}.dws_sr_data_warehouse_tc_pb_item_level_ecpm_1d
partition (grass_region = ${grass_region}, regional_date = ${regional_date})
select item_id
,ecpm_tag
from ecpm_label_${grass_region_without_quote}
;
