-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d.sql
-- deprecated: False
-- sha256: 3210a1dc8401e6ddb22732b3af3cfbc6974c097b002726a6b2d1889f41a72599
CREATE TEMPORARY VIEW selected_user_exps_${grass_region_without_quote} AS
SELECT 
    user_id
    ,exp_group_id
FROM 
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE 
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND is_assignment_log = 1
    AND is_search_whitelist = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_user_benchmark_${grass_region_without_quote} AS
SELECT
    COALESCE(cast(is_ads as string), 'false') as is_ads
    ,COALESCE(platform, 'unknown') as platform
    ,user_id
    ,array_intersect(dedup_scenario_tags,
        array(
            'dpm module Global Search business line Search', 'DA_Daily Discover','DA_You May Also Like',
            'DA_Cart_Unify','DA_Buy Again (Me Page)','DA_Cart Recommendation','DA_odp_ymal-order_detail',
            'DA_Order Successful Recommendation','DA_mpp_ymal-order_list','DA_Me YMAL','DA_Shop YMAL','DA_Shop_Unify',
            'dpm_HP_DD + dpm_Global Search', 'dpm_PDP_YMAL + dpm_Global Search', 'dpm_PP_YMAL + dpm_Global Search'
        )
    ) AS dedup_scenario_tags

    ,SUM(imp_cnt) AS imp_cnt 
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
    ,SUM(if(target_type = 'item',imp_cnt, NULL)) AS item_imp_cnt
    ,SUM(if(target_type = 'item',click_cnt, NULL)) AS item_click_cnt
FROM 
    srdi_mart.dws_sr_data_warehouse_platform_user_item_keyword_benchmark_1d
WHERE 
    grass_region IN (${grass_region}) 
    AND local_date = ${local_date}
    AND (
        size(array_intersect(dedup_scenario_tags,
            array(
                'dpm module Global Search business line Search', 'DA_Daily Discover','DA_You May Also Like',
                'DA_Cart_Unify','DA_Buy Again (Me Page)','DA_Cart Recommendation','DA_odp_ymal-order_detail',
                'DA_Order Successful Recommendation','DA_mpp_ymal-order_list','DA_Me YMAL','DA_Shop YMAL','DA_Shop_Unify',
                'dpm_HP_DD + dpm_Global Search', 'dpm_PDP_YMAL + dpm_Global Search', 'dpm_PP_YMAL + dpm_Global Search'
            )
        )) > 0
    )
GROUP BY 
    1,2,3,4
UNION ALL 
SELECT
    COALESCE(cast(is_ads as string), 'false') as is_ads
    ,COALESCE(platform, 'unknown') as platform
    ,user_id
    ,ARRAY('__ALL__') AS dedup_scenario_tags

    ,SUM(imp_cnt) AS imp_cnt 
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
    ,SUM(if(target_type = 'item',imp_cnt, NULL)) AS item_imp_cnt
    ,SUM(if(target_type = 'item',click_cnt, NULL)) AS item_click_cnt
FROM 
    srdi_mart.dws_sr_data_warehouse_platform_user_item_keyword_benchmark_1d
WHERE 
    grass_region IN (${grass_region}) 
    AND local_date = ${local_date}
    AND is_direct = true
GROUP BY 
    1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW tracking_${grass_region_without_quote} AS
SELECT  
    is_ads
    ,platform
    ,user_id
    ,case
        when scenario_tag = 'dpm module Global Search business line Search' then 'Search'
        else scenario_tag 
    end as scenario_tag
    ,SUM(imp_cnt) AS imp_cnt 
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
FROM 
    dws_user_benchmark_${grass_region_without_quote}
    LATERAL VIEW EXPLODE (dedup_scenario_tags) AS scenario_tag
GROUP BY 
    1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_table_${grass_region_without_quote} AS
SELECT
    COALESCE(is_ads, '__ALL__') as is_ads
    ,COALESCE(platform, '__ALL__') AS platform
    ,user_id
    ,scenario_tag

    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
    ,IF(sum(order_cnt) = 0, 0, sum(gmv) / sum(order_cnt)) as abs
FROM 
    tracking_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    -- Base dimension user_id, scenario_tag. Cube dimension is_ads,platform
    (is_ads, platform,user_id, scenario_tag), (is_ads,user_id, scenario_tag), 
    (platform, user_id, scenario_tag), (user_id, scenario_tag)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW outlier_agg_${grass_region_without_quote} AS
SELECT
    case
        when feature_group = 'all' then '__ALL__'
        when feature_group = 'Cart Unify' then 'DA_Cart_Unify'
        when feature_group = 'Order Detail Page YMAL' then 'DA_odp_ymal-order_detail'
        when feature_group = 'My Purchase Page YMAL' then 'DA_mpp_ymal-order_list'
        when feature_group = 'Daily Discover' then 'DA_Daily Discover'
        when feature_group = 'You May Also Like' then 'DA_You May Also Like'
        when feature_group = 'Buy Again (Me Page)' then 'DA_Buy Again (Me Page)'
        when feature_group = 'Cart Recommendation' then 'DA_Cart Recommendation'
        when feature_group = 'Order Successful Recommendation' then 'DA_Order Successful Recommendation'
        when feature_group = 'Me YMAL' then 'DA_Me YMAL'
        when feature_group = 'Shop YMAL' then 'DA_Shop YMAL'
        when feature_group = 'Shop Unify' then 'DA_Shop_Unify'
        else feature_group
    end as feature_group
    ,IF(is_ads = 'all', '__ALL__', is_ads) AS is_ads
    ,max(if(percentile=0.995, val, 0)) as abs_995
FROM 
    srdi_mart.ads_rcmd_platform_scenario_level_outlier_di
WHERE 
    grass_date = ${local_date}
    and grass_region IN (${grass_region}) 
    and outlier_type = 'abs'
GROUP BY 
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_table_with_abs_${grass_region_without_quote} AS
SELECT
    a.is_ads
    ,platform
    ,user_id
    ,scenario_tag
    ,abs_995

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,item_imp_cnt
    ,item_click_cnt
    ,gmv
    ,pc2_gmv
    ,case when coalesce(abs,0) <= abs_995 then 1 else 0 end as below_995
FROM 
    cube_table_${grass_region_without_quote} a
    LEFT JOIN outlier_agg_${grass_region_without_quote} b
    ON a.scenario_tag = b.feature_group
    AND a.is_ads = b.is_ads
    AND a.platform = '__ALL__';

--sql_divide_splitter--

CREATE TEMPORARY VIEW res_data_${grass_region_without_quote} AS
SELECT 
    b.exp_group_id AS exp_group_id
    ,is_ads
    ,platform
    ,scenario_tag
    ,SUM(IF(imp_cnt > 0 and b.user_id > 0, 1, NULL)) AS imp_uu
    ,SUM(IF(click_cnt > 0 and b.user_id > 0, 1, NULL)) AS click_uu
    ,SUM(IF(ppv_cnt > 0 and b.user_id > 0, 1, NULL)) AS ppv_uu
    ,SUM(IF(cart_cnt > 0 and b.user_id > 0, 1, NULL)) AS cart_uu
    ,SUM(IF(order_cnt > 0 and b.user_id > 0, 1, NULL)) AS order_uu
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(ppv_cnt) AS ppv_cnt
    ,SUM(cart_cnt) AS cart_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(item_imp_cnt) AS item_imp_cnt
    ,SUM(item_click_cnt) AS item_click_cnt
    ,SUM(gmv) AS gmv

    ,COUNT(DISTINCT IF(below_995 = 1 AND imp_cnt >0, b.user_id, NULL)) AS imp_uu_995
    ,sum(IF(below_995 = 1, imp_cnt, 0)) AS imp_cnt_995
    ,sum(IF(below_995 = 1, order_cnt, 0)) AS order_cnt_995
    ,sum(IF(below_995 = 1, gmv, 0)) AS gmv_995
    ,sum(IF(below_995 = 1, pc2_gmv, 0)) AS pc2_gmv_995
    ,max(abs_995) as abs_995
FROM 
    cube_table_with_abs_${grass_region_without_quote} a
    INNER JOIN selected_user_exps_${grass_region_without_quote} b
    ON a.user_id = b.user_id
GROUP BY
    1,2,3,4;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_exp_level_other_scenario_metrics_1d
PARTITION (
    grass_region = ${grass_region},
    local_date = ${local_date})
SELECT  
/*+ REPARTITION(100) */
    scenario_tag
    ,platform
    ,is_ads
    ,exp_group_id
    ,item_imp_cnt
    ,item_click_cnt
    ,ppv_cnt AS ppv_cnt_exclude_isback
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu AS atc_uu
    ,order_uu

    ,imp_uu_995
    ,imp_cnt_995
    ,order_cnt_995
    ,gmv_995
    ,pc2_gmv_995
    ,imp_cnt
    ,click_cnt
FROM    
    res_data_${grass_region_without_quote};
