-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d.sql
-- deprecated: False
-- sha256: 72556e4e874edc3190fde9f510215f299bdc05fcda5e031b769a337995b1d849
-- DRD: https://confluence.shopee.io/pages/viewpage.action?pageId=2751255278
CREATE TEMPORARY VIEW user_exp_mapping_${grass_region_without_quote} AS 
SELECT
    user_id
    ,experiment_id
    ,exp_group_id
FROM
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND is_assignment_log = 1
    AND is_search_whitelist = 1;

--sql_divide_splitter--

CACHE TABLE exp_group_uu_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,COUNT(1) AS group_uu
FROM
    user_exp_mapping_${grass_region_without_quote}
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_search_volume_deduplicated_${grass_region_without_quote} AS
SELECT DISTINCT
    user_id
    ,device_id
    ,keyword
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND page_section IS NULL
    AND operation = 'view';

--sql_divide_splitter--

CACHE TABLE search_volume_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,COUNT(1) AS search_volume
FROM
    user_exp_mapping_${grass_region_without_quote} a
JOIN
    dwd_search_volume_deduplicated_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW view_user_deduplicated_${grass_region_without_quote} AS
SELECT DISTINCT
    user_id
FROM
    dwd_search_volume_deduplicated_${grass_region_without_quote};

--sql_divide_splitter--

CACHE TABLE search_uu_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,COUNT(1) AS search_uu
FROM
    user_exp_mapping_${grass_region_without_quote} a
JOIN
    view_user_deduplicated_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_raw_data_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,COALESCE(layout_variant, '') AS layout_variant
    ,COALESCE(app_version, '') AS app_version
    ,COALESCE(dre_version, '') AS dre_version
    ,COALESCE(original_operation, '') AS operation
    ,COALESCE(search_session_id, '') AS search_session_id
    ,is_cache
    ,TRANSFORM(stages_duration, x -> FROM_JSON(x, 'STRUCT<parent_stage:STRING,stage:STRING,category_level:INT,duration:BIGINT,client_type:STRING>')) AS stages
    ,total_duration
    ,server_cost
    ,request_pack_size
    ,response_pack_size
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND page_type IN ('global_search', 'search_prefill', 'search_in_pdp')
    AND user_id > 0
    AND platform_implementation = 'dre'
    AND REGEXP_LIKE(app_version, '^[0-9][0-9]?\.[0-9][0-9]?\.[0-9][0-9]?$')
    AND REGEXP_LIKE(dre_version, '^[0-9][0-9]?\.[0-9][0-9]?\.[0-9][0-9]?$')
    AND operation = 'click'
    AND original_operation IN ('action_first_page_performance', 'action_pagination_performance', 'action_filter_performance')
    AND platform IN ('ios_app', 'android_app')
    AND SIZE(stages_duration) > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_raw_data_version_filtered_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,is_cache
    ,stages
    ,total_duration
    ,server_cost
    ,request_pack_size
    ,response_pack_size
FROM 
    dwd_raw_data_${grass_region_without_quote}
WHERE (
        CAST(SPLIT(app_version, '\\.')[0] AS INT) > 3
        OR (CAST(SPLIT(app_version, '\\.')[0] AS INT) = 3 AND CAST(SPLIT(app_version, '\\.')[1] AS INT) > 27)
        OR (CAST(SPLIT(app_version, '\\.')[0] AS INT) = 3 AND CAST(SPLIT(app_version, '\\.')[1] AS INT) = 27 AND CAST(SPLIT(app_version, '\\.')[2] AS INT) >= 0)
    ) AND (
        CAST(SPLIT(dre_version, '\\.')[0] AS INT) > 1
        OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 50)
        OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 50 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 2)
    );

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_raw_data_explode_stages_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,is_cache
    ,stage_detail.stage AS stage
    ,COALESCE(stage_detail.category_level, 'NULL') AS category_level
    ,COALESCE(stage_detail.parent_stage, 'NULL') AS parent_stage
    ,COALESCE(stage_detail.client_type, 'NULL') AS client_type
    ,stage_detail.duration AS duration
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote}
LATERAL VIEW
    EXPLODE(stages) AS stage_detail
WHERE
    stage_detail.duration IS NOT NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW stage_duration_user_grouped_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,dre_version
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,client_type
    ,duration
    ,COUNT(1) AS freq_count
FROM
    dwd_raw_data_explode_stages_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW stage_duration_exp_freq_count_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,'__ALL__' AS layout_variant
    ,'__ALL__' AS app_version
    ,'__ALL__' AS dre_version
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,duration
    ,SUM(freq_count) AS freq_count
FROM
    stage_duration_user_grouped_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    -- category_level & parent_stage live on dre_version >= 1.57.4 & app-version >= 3.27.0
    CAST(SPLIT(dre_version, '\\.')[0] AS INT) > 1
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 57)
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 57 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 4)
GROUP BY
    experiment_id
    ,exp_group_id
    ,platform
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,duration;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_stage_duration_metrics_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,PERCENTILE(duration, ARRAY(0.8, 0.9, 0.95, 0.99), freq_count) AS duration_pcts
FROM
    stage_duration_exp_freq_count_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7,8,9,10;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_runtime_metrics_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,'others' AS stage
    ,NULL AS client_type
    ,CASE
        WHEN operation = 'action_first_page_performance' THEN SUM(IF(stage = 'fsp', duration, 0)) - SUM(IF(category_level = 1, duration, 0))
        WHEN operation = 'action_pagination_performance' THEN SUM(IF(stage = 'load_more', duration, 0))
            - SUM(IF(stage IN ('prepare_render_data', 'prepare_search_params', 'fetch_items', 'parse_response_data'), duration, 0))
        WHEN operation = 'action_filter_performance' THEN SUM(IF(stage = 'filter_refresh', duration, 0)) - SUM(IF(category_level = 1, duration, 0))
    END AS duration
FROM
    dwd_raw_data_explode_stages_${grass_region_without_quote}
WHERE -- Restrict dre_version >= 1.57.4 AND dre_version < 1.67.0
    (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 57 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) < 67)
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 57 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 4)
GROUP BY
    1,2,3,4,5,6,7,8,9
UNION ALL
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,'js_runtime' AS stage
    ,NULL AS client_type
    ,CASE
        WHEN operation = 'action_first_page_performance' THEN SUM(IF(category_level = 1, duration, 0)) - SUM(IF(stage = 'server_cost', duration, 0))
        WHEN operation = 'action_pagination_performance' THEN
            SUM(IF(stage IN ('prepare_render_data', 'prepare_search_params', 'fetch_items', 'parse_response_data'), duration, 0)) - SUM(IF(stage = 'server_cost', duration, 0))
        WHEN operation = 'action_filter_performance' THEN SUM(IF(category_level = 1, duration, 0)) - SUM(IF(stage = 'server_cost', duration, 0))
    END AS duration
FROM
    dwd_raw_data_explode_stages_${grass_region_without_quote}
WHERE -- Restrict dre_version >= 1.57.4 AND dre_version < 1.67.0
    (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 57 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) < 67)
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 57 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 4)
GROUP BY
    1,2,3,4,5,6,7,8,9
UNION ALL
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,'others' AS stage
    ,'' AS client_type
    ,SUM(total_duration - AGGREGATE(FILTER(stages, x -> x.client_type IN ('js', 'server')), CAST(0 AS BIGINT), (acc, stage_detail) -> acc + COALESCE(stage_detail.duration, 0))) AS duration
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote}
WHERE -- Restrict dre_version >= 1.67.0
    CAST(SPLIT(dre_version, '\\.')[0] AS INT) > 1
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 67)
    OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 67 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 0)
GROUP BY
    1,2,3,4,5,6,7,8,9
UNION ALL
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,search_session_id
    ,'js_runtime' AS stage
    ,client_type
    ,SUM(duration) AS duration
FROM
    dwd_raw_data_explode_stages_${grass_region_without_quote}
WHERE -- Restrict dre_version >= 1.67.0
    client_type = 'js'
    AND (
        CAST(SPLIT(dre_version, '\\.')[0] AS INT) > 1
        OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) > 67)
        OR (CAST(SPLIT(dre_version, '\\.')[0] AS INT) = 1 AND CAST(SPLIT(dre_version, '\\.')[1] AS INT) = 67 AND CAST(SPLIT(dre_version, '\\.')[2] AS INT) >= 0)
    )
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW runtime_metrics_freq_count_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,'__ALL__' AS layout_variant
    ,'__ALL__' AS app_version
    ,'__ALL__' AS dre_version
    ,operation
    ,stage
    ,NULL AS client_type
    ,duration
    ,COUNT(1) AS freq_count
FROM
    dwd_runtime_metrics_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3,4,5,6,7,8,9,10;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_runtime_metrics_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,stage
    ,client_type
    ,PERCENTILE(duration, ARRAY(0.8, 0.9, 0.95, 0.99), freq_count) AS duration_pcts
FROM
    runtime_metrics_freq_count_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7,8,9;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_all_stage_duration_merge_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,NULL AS client_type
    ,duration_pcts[0] AS duration_p80
    ,duration_pcts[1] AS duration_p90
    ,duration_pcts[2] AS duration_p95
    ,duration_pcts[3] AS duration_p99
FROM
    dws_stage_duration_metrics_${grass_region_without_quote}
UNION ALL
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,stage
    ,NULL AS category_level
    ,NULL AS parent_stage
    ,client_type
    ,duration_pcts[0] AS duration_p80
    ,duration_pcts[1] AS duration_p90
    ,duration_pcts[2] AS duration_p95
    ,duration_pcts[3] AS duration_p99
FROM
    dws_runtime_metrics_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW total_duration_and_be_stats_all_op_search_session_grouped_${grass_region_without_quote} AS
SELECT
-- Apply group by search_session_id and sum metrics
-- Before approx pct for operation = __ALL__ for these metrics
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,search_session_id
    ,SUM(CASE
        WHEN operation IN ('action_first_page_performance', 'action_filter_performance') THEN total_duration
        WHEN operation = 'action_pagination_performance'
            THEN AGGREGATE(FILTER(stages, x -> x.stage = 'load_more_item_exposure'), CAST(0 AS BIGINT), (acc, stage_detail) -> acc + GREATEST(stage_detail.duration, 0))
        ELSE 0
    END) AS total_duration
    ,SUM(server_cost) AS server_cost
    ,SUM(request_pack_size) AS request_pack_size
    ,SUM(response_pack_size) AS response_pack_size
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote}
GROUP BY 
    user_id, platform, layout_variant, app_version, dre_version, search_session_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW total_duration_and_be_stats_user_level_all_metrics_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,total_duration
    ,server_cost
    ,request_pack_size
    ,response_pack_size
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote}
UNION ALL
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,'__ALL__' AS operation
    ,total_duration
    ,server_cost
    ,request_pack_size
    ,response_pack_size
FROM
    total_duration_and_be_stats_all_op_search_session_grouped_${grass_region_without_quote};

--sql_divide_splitter--

CREATE TEMPORARY VIEW server_cost_and_request_pack_user_level_freq_count_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,server_cost
    ,request_pack_size
    ,COUNT(1) AS freq_count
FROM
    total_duration_and_be_stats_user_level_all_metrics_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    (user_id, platform, layout_variant, app_version, dre_version, operation, server_cost)
    ,(user_id, platform, layout_variant, app_version, dre_version, operation, request_pack_size)
);

--sql_divide_splitter--

CREATE TEMPORARY VIEW total_duration_and_response_pack_size_pcts_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,IF(GROUPING(layout_variant) = 1, '__ALL__', layout_variant) AS layout_variant
    ,IF(GROUPING(app_version) = 1, '__ALL__', app_version) AS app_version
    ,IF(GROUPING(dre_version) = 1, '__ALL__', dre_version) AS dre_version
    ,operation
    ,APPROX_PERCENTILE(total_duration, ARRAY(0.8, 0.9, 0.95, 0.99), 2000) AS total_duration_pcts
    ,APPROX_PERCENTILE(response_pack_size, ARRAY(0.8, 0.9, 0.95, 0.99), 2000) AS response_pack_size_pcts
FROM
    total_duration_and_be_stats_user_level_all_metrics_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY 
    experiment_id
    ,exp_group_id
    ,platform
    ,CUBE(layout_variant, app_version, dre_version)
    ,operation;

--sql_divide_splitter--

CREATE TEMPORARY VIEW server_cost_freq_count_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,IF(GROUPING(layout_variant) = 1, '__ALL__', layout_variant) AS layout_variant
    ,IF(GROUPING(app_version) = 1, '__ALL__', app_version) AS app_version
    ,IF(GROUPING(dre_version) = 1, '__ALL__', dre_version) AS dre_version
    ,operation
    ,server_cost
    ,SUM(freq_count) AS freq_count
FROM
    server_cost_and_request_pack_user_level_freq_count_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    server_cost IS NOT NULL
GROUP BY 
    experiment_id
    ,exp_group_id
    ,platform
    ,CUBE(layout_variant, app_version, dre_version)
    ,operation
    ,server_cost;

--sql_divide_splitter--

CREATE TEMPORARY VIEW server_cost_pcts_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,PERCENTILE(server_cost, ARRAY(0.8, 0.9, 0.95, 0.99), freq_count) AS server_cost_pcts
FROM
    server_cost_freq_count_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7;

--sql_divide_splitter--

CREATE TEMPORARY VIEW request_pack_size_freq_count_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,IF(GROUPING(layout_variant) = 1, '__ALL__', layout_variant) AS layout_variant
    ,IF(GROUPING(app_version) = 1, '__ALL__', app_version) AS app_version
    ,IF(GROUPING(dre_version) = 1, '__ALL__', dre_version) AS dre_version
    ,operation
    ,request_pack_size
    ,SUM(freq_count) AS freq_count
FROM
    server_cost_and_request_pack_user_level_freq_count_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    request_pack_size IS NOT NULL
GROUP BY 
    experiment_id
    ,exp_group_id
    ,platform
    ,CUBE(layout_variant, app_version, dre_version)
    ,operation
    ,request_pack_size;

--sql_divide_splitter--

CREATE TEMPORARY VIEW request_pack_size_pcts_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,PERCENTILE(request_pack_size, ARRAY(0.8, 0.9, 0.95, 0.99), freq_count) AS request_pack_size_pcts
FROM
    request_pack_size_freq_count_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_total_duration_and_be_statistics_merge_${grass_region_without_quote} AS
SELECT
    COALESCE(a.experiment_id, b.experiment_id, c.experiment_id) AS experiment_id
    ,COALESCE(a.exp_group_id, b.exp_group_id, c.exp_group_id) AS exp_group_id
    ,COALESCE(a.platform, b.platform, c.platform) AS platform
    ,COALESCE(a.layout_variant, b.layout_variant, c.layout_variant) AS layout_variant
    ,COALESCE(a.app_version, b.app_version, c.app_version) AS app_version
    ,COALESCE(a.dre_version, b.dre_version, c.dre_version) AS dre_version
    ,COALESCE(a.operation, b.operation, c.operation) AS operation
    ,total_duration_pcts[0] AS total_duration_p80
    ,total_duration_pcts[1] AS total_duration_p90
    ,total_duration_pcts[2] AS total_duration_p95
    ,total_duration_pcts[3] AS total_duration_p99
    ,server_cost_pcts[0] AS server_cost_p80
    ,server_cost_pcts[1] AS server_cost_p90
    ,server_cost_pcts[2] AS server_cost_p95
    ,server_cost_pcts[3] AS server_cost_p99
    ,request_pack_size_pcts[0] AS request_pack_size_p80
    ,request_pack_size_pcts[1] AS request_pack_size_p90
    ,request_pack_size_pcts[2] AS request_pack_size_p95
    ,request_pack_size_pcts[3] AS request_pack_size_p99
    ,response_pack_size_pcts[0] AS response_pack_size_p80
    ,response_pack_size_pcts[1] AS response_pack_size_p90
    ,response_pack_size_pcts[2] AS response_pack_size_p95
    ,response_pack_size_pcts[3] AS response_pack_size_p99
FROM
    total_duration_and_response_pack_size_pcts_${grass_region_without_quote} a
FULL JOIN
    server_cost_pcts_${grass_region_without_quote} b
ON
    a.experiment_id = b.experiment_id
    AND a.exp_group_id = b.exp_group_id
    AND a.platform = b.platform
    AND a.layout_variant = b.layout_variant
    AND a.app_version = b.app_version
    AND a.dre_version = b.dre_version
    AND a.operation = b.operation
FULL JOIN
    request_pack_size_pcts_${grass_region_without_quote} c
ON
    COALESCE(a.experiment_id, b.experiment_id) = c.experiment_id
    AND COALESCE(a.exp_group_id, b.exp_group_id) = c.exp_group_id
    AND COALESCE(a.platform, b.platform) = c.platform
    AND COALESCE(a.layout_variant, b.layout_variant) = c.layout_variant
    AND COALESCE(a.app_version, b.app_version) = c.app_version
    AND COALESCE(a.dre_version, b.dre_version) = c.dre_version
    AND COALESCE(a.operation, b.operation) = c.operation;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_load_times_${grass_region_without_quote} AS
SELECT
    user_id
    ,platform
    ,IF(GROUPING(layout_variant) = 1, '__ALL__', layout_variant) AS layout_variant
    ,IF(GROUPING(app_version) = 1, '__ALL__', app_version) AS app_version
    ,IF(GROUPING(dre_version) = 1, '__ALL__', dre_version) AS dre_version
    ,operation
    ,search_session_id
    ,COUNT(1) AS load_times
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote}
GROUP BY
    user_id, platform, CUBE(layout_variant, app_version, dre_version), operation, search_session_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW load_times_flatten_${grass_region_without_quote} AS
-- To give pagination & filter operations 0 load_times value under the same dimensions which has business meaning
SELECT
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,search_session_id
    ,SUM(IF(operation = 'action_first_page_performance', load_times, 0)) AS first_page_load_times
    ,SUM(IF(operation = 'action_pagination_performance', load_times, 0)) AS pagination_load_times
    ,SUM(IF(operation = 'action_filter_performance', load_times, 0)) AS filter_load_times
    ,COUNT(IF(operation = 'action_first_page_performance', 1, NULL)) AS first_page_count
    ,COUNT(IF(operation = 'action_pagination_performance', 1, NULL)) AS pagination_count
    ,COUNT(IF(operation = 'action_filter_performance', 1, NULL)) AS filter_count
FROM
    dwd_load_times_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_load_times_exploded_${grass_region_without_quote} AS
SELECT
-- Add back on operation column
-- num_count to remove phantom rows generated where there is completely no pagination or filter from source data
    user_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,exploded.operation AS operation
    ,exploded.load_time AS load_times
FROM
    load_times_flatten_${grass_region_without_quote}
LATERAL VIEW
    EXPLODE(ARRAY(
        STRUCT('action_first_page_performance' AS operation, first_page_load_times AS load_time, first_page_count AS num_count)
        ,STRUCT('action_pagination_performance' AS operation, pagination_load_times AS load_time, pagination_count AS num_count)
        ,STRUCT('action_filter_performance' AS operation, filter_load_times AS load_time, filter_count AS num_count)
    )) AS exploded
WHERE
    exploded.num_count IS NOT NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_load_times_count_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,load_times
    ,COUNT(1) AS load_times_count
FROM
    dwm_load_times_exploded_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3,4,5,6,7,8;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_load_times_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,SUM(load_times * load_times_count) / SUM(load_times_count) AS avg_load_times
    ,PERCENTILE(load_times, ARRAY(0.5, 0.8, 0.9, 0.95, 0.99), load_times_count) AS load_times_pcts
FROM
    dwm_load_times_count_${grass_region_without_quote}
GROUP BY
    1,2,3,4,5,6,7;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_cache_success_rate_${grass_region_without_quote} AS
SELECT
    experiment_id
    ,exp_group_id
    ,platform
    ,IF(GROUPING(layout_variant) = 1, '__ALL__', layout_variant) AS layout_variant
    ,IF(GROUPING(app_version) = 1, '__ALL__', app_version) AS app_version
    ,IF(GROUPING(dre_version) = 1, '__ALL__', dre_version) AS dre_version
    ,SUM(IF(is_cache = 'true', 1, 0)) / COUNT(1) AS cache_success_rate
FROM
    dwd_raw_data_version_filtered_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    operation = 'action_first_page_performance'
GROUP BY
    experiment_id, exp_group_id, platform, CUBE(layout_variant, app_version, dre_version);

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.ads_sr_data_warehouse_search_abtest_app_performance_monitor_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
-- duration metrics are at operation + stage granularity which is seperate from the other metrics
SELECT
/*+ REPARTITION(200) */
    a.experiment_id
    ,a.exp_group_id
    ,duration_p80
    ,duration_p90
    ,duration_p95
    ,duration_p99
    ,NULL AS total_duration_p80
    ,NULL AS total_duration_p90
    ,NULL AS total_duration_p95
    ,NULL AS total_duration_p99
    ,NULL AS server_cost_p80
    ,NULL AS server_cost_p90
    ,NULL AS server_cost_p95
    ,NULL AS server_cost_p99
    ,NULL AS request_pack_size_p80
    ,NULL AS request_pack_size_p90
    ,NULL AS request_pack_size_p95
    ,NULL AS request_pack_size_p99
    ,NULL AS response_pack_size_p80
    ,NULL AS response_pack_size_p90
    ,NULL AS response_pack_size_p95
    ,NULL AS response_pack_size_p99
    ,NULL AS avg_load_times
    ,NULL AS p50_load_times
    ,NULL AS p80_load_times
    ,NULL AS p90_load_times
    ,NULL AS p95_load_times
    ,NULL AS p99_load_times
    ,NULL AS cache_success_rate
    ,group_uu
    ,search_uu
    ,search_volume
    ,platform
    ,layout_variant
    ,app_version
    ,dre_version
    ,operation
    ,stage
    ,category_level
    ,parent_stage
    ,client_type
FROM
    dws_all_stage_duration_merge_${grass_region_without_quote} a
LEFT JOIN
    exp_group_uu_${grass_region_without_quote} b
ON
    a.experiment_id = b.experiment_id
    AND a.exp_group_id = b.exp_group_id
LEFT JOIN
    search_uu_${grass_region_without_quote} c
ON
    a.experiment_id = c.experiment_id
    AND a.exp_group_id = c.exp_group_id
LEFT JOIN
    search_volume_${grass_region_without_quote} d
ON
    a.experiment_id = d.experiment_id
    AND a.exp_group_id = d.exp_group_id
UNION ALL
SELECT
/*+ REPARTITION(200) */
    a.experiment_id AS experiment_id
    ,a.exp_group_id AS exp_group_id
    ,NULL AS duration_p80
    ,NULL AS duration_p90
    ,NULL AS duration_p95
    ,NULL AS duration_p99
    ,total_duration_p80
    ,total_duration_p90
    ,total_duration_p95
    ,total_duration_p99
    ,server_cost_p80
    ,server_cost_p90
    ,server_cost_p95
    ,server_cost_p99
    ,request_pack_size_p80
    ,request_pack_size_p90
    ,request_pack_size_p95
    ,request_pack_size_p99
    ,response_pack_size_p80
    ,response_pack_size_p90
    ,response_pack_size_p95
    ,response_pack_size_p99
    ,avg_load_times
    ,load_times_pcts[0] AS p50_load_times
    ,load_times_pcts[1] AS p80_load_times
    ,load_times_pcts[2] AS p90_load_times
    ,load_times_pcts[3] AS p95_load_times
    ,load_times_pcts[4] AS p99_load_times
    ,cache_success_rate
    ,group_uu
    ,search_uu
    ,search_volume
    ,a.platform AS platform
    ,a.layout_variant AS layout_variant
    ,a.app_version AS app_version
    ,a.dre_version AS dre_version
    ,a.operation AS operation
    ,'__ALL__' AS stage
    ,NULL AS category_level
    ,NULL AS parent_stage
    ,NULL AS client_type
FROM
    dws_total_duration_and_be_statistics_merge_${grass_region_without_quote} a
LEFT JOIN
    dws_load_times_${grass_region_without_quote} b
ON
    a.platform = b.platform
    AND a.layout_variant = b.layout_variant
    AND a.app_version = b.app_version
    AND a.dre_version = b.dre_version
    AND a.operation = b.operation
    AND a.experiment_id = b.experiment_id
    AND a.exp_group_id = b.exp_group_id
LEFT JOIN
    dws_cache_success_rate_${grass_region_without_quote} c
ON
    a.platform = c.platform
    AND a.layout_variant = c.layout_variant
    AND a.app_version = c.app_version
    AND a.dre_version = c.dre_version
    AND a.operation = 'action_first_page_performance'
    AND a.experiment_id = c.experiment_id
    AND a.exp_group_id = c.exp_group_id
LEFT JOIN
    exp_group_uu_${grass_region_without_quote} d
ON
    a.experiment_id = d.experiment_id
    AND a.exp_group_id = d.exp_group_id
LEFT JOIN
    search_uu_${grass_region_without_quote} e
ON
    a.experiment_id = e.experiment_id
    AND a.exp_group_id = e.exp_group_id
LEFT JOIN
    search_volume_${grass_region_without_quote} f
ON
    a.experiment_id = f.experiment_id
    AND a.exp_group_id = f.exp_group_id;
