-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_attribute_level_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_attribute_level_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_homepage_user_attribute_level_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_homepage_user_attribute_level_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_homepage_user_attribute_level_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_homepage_user_attribute_level_1d.sql
-- deprecated: False
-- sha256: 35ecfe22b78448a6a5d14162e7ca290c599e0e69f86b26b4ff035ca317878c07
set platform_home_zreo_statement = 0 as platform_dau
    ,0 as platform_omni_imp_cnt
    ,0 as platform_ppv_cnt
    ,0 as platform_order_cnt
    ,0 as homepage_dau
    ,0 as homepage_stay_time;

--sql_divide_splitter--
set dd_zero_statement = 0 as dd_dau
    ,0 as dd_stay_time
    ,0 as dd_card_imp_cnt
    ,0 as dd_card_click_cnt
    ,0 as dd_card_omni_imp_cnt
    ,0 as dd_card_omni_click_cnt
    ,0 as dd_ppv_cnt
    ,0 as dd_order_cnt
    ,0 as dd_gmv
    ,0 as dd_organic_card_imp_cnt
    ,0 as dd_organic_card_click_cnt
    ,0 as dd_organic_card_omni_imp_cnt
    ,0 as dd_organic_card_omni_click_cnt
    ,0 as dd_organic_ppv_cnt
    ,0 as dd_organic_order_cnt
    ,0 as dd_organic_gmv
    ,0 as dd_ads_card_imp_cnt
    ,0 as dd_ads_card_click_cnt
    ,0 as dd_ads_card_omni_imp_cnt
    ,0 as dd_ads_card_omni_click_cnt
    ,0 as dd_ads_ppv_cnt
    ,0 as dd_ads_order_cnt
    ,0 as dd_ads_gmv;

--sql_divide_splitter--
set dd_item_card_zero_statement = 0 as dd_item_card_imp_cnt
    ,0 as dd_item_card_click_cnt
    ,0 as dd_item_card_ppv_cnt
    ,0 as dd_item_card_order_cnt
    ,0 as dd_item_card_gmv
    ,0 as dd_organic_item_card_imp_cnt
    ,0 as dd_organic_item_card_click_cnt
    ,0 as dd_organic_item_card_ppv_cnt
    ,0 as dd_organic_item_card_order_cnt
    ,0 as dd_organic_item_card_gmv
    ,0 as dd_ads_item_card_imp_cnt
    ,0 as dd_ads_item_card_click_cnt
    ,0 as dd_ads_item_card_ppv_cnt
    ,0 as dd_ads_item_card_order_cnt
    ,0 as dd_ads_item_card_gmv;

--sql_divide_splitter--
set dd_mini_feed_card_zero_statement = 0 as dd_mini_feed_card_imp_cnt
    ,0 as dd_mini_feed_card_click_cnt
    ,0 as dd_mini_feed_card_omni_imp_cnt
    ,0 as dd_mini_feed_card_omni_click_cnt
    ,0 as dd_mini_feed_card_ppv_cnt
    ,0 as dd_mini_feed_card_order_cnt
    ,0 as dd_mini_feed_card_gmv;

--sql_divide_splitter--
set dd_video_card_zero_statement = 0 as dd_video_card_imp_cnt
    ,0 as dd_video_card_click_cnt
    ,0 as dd_video_card_omni_imp_cnt
    ,0 as dd_video_card_omni_click_cnt
    ,0 as dd_video_card_ppv_cnt
    ,0 as dd_video_card_order_cnt
    ,0 as dd_video_card_gmv;

--sql_divide_splitter--
set dd_live_card_zero_statement = 0 as dd_live_card_imp_cnt
    ,0 as dd_live_card_click_cnt
    ,0 as dd_live_card_omni_imp_cnt
    ,0 as dd_live_card_omni_click_cnt
    ,0 as dd_live_card_ppv_cnt
    ,0 as dd_live_card_order_cnt
    ,0 as dd_live_card_gmv;

--sql_divide_splitter--
create temporary view base_data_${grass_region_without_quote} as
select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,dau as platform_dau
    ,omni_imp_cnt as platform_omni_imp_cnt
    ,ppv_cnt as platform_ppv_cnt
    ,order_cnt as platform_order_cnt
    ,0 as homepage_dau
    ,0 as homepage_stay_time
    ,${dd_zero_statement}
    ,${dd_item_card_zero_statement}
    ,${dd_mini_feed_card_zero_statement}
    ,${dd_video_card_zero_statement}
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_platform_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,0 as platform_dau
    ,0 as platform_omni_imp_cnt
    ,0 as platform_ppv_cnt
    ,0 as platform_order_cnt
    ,view_uu as homepage_dau
    ,stay_time as homepage_stay_time
    ,${dd_zero_statement}
    ,${dd_item_card_zero_statement}
    ,${dd_mini_feed_card_zero_statement}
    ,${dd_video_card_zero_statement}
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = '__ALL__'

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,${platform_home_zreo_statement}
    ,imp_uu as dd_dau
    ,stay_time as dd_stay_time
    ,imp_cnt as dd_card_imp_cnt
    ,click_cnt as dd_card_click_cnt
    ,omni_imp_cnt as dd_card_omni_imp_cnt
    ,omni_click_cnt as dd_card_omni_click_cnt
    ,ppv_cnt as dd_ppv_cnt
    ,order_cnt as dd_order_cnt
    ,gmv as dd_gmv
    ,organic_imp_cnt as dd_organic_card_imp_cnt
    ,organic_click_cnt as dd_organic_card_click_cnt
    ,organic_omni_imp_cnt as dd_organic_card_omni_imp_cnt
    ,organic_omni_click_cnt as dd_organic_card_omni_click_cnt
    ,organic_ppv_cnt as dd_organic_ppv_cnt
    ,organic_order_cnt as dd_organic_order_cnt
    ,organic_gmv as dd_organic_gmv
    ,ads_imp_cnt as dd_ads_card_imp_cnt
    ,ads_click_cnt as dd_ads_card_click_cnt
    ,ads_omni_imp_cnt as dd_ads_card_omni_imp_cnt
    ,ads_omni_click_cnt as dd_ads_card_omni_click_cnt
    ,ads_ppv_cnt as dd_ads_ppv_cnt
    ,ads_order_cnt as dd_ads_order_cnt
    ,ads_gmv as dd_ads_gmv
    ,${dd_item_card_zero_statement}
    ,${dd_mini_feed_card_zero_statement}
    ,${dd_video_card_zero_statement}
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = 'Daily Discover'
    and object = '__ALL__'

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,${platform_home_zreo_statement}
    ,${dd_zero_statement}
    ,omni_imp_cnt as dd_item_card_imp_cnt
    ,omni_click_cnt as dd_item_card_click_cnt
    ,ppv_cnt as dd_item_card_ppv_cnt
    ,order_cnt as dd_item_card_order_cnt
    ,gmv as dd_item_card_gmv
    ,organic_omni_imp_cnt as dd_organic_item_card_imp_cnt
    ,organic_omni_click_cnt as dd_organic_item_card_click_cnt
    ,organic_ppv_cnt as dd_organic_item_card_ppv_cnt
    ,organic_order_cnt as dd_organic_item_card_order_cnt
    ,organic_gmv as dd_organic_item_card_gmv
    ,ads_omni_imp_cnt as dd_ads_item_card_imp_cnt
    ,ads_omni_click_cnt as dd_ads_item_card_click_cnt
    ,ads_ppv_cnt as dd_ads_item_card_ppv_cnt
    ,ads_order_cnt as dd_ads_item_card_order_cnt
    ,ads_gmv as dd_ads_item_card_gmv
    ,${dd_mini_feed_card_zero_statement}
    ,${dd_video_card_zero_statement}
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = 'Daily Discover'
    and object = 'item card'

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,${platform_home_zreo_statement}
    ,${dd_zero_statement}
    ,${dd_item_card_zero_statement}
    ,imp_cnt as dd_mini_feed_card_imp_cnt
    ,click_cnt as dd_mini_feed_card_click_cnt
    ,omni_imp_cnt as dd_mini_feed_card_omni_imp_cnt
    ,omni_click_cnt as dd_mini_feed_card_omni_click_cnt
    ,ppv_cnt as dd_mini_feed_card_ppv_cnt
    ,order_cnt as dd_mini_feed_card_order_cnt
    ,gmv as dd_mini_feed_card_gmv
    ,${dd_video_card_zero_statement}
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = 'Daily Discover'
    and object = 'mini_feed_item_card'

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,${platform_home_zreo_statement}
    ,${dd_zero_statement}
    ,${dd_item_card_zero_statement}
    ,${dd_mini_feed_card_zero_statement}
    ,imp_cnt as dd_video_card_imp_cnt
    ,click_cnt as dd_video_card_click_cnt
    ,omni_imp_cnt as dd_video_card_omni_imp_cnt
    ,omni_click_cnt as dd_video_card_omni_click_cnt
    ,ppv_cnt as dd_video_card_ppv_cnt
    ,order_cnt as dd_video_card_order_cnt
    ,gmv as dd_video_card_gmv
    ,${dd_live_card_zero_statement}
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = 'Daily Discover'
    and object = 'video card'

union all

select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,${platform_home_zreo_statement}
    ,${dd_zero_statement}
    ,${dd_item_card_zero_statement}
    ,${dd_mini_feed_card_zero_statement}
    ,${dd_video_card_zero_statement}
    ,imp_cnt as dd_live_card_imp_cnt
    ,click_cnt as dd_live_card_click_cnt
    ,omni_imp_cnt as dd_live_card_omni_imp_cnt
    ,omni_click_cnt as dd_live_card_omni_click_cnt
    ,ppv_cnt as dd_live_card_ppv_cnt
    ,order_cnt as dd_live_card_order_cnt
    ,gmv as dd_live_card_gmv
from ${schema}.dws_sr_data_warehouse_homepage_user_attribute_level_1d
where grass_region = ${grass_region} and local_date = ${local_date}
    and module = 'Daily Discover'
    and object = 'live card'

--sql_divide_splitter--

insert overwrite table ${schema}.ads_sr_data_warehouse_homepage_user_attribute_level_1d
partition(grass_region=${grass_region}, local_date=${local_date})
select
    platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
    ,max(platform_dau) as platform_dau
    ,max(platform_omni_imp_cnt) as platform_omni_imp_cnt
    ,max(platform_ppv_cnt) as platform_ppv_cnt
    ,max(platform_order_cnt) as platform_order_cnt
    ,max(homepage_dau) as homepage_dau
    ,max(homepage_stay_time) as homepage_stay_time
    ,max(dd_dau) as dd_dau
    ,max(dd_stay_time) as dd_stay_time
    ,max(dd_card_imp_cnt) as dd_card_imp_cnt
    ,max(dd_card_click_cnt) as dd_card_click_cnt
    ,max(dd_card_omni_imp_cnt) as dd_card_omni_imp_cnt
    ,max(dd_card_omni_click_cnt) as dd_card_omni_click_cnt
    ,max(dd_ppv_cnt) as dd_ppv_cnt
    ,max(dd_order_cnt) as dd_order_cnt
    ,max(dd_gmv) as dd_gmv
    ,max(dd_organic_card_imp_cnt) as dd_organic_card_imp_cnt
    ,max(dd_organic_card_click_cnt) as dd_organic_card_click_cnt
    ,max(dd_organic_card_omni_imp_cnt) as dd_organic_card_omni_imp_cnt
    ,max(dd_organic_card_omni_click_cnt) as dd_organic_card_omni_click_cnt
    ,max(dd_organic_ppv_cnt) as dd_organic_ppv_cnt
    ,max(dd_organic_order_cnt) as dd_organic_order_cnt
    ,max(dd_organic_gmv) as dd_organic_gmv
    ,max(dd_ads_card_imp_cnt) as dd_ads_card_imp_cnt
    ,max(dd_ads_card_click_cnt) as dd_ads_card_click_cnt
    ,max(dd_ads_card_omni_imp_cnt) as dd_ads_card_omni_imp_cnt
    ,max(dd_ads_card_omni_click_cnt) as dd_ads_card_omni_click_cnt
    ,max(dd_ads_ppv_cnt) as dd_ads_ppv_cnt
    ,max(dd_ads_order_cnt) as dd_ads_order_cnt
    ,max(dd_ads_gmv) as dd_ads_gmv
    ,max(dd_item_card_imp_cnt) as dd_item_card_imp_cnt
    ,max(dd_item_card_click_cnt) as dd_item_card_click_cnt
    ,max(dd_item_card_ppv_cnt) as dd_item_card_ppv_cnt
    ,max(dd_item_card_order_cnt) as dd_item_card_order_cnt
    ,max(dd_item_card_gmv) as dd_item_card_gmv
    ,max(dd_organic_item_card_imp_cnt) as dd_organic_item_card_imp_cnt
    ,max(dd_organic_item_card_click_cnt) as dd_organic_item_card_click_cnt
    ,max(dd_organic_item_card_ppv_cnt) as dd_organic_item_card_ppv_cnt
    ,max(dd_organic_item_card_order_cnt) as dd_organic_item_card_order_cnt
    ,max(dd_organic_item_card_gmv) as dd_organic_item_card_gmv
    ,max(dd_ads_item_card_imp_cnt) as dd_ads_item_card_imp_cnt
    ,max(dd_ads_item_card_click_cnt) as dd_ads_item_card_click_cnt
    ,max(dd_ads_item_card_ppv_cnt) as dd_ads_item_card_ppv_cnt
    ,max(dd_ads_item_card_order_cnt) as dd_ads_item_card_order_cnt
    ,max(dd_ads_item_card_gmv) as dd_ads_item_card_gmv
    ,max(dd_mini_feed_card_imp_cnt) as dd_mini_feed_card_imp_cnt
    ,max(dd_mini_feed_card_click_cnt) as dd_mini_feed_card_click_cnt
    ,max(dd_mini_feed_card_omni_imp_cnt) as dd_mini_feed_card_omni_imp_cnt
    ,max(dd_mini_feed_card_omni_click_cnt) as dd_mini_feed_card_omni_click_cnt
    ,max(dd_mini_feed_card_ppv_cnt) as dd_mini_feed_card_ppv_cnt
    ,max(dd_mini_feed_card_order_cnt) as dd_mini_feed_card_order_cnt
    ,max(dd_mini_feed_card_gmv) as dd_mini_feed_card_gmv
    ,max(dd_video_card_imp_cnt) as dd_video_card_imp_cnt
    ,max(dd_video_card_click_cnt) as dd_video_card_click_cnt
    ,max(dd_video_card_omni_imp_cnt) as dd_video_card_omni_imp_cnt
    ,max(dd_video_card_omni_click_cnt) as dd_video_card_omni_click_cnt
    ,max(dd_video_card_ppv_cnt) as dd_video_card_ppv_cnt
    ,max(dd_video_card_order_cnt) as dd_video_card_order_cnt
    ,max(dd_video_card_gmv) as dd_video_card_gmv
    ,max(dd_live_card_imp_cnt) as dd_live_card_imp_cnt
    ,max(dd_live_card_click_cnt) as dd_live_card_click_cnt
    ,max(dd_live_card_omni_imp_cnt) as dd_live_card_omni_imp_cnt
    ,max(dd_live_card_omni_click_cnt) as dd_live_card_omni_click_cnt
    ,max(dd_live_card_ppv_cnt) as dd_live_card_ppv_cnt
    ,max(dd_live_card_order_cnt) as dd_live_card_order_cnt
    ,max(dd_live_card_gmv) as dd_live_card_gmv
from base_data_${grass_region_without_quote}
group by platform
    ,item_click_level
    ,dd_click_level
    ,major_app_version
    ,app_version
