-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dim_sr_data_warehouse_abtest_user_group
-- physical_table: srdi_mart.dim_sr_data_warehouse_abtest_user_group
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dim_sr_data_warehouse_abtest_user_group
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dim/dim_sr_data_warehouse_abtest_user_group.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dim_sr_data_warehouse_abtest_user_group/analytics-mart-sr-data-warehouse/src/main/resources/dim/dim_sr_data_warehouse_abtest_user_group.sql
-- deprecated: False
-- sha256: e0c92aa143653ee1e6e918c5d23ca6fd948c01b21e1c5bee9a1478d897985bf2
create temporary view abtest_user_group_union_all_${grass_region_without_quote} as
select grass_region
      ,user_id
      ,exp_group_id
      ,max(is_trffic_log) as is_trffic_log
      ,max(is_assignment_log) as is_assignment_log
      ,max(is_rcmd_service) as is_rcmd_service
from (
    select grass_region
          ,user_id
          ,exp_group_id
          ,1 as is_trffic_log
          ,0 as is_assignment_log
          ,0 as is_rcmd_service
    from srdi_mart.dwm_sr_data_warehouse_abtest_traffic_user_group
    where grass_region in (${grass_region})
    and local_date = ${local_date}
    and user_id > 0
    and exp_group_id > 0

    union all
    select grass_region
          ,user_id
          ,group_id as exp_group_id
          ,0 as is_trffic_log
          ,1 as is_assignment_log
           -- 1、这个表的地位极大概率就是前端实验表，只是里面混入了一些后端实验
           -- 2、因为前后端实验用了一个scene等原因，导致前端实验被染色为了is_rcmd_whitelist=1
           -- 3、里面有一些 独有的 后端实验且is_rcmd_whitelist=1的，不过状态都是完成的，且流量（userid-groupid）都是个位数。
           -- 4、里面还有一些 独有的 不明前后端类型且is_rcmd_whitelist=1的，有开启中，也有完成的，但是同样地流量都是个位数。
           -- 综上，这里直接写死为is_rcmd_service=0即可，因为DA侧不看前端实验，如果有其他人看前端实验，需要对外暴露一个前端实验标记（或者现关联dim表）
          ,0 as is_rcmd_service
    from traffic.shopee_traffic_dws_abtest_hit_log_di__reg_live
    where grass_region in (${grass_region})
    and grass_date = ${local_date}
    and tz_type = 'local'
    and user_id > 0
    and group_id > 0

    union all
    select grass_region
          ,user_id
          ,group_id as exp_group_id
          ,0 as is_trffic_log
          ,1 as is_assignment_log
          ,if(servers is not null  -- 服务名不为空，且是rcmd 服务产生的
              and arrays_overlap(servers, array('recommendation_mixer','recommend-bff'))
              ,1,0) as is_rcmd_service
    from abtest.abtest_mart_dws_assignment_agg_1d
    where local_date = ${local_date}
    and grass_region in (${grass_region})
    and scene_id not in (235)
    and user_id > 0
    and group_id > 0
) t
group by grass_region, user_id, exp_group_id
;

--sql_divide_splitter--
create temporary view abtest_exp_group_${grass_region_without_quote} as
select exp_group_id
      ,experiment_id
      ,scene_id
      ,layer_id
      ,project_name
      ,exp_algo_tags

      ,is_rcmd_whitelist
      ,is_search_whitelist
      ,is_rcmd_search_whitelist
      ,is_homepage_whitelist
      ,is_homepage_other_whitelist
      ,is_rcmd_scene_whitelist
      ,is_ads_whitelist
from srdi_mart.dim_sr_data_warehouse_abtest_group
where local_date = ${local_date}
;

--sql_divide_splitter--
insert overwrite table ${schema}.dim_sr_data_warehouse_abtest_user_group partition(grass_region, local_date)
select t1.user_id
      ,t1.exp_group_id

      ,t1.is_trffic_log
      ,t1.is_assignment_log

      ,case
         when t1.is_assignment_log = 1 and t2.is_ads_whitelist = 1 then 1 -- 拼接上ads的白名单实验组
         when t1.is_trffic_log = 1     and coalesce(t2.is_ads_whitelist, 0) = 0 and t1.exp_group_id not in (63960,63961,452746,453033) then 1 -- 本身来自埋点的实验组, 排除掉ads exp
         else 0
       end as is_dim_join

      ,t2.experiment_id
      ,t2.scene_id
      ,t2.layer_id
      ,t2.project_name

      ,t2.exp_algo_tags

      ,t2.is_rcmd_whitelist
      ,t2.is_search_whitelist
      ,t2.is_rcmd_search_whitelist
      ,t2.is_homepage_whitelist
      ,t2.is_homepage_other_whitelist
      ,t2.is_rcmd_scene_whitelist
      ,t2.is_ads_whitelist
      ,t1.is_rcmd_service

      ,t1.grass_region
      ,cast(${local_date} as date) as local_date
from abtest_user_group_union_all_${grass_region_without_quote} t1
left join abtest_exp_group_${grass_region_without_quote} t2 on t1.exp_group_id = t2.exp_group_id
;
