-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_metrics_30d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_metrics_30d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_keyword_metrics_30d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_metrics_30d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_keyword_metrics_30d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_keyword_metrics_30d.sql
-- deprecated: False
-- sha256: 054f4fb284d778733d6761d4ba5ca62602f5e47fd1f91f06a0f98d323c720317
CREATE TEMPORARY VIEW dws_increased_search_volume_${grass_region_without_quote} AS 
SELECT
    keyword
    ,is_ads
    ,card_type
    ,time_range
    ,MAX(IF(local_date = ${local_date},search_volume, 0)) - COALESCE(MAX(IF(local_date = date_sub(${local_date}, 1),search_volume, 0)), 0)  AS increased_search_volume
FROM
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE
    local_date IN (${local_date}, date_sub(${local_date}, 1)) 
    AND grass_region = ${grass_region}
    AND card_type IN ('item', 'video', 'livestream', '__ALL__')
    AND time_range = 1
GROUP BY
    1,2,3,4
UNION ALL 
SELECT
    keyword
    ,is_ads
    ,card_type
    ,time_range
    ,MAX(IF(local_date = ${local_date},search_volume, 0)) - COALESCE(MAX(IF(local_date = date_sub(${local_date}, 7),search_volume, 0)), 0) AS increased_search_volume
FROM
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE
    local_date IN (${local_date}, date_sub(${local_date}, 7)) 
    AND grass_region = ${grass_region}
    AND card_type IN ('item', 'video', 'livestream', '__ALL__')
    AND time_range = 7
GROUP BY
    1,2,3,4
UNION ALL
SELECT
    keyword
    ,is_ads
    ,card_type
    ,time_range
    ,MAX(IF(local_date = ${local_date},search_volume, 0)) - COALESCE(MAX(IF(local_date = date_sub(${local_date}, 30),search_volume, 0)), 0) AS increased_search_volume
FROM
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE
    local_date IN (${local_date}, date_sub(${local_date}, 30)) 
    AND grass_region = ${grass_region}
    AND card_type IN ('item', 'video', 'livestream', '__ALL__')
    AND time_range = 30
GROUP BY
    1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW base_keyword_${grass_region_without_quote} AS
SELECT
    keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,is_ads
    ,card_type

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
    
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,search_volume
    ,user_count
    ,search_volume_rank
    ,time_range
FROM
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE
    local_date IN (${local_date}) 
    AND grass_region = ${grass_region}
    -- AND level1_keyword_category IS NOT NULL
    AND card_type IN ('item', 'video', 'livestream', '__ALL__')
    AND search_volume > 5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW increased_rank_${grass_region_without_quote} AS
SELECT
    a.keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,a.is_ads
    ,a.card_type

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
    
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,search_volume
    ,increased_search_volume
    ,user_count
    ,search_volume_rank
    ,RANK() OVER (PARTITION BY a.level1_keyword_category, a.is_ads, a.card_type, a.time_range
        ORDER BY increased_search_volume DESC) AS increased_rank
    ,a.time_range
FROM
    base_keyword_${grass_region_without_quote} a
    LEFT JOIN dws_increased_search_volume_${grass_region_without_quote} b
    ON a.keyword = b.keyword 
        AND a.is_ads = b.is_ads 
        AND a.card_type = b.card_type
        AND a.time_range = b.time_range;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_keyword_metrics_30d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
    ,time_range
)
SELECT
    keyword
    ,keyword_cluster
    ,level1_keyword_category
    ,level2_keyword_category
    ,is_ads
    ,card_type

    ,imp_cnt
    ,click_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
    
    ,imp_uu
    ,click_uu
    ,ppv_uu
    ,cart_uu
    ,order_uu
    ,search_volume
    ,increased_search_volume
    ,user_count
    ,search_volume_rank
    ,increased_rank
    ,time_range
FROM
    increased_rank_${grass_region_without_quote};
