-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_sr_exp_1d
-- physical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_sr_exp_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_sr_exp_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_tc_pb_sr_exp_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_tc_pb_sr_exp_1d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_tc_pb_sr_exp_1d.sql
-- deprecated: False
-- sha256: 03b8fe22f2bf80e12e3d33a863774e9f489426ffb9b40c44642b741abb8ba30e
-- order和gmv 的场景都是归因出来的，所以在source 1和2 的时候，用copy逻辑，用一个表 本身 union all source 1 union all source 2
-- item 和click 本身是有场景的，虽然也有归因，但是归因也是真是发生不是copy出来的，但是不能用 本身 union all source 1 union all source 2，是应为有的imo 和click 没有形成到order的链路，所以得借助别的表
CREATE TEMPORARY VIEW all_cspu_model_${grass_region_without_quote} AS
SELECT
     item_id
    ,shop_id
    ,cspu_id
    ,model_id
    ,local_hour
from srdi_mart.dim_sr_data_warehouse_pb_all_cspu_link_analysis_hf
where grass_region in (${grass_region})  and local_date = ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cspu_label_${grass_region_without_quote} AS
select
     cspu_id
    ,order_cnt as cspu_l1d_order_cnt
from srdi_mart.dws_sr_data_warehouse_tc_pb_cspu_level_1d
WHERE grass_region IN (${grass_region}) and local_date = date_sub(${local_date}, 1)
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_model_list_${grass_region_without_quote} AS
select
     local_hour as cheapest_hour
    ,c.cspu_id
    ,model_id
    ,item_id
    ,shop_id
    ,business_type
from (
    SELECT
         cspu_id
        ,model_id
        ,item_id
        ,shop_id
        ,local_hour
        ,business_type
    FROM srdi_mart.dim_sr_data_warehouse_pb_one_variation_model_analysis_hf
    WHERE grass_region = ${grass_region} AND local_date = ${local_date}
) c
left join cspu_label_${grass_region_without_quote} d on c.cspu_id=d.cspu_id
where d.cspu_l1d_order_cnt>0 or d.cspu_l1d_order_cnt is null
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_all_model_${grass_region_without_quote} AS
SELECT
    a.*
FROM all_cspu_model_${grass_region_without_quote} a
inner join (
    select
         cheapest_hour
        ,cspu_id
    from cheapest_model_list_${grass_region_without_quote}
    group by cheapest_hour,cspu_id
) b on a.cspu_id=b.cspu_id and a.local_hour=b.cheapest_hour
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_item_list_${grass_region_without_quote} AS
select
     cheapest_hour
    ,item_id
    ,shop_id
from cheapest_model_list_${grass_region_without_quote}
group by
     cheapest_hour
    ,item_id
    ,shop_id
;
--sql_divide_splitter--
CREATE TEMPORARY VIEW winner_item_list_${grass_region_without_quote} AS
select
    cheapest_hour
     ,item_id
     ,shop_id
     ,business_type
from cheapest_model_list_${grass_region_without_quote}
where business_type in (3,4)
group by
    cheapest_hour
       ,item_id
       ,shop_id
       ,business_type
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_cspu_all_item_${grass_region_without_quote} AS
select
     local_hour
    ,item_id
    ,shop_id
from cheapest_cspu_all_model_${grass_region_without_quote}
group by
     local_hour
    ,item_id
    ,shop_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW exp_traffic_info_${grass_region_without_quote} AS
select
     group_id
from abtest.shopee_experiment_admin_db__group_dimension_tab__reg_continuous_s0_live
where scene_id in (
   449, --search_rcmd_priority
   142, --daily_discover_main
   132, --product_detail_page
   368, --cart_unify
   381, --ItemSearch
   443,  --Search guide
   373,
   1605,--global_overlap_scene_sra
   390, --BizExp
   1718, --rcmd_mix_rank
   811,
   515,
   527,
   414,
   435,
   451,
   564,
   601,
   885,
   1267,
   1266,
   1341,
   1196,
   1361,
   1551,
   1574,
   1850
)
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW user_exp_raw_${grass_region_without_quote} as
SELECT
     user_id
    ,exp_group_id
FROM srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE grass_region in (${grass_region}) AND local_date = ${local_date} and is_assignment_log = 1
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
SELECT
     user_id
    ,exp_group_id
FROM user_exp_raw_${grass_region_without_quote} a
inner join exp_traffic_info_${grass_region_without_quote} b on a.exp_group_id = b.group_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_data_${grass_region_without_quote} AS
SELECT
     user_id
    ,shop_id
    ,item_id
    ,model_id
    ,is_ads
    ,mapping_general
    ,cheapest_item
    ,cheapest_cspu_all_item
    ,cheapest_model
    ,cheapest_cspu_all_model
    ,winner_item
    ,bidding_scs_cheapest_item
    ,winner_model
    ,bidding_scs_cheapest_model
    ,sum(imp_cnt) as imp_cnt
    ,sum(order_cnt) as order_cnt
    ,sum(gmv) as gmv
    ,sum(gmv_local) as gmv_local
from(
    SELECT
         a.local_hour
        ,a.user_id
        ,a.shop_id
        ,a.item_id
        ,a.model_id
        ,is_ads
        ,mapping_general
        ,if(b.item_id is not null,1,0) as cheapest_item
        ,if(c.item_id is not null,1,0) as cheapest_cspu_all_item
        ,if(b1.model_id is not null,1,0) as cheapest_model
        ,if(c1.model_id is not null,1,0) as cheapest_cspu_all_model
        ,if(d.item_id is not null,1,0) as winner_item
        ,if(d.business_type = 4,1,0) as bidding_scs_cheapest_item
        ,if(b1.business_type in (3,4),1,0) winner_model
        ,if(b1.business_type = 4,1,0) bidding_scs_cheapest_model
        ,imp_cnt
        ,order_cnt
        ,gmv
        ,gmv_local
    FROM srdi_mart.dws_sr_data_warehouse_tc_pb_basic_aggr_1d a
    left join  cheapest_item_list_${grass_region_without_quote} b on a.shop_id=b.shop_id and a.item_id=b.item_id and a.local_hour=b.cheapest_hour
    left join  cheapest_cspu_all_item_${grass_region_without_quote} c on a.shop_id=c.shop_id and a.item_id=c.item_id and a.local_hour=c.local_hour
    left join  winner_item_list_${grass_region_without_quote} d on a.shop_id=d.shop_id and a.item_id=d.item_id and a.local_hour=d.cheapest_hour
    left join  cheapest_model_list_${grass_region_without_quote} b1 on a.shop_id=b1.shop_id and a.item_id=b1.item_id and a.model_id=b1.model_id and a.local_hour=b1.cheapest_hour
    left join  cheapest_cspu_all_model_${grass_region_without_quote} c1 on a.shop_id=c1.shop_id and a.item_id=c1.item_id and a.model_id=c1.model_id and a.local_hour=c1.local_hour
    WHERE a.grass_region IN (${grass_region}) AND a.local_date = ${local_date}
    and a.mapping_general in ('Search', 'Daily Discover', 'You May Also Like', 'Post Purchase')
) w
group by
     user_id
    ,shop_id
    ,item_id
    ,model_id
    ,is_ads
    ,mapping_general
    ,cheapest_item
    ,cheapest_cspu_all_item
    ,cheapest_model
    ,cheapest_cspu_all_model
    ,winner_item
    ,bidding_scs_cheapest_item
    ,winner_model
    ,bidding_scs_cheapest_model
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW traffic_exp_${grass_region_without_quote} AS
SELECT
     exp_group_id
    ,a.user_id
    ,shop_id
    ,item_id
    ,model_id
    ,is_ads
    ,mapping_general
    ,cheapest_item
    ,cheapest_cspu_all_item
    ,cheapest_model
    ,cheapest_cspu_all_model
    ,winner_item
    ,bidding_scs_cheapest_item
    ,winner_model
    ,bidding_scs_cheapest_model
    ,imp_cnt
    ,order_cnt
    ,gmv
    ,gmv_local
FROM traffic_data_${grass_region_without_quote} a
inner join user_exp_${grass_region_without_quote} b on a.user_id=b.user_id
;
--sql_divide_splitter--
create temporary view traffic_exp_aggr_${grass_region_without_quote} as
select
     if (grouping(is_ads) = 1, '__ALL__', is_ads) as is_ads
    ,mapping_general
    ,exp_group_id
    ,user_id
    ,sum(if (cheapest_model = 1, order_cnt, 0)) as cheapest_model_order_cnt
    ,sum(if (cheapest_model = 1, gmv, 0)) as cheapest_model_gmv
    ,sum(if (cheapest_model = 1, gmv_local, 0)) as cheapest_model_gmv_local
    ,sum(if (cheapest_item = 1, imp_cnt, 0)) as cheapest_item_imp_pv
    ,sum(if (cheapest_item = 1, order_cnt, 0)) as cheapest_item_order_cnt
    ,sum(if (cheapest_item = 1, gmv, 0)) as cheapest_item_gmv
    ,sum(if (cheapest_item = 1, gmv_local, 0)) as cheapest_item_gmv_local

    ,sum(if (cheapest_cspu_all_item = 1, imp_cnt, 0)) as cspu_item_imp_pv
    ,sum(if (cheapest_cspu_all_model = 1, order_cnt, 0)) as cspu_model_order_cnt
    ,sum(if (cheapest_cspu_all_model = 1, gmv, 0)) as cspu_model_gmv
    ,sum(if (cheapest_cspu_all_model = 1, gmv_local, 0)) as cspu_model_gmv_local

    ,sum(imp_cnt) as scene_imp_pv
    ,sum(order_cnt) as scene_order_cnt
    ,sum(gmv) as scene_gmv
    ,sum(gmv_local) as scene_gmv_local
    ,sum(if(bidding_scs_cheapest_item = 1, imp_cnt, 0)) as bidding_scs_cheapest_imp_cnt
    ,sum(if(bidding_scs_cheapest_model = 1, order_cnt, 0)) as bidding_scs_cheapest_order_cnt
    ,sum(if(winner_item = 1, imp_cnt, 0)) as winner_imp_cnt
    ,sum(if(winner_model = 1, order_cnt, 0)) as winner_order_cnt
from traffic_exp_${grass_region_without_quote}
group by grouping sets (
    (exp_group_id, mapping_general, is_ads, user_id),
    (exp_group_id, mapping_general, user_id)
)
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.ads_sr_data_warehouse_tc_pb_sr_exp_1d partition (grass_region = ${grass_region},local_date = ${local_date})
select
    is_ads
     ,mapping_general
     ,exp_group_id

     ,sum(cheapest_model_order_cnt) as cheapest_model_order_cnt
     ,sum(if (cheapest_model_order_cnt > 0, 1, 0)) as cheapest_model_order_uv
     ,sum(cheapest_model_gmv) as cheapest_model_gmv
     ,sum(cheapest_model_gmv_local) as cheapest_model_gmv_local
     ,sum(cheapest_item_imp_pv) as cheapest_item_imp_pv
     ,sum(if (cheapest_item_imp_pv > 0, 1, 0)) as cheapest_item_imp_uv
     ,sum(cheapest_item_order_cnt) as cheapest_item_order_cnt
     ,sum(if (cheapest_item_order_cnt > 0, 1, 0)) as cheapest_item_order_uv
     ,sum(cheapest_item_gmv) as cheapest_item_gmv
     ,sum(cheapest_item_gmv_local) as cheapest_item_gmv_local

     ,sum(cspu_item_imp_pv) as cspu_item_imp_pv
     ,sum(if (cspu_item_imp_pv > 0, 1, 0)) as cspu_item_imp_uv
     ,sum(cspu_model_order_cnt) as cspu_model_order_cnt
     ,sum(if (cspu_model_order_cnt > 0, 1, 0)) as cspu_model_order_uv
     ,sum(cspu_model_gmv) as cspu_model_gmv
     ,sum(cspu_model_gmv_local) as cspu_model_gmv_local

     ,sum(scene_imp_pv) as scene_imp_pv
     ,sum(if (scene_imp_pv > 0, 1, 0)) as scene_imp_uv
     ,sum(scene_order_cnt) as scene_order_cnt
     ,sum(if (scene_order_cnt > 0, 1, 0)) as scene_order_uv
     ,sum(scene_gmv) as scene_gmv
     ,sum(scene_gmv_local) as scene_gmv_local
     ,sum(bidding_scs_cheapest_imp_cnt) as bidding_scs_cheapest_imp_cnt
     ,sum(bidding_scs_cheapest_order_cnt) as bidding_scs_cheapest_order_cnt
     ,sum(winner_imp_cnt) as winner_imp_cnt
     ,sum(winner_order_cnt) as winner_order_cnt
from traffic_exp_aggr_${grass_region_without_quote}
group by
    mapping_general
       ,is_ads
       ,exp_group_id
;
