-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d.sql
-- deprecated: False
-- sha256: ae53ce3fa30b9c870d2ed70893293d0377df8ed84d84c5f3e6ec95383942f8d3
CREATE TEMPORARY VIEW fe_log_${grass_region_without_quote} AS 
SELECT 
    request_id
    ,user_id
    ,device_id
    ,item_id
    ,content_id
    

    ,max(imp_time) AS imp_time
    ,max(platform) AS platform
    ,max(trim(lower(keyword))) AS keyword
    ,max(is_ads) AS is_ads
    ,max(sort_type) AS sort_type
    ,max(with_filter) AS with_filter
    ,max(rule_ids) AS rule_ids
    ,max(search_session_id) AS search_session_id
    ,max(card_type) AS card_type
    -- ,max(sub_product_type) AS sub_product_type
    ,max(search_mid) AS search_mid
    ,max(location) AS location
    ,max(ai_search_info_md5) AS ai_search_info_md5
    ,max(ai_search_info_box) AS ai_search_info_box
    ,transform(max(search_filter_string), x -> to_json(from_json(x, 'struct<filter_type:int,filter_name:string,filter_option:string>'))) AS search_filter
FROM srdi_mart.dws_sr_data_warehouse_search_request_item_metrics_1d
WHERE 
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND (search_mid LIKE 'image%' OR search_mid = 'voice_search')
GROUP BY 
    1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_ads_${grass_region_without_quote} AS 
SELECT
    ads_id
    -- ,pricing_type
    -- ,placement
    -- ,main_product_type
    -- ,product_type
    ,sub_product_type
FROM
    (
        SELECT
            *,
            row_number() over (partition by ads_id,grass_region order by placement DESC) as rn
        FROM
            mp_paidads.dim_advertise__reg_s0_live
        WHERE 
            grass_date = ${local_date}
            AND grass_region = ${grass_region}
            AND tz_type = 'local'
    )
WHERE 
    rn = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW be_log_${grass_region_without_quote} AS
SELECT 
    request_id
    ,item_id
    ,sub_product_type
    ,MAX(rank_score) AS rank_score
    ,MAX(rel_add) AS rel_add
    ,MAX(rel_lx) AS rel_lx
    ,MAX(rel_raw) AS rel_raw
    ,MAX(es_score) AS es_score
    ,MAX( CASE 
        WHEN card_type = '1' THEN 'item'
        WHEN card_type = '6' THEN 'video'
        WHEN card_type = '7' THEN 'livestream'
    END) AS card_type
    ,MAX(multimodal_user_intention_info) AS user_intention
FROM srdi_mart.dwd_sr_data_warehouse_search_be_log a
    LEFT JOIN dim_ads_${grass_region_without_quote} b 
    ON
        CASE
            WHEN coalesce(a.ads_id, a.ads_id_for_roi2, a.ads_id_for_ocpc) IS NULL
            THEN -1000000000 - pmod(xxhash64(coalesce(a.request_id, a.item_id, a.session_id)), 1024)  -- 负数伪键
            ELSE coalesce(a.ads_id, a.ads_id_for_roi2, a.ads_id_for_ocpc)
        END = b.ads_id
WHERE 
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND multimodal_user_intention_info IS NOT NULL
GROUP BY 
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW category_cluster_${grass_region_without_quote} AS
SELECT
    cluster,
    l1_category
FROM
    mkplsearch_data_product.global_category_cluster_mapping
WHERE tree_type = 'local';

--sql_divide_splitter--

CREATE TEMPORARY VIEW keyword_cat_${grass_region_without_quote} AS
SELECT
    keyword_category.keyword AS keyword,
    category_cluster.cluster AS keyword_cluster,
    keyword_category.level1_category_percents[0] AS level1_category,
    keyword_category.level2_category_percents[0] AS level2_category,
    keyword_category.level3_category_percents[0] AS level3_category,
    country
FROM(
    SELECT
        *
    FROM 
    (
        SELECT
            keyword,
            cat_id_percents,
            category_group,
            CASE 
                WHEN level = 1 THEN 'level1'
                WHEN level = 2 THEN 'level2'
                WHEN level = 3 THEN 'level3'
                WHEN level = 4 THEN 'level4'
                WHEN level = 5 THEN 'level5'
            END AS level,
            country
        FROM
            search_algo.ads_query_cat_7d
        WHERE dt = date_sub(next_day( ${local_date}, 'sunday'), 14) -- Find date of next sunday (UTC+8) then -14 day
        AND operation = 'impression'
        AND is_global_cat = true -- filter out non-global categories as they're already deprecated
        and country = ${grass_region}
    )
    PIVOT (
        FIRST(cat_id_percents) AS category_percents, FIRST(category_group) AS category_group
        FOR(level) IN ('level1', 'level2', 'level3', 'level4', 'level5')
    )
) AS keyword_category
LEFT JOIN category_cluster_${grass_region_without_quote} category_cluster
    ON level1_category_percents[0].cat_name = category_cluster.l1_category;

--sql_divide_splitter--

CREATE TEMPORARY VIEW kw_type_${grass_region_without_quote} AS
SELECT
    keyword
    ,CASE
        WHEN keyword_cumulative_search_volume_percentile <= 0.2 THEN '0%-20%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.5 THEN '20%-50%'
        WHEN keyword_cumulative_search_volume_percentile <= 0.8 THEN '50%-80%'
        WHEN keyword_cumulative_search_volume_percentile <= 1.0 THEN '80%-100%'
        ELSE NULL
    END AS keyword_type
FROM 
    srdi_mart.dws_sr_data_warehouse_search_keyword_level_metrics_30d
WHERE 
    grass_region IN (${grass_region})
    AND local_date = ${local_date}
    AND is_ads = '__ALL__'
    AND card_type = '__ALL__'
    AND time_range = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW qp_log_${grass_region_without_quote} AS
SELECT
    unique_key
    ,requestid AS request_id
    ,userid AS user_id
    ,TRANSFORM(FILTER(default_variables, x -> x.name != 'attr_catid'),x -> named_struct('name', x.name, 'value', x.value)) AS default_variables
    ,TRANSFORM(predict_cats, x -> x.id) AS predict_query_category
    ,query_expansion.query_expansions AS query_rewrite
    ,COALESCE(wsrp_rewrite_result.correct_keyword, nsrp_rewrite_result.correct_keyword) AS query_correct
    ,RANK() OVER (PARTITION BY dt,country,requestid,userid ORDER BY unique_key desc) AS offset_rank
    ,country AS grass_region
FROM
    srdi_mart.dwd_fp_search_query_service_request_log_1h
WHERE
    dt BETWEEN ${local_date} AND date_add(${local_date}, 1)
    AND is_execute_query = 1
    AND date(date_timezone_convert(dt,hh,'SG',country,"yyyy-MM-dd")) = ${local_date}
    AND scene_id like '10101%'
    and country = ${grass_region}
;

--sql_divide_splitter--

CREATE TEMPORARY VIEW deduplicated_qp_log_${grass_region_without_quote} AS
SELECT
    *
FROM
    qp_log_${grass_region_without_quote}
WHERE
    offset_rank = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW audio_url_${grass_region_without_quote} AS
SELECT
    user_id
    ,qp_request_id AS request_id
    ,search_session_id
    ,max(audio_url) as audio_url
FROM
    srdi_mart.dws_sr_data_warehouse_voice_search_session_level_metrics_1d
WHERE
    grass_region  = ${grass_region}
    AND local_date = ${local_date}
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_item_${grass_region_without_quote} AS
SELECT
    item_id 
    ,shop_id 
FROM 
    srdi_mart.dim_sr_data_warehouse_item
WHERE
    grass_region  = ${grass_region}
    AND local_date = ${local_date};

--sql_divide_splitter--

CREATE TEMPORARY VIEW ai_search_srp_seq_info_last_element_${grass_region_without_quote} AS
SELECT
    srp_request_id AS request_id
    ,MAX(algo_intent_search_txt) AS algo_intent_search_txt
    ,ELEMENT_AT(MAX(srp_seq_info), -1) AS srp_seq_info_last_element
FROM
    srdi_mart.dws_sr_data_warehouse_ai_search_wide_metrics_1d
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND search_mid LIKE 'image%'
    AND srp_request_id != ''
GROUP BY
    1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW imp_image_id_${grass_region_without_quote} AS
SELECT
    request_id
    ,item_id
    ,location
    ,MAX(image_id) AS imp_image_id
FROM
    srdi_mart.dwd_sr_data_warehouse_platform
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND page_section IS NULL
    AND target_type = 'item'
    AND operation = 'impression'
    AND original_operation = 'impression'
    AND request_id != ''
    AND item_id IS NOT NULL
    AND location IS NOT NULL
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW web_domain_${grass_region_without_quote} AS
SELECT
    region_domain
FROM
    search_data.dim_tmp_region_domain_map
WHERE
    region = ${grass_region};

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_sqe_mutimodal_real_log_1d 
PARTITION (
    grass_region = ${grass_region},
    grass_date = ${local_date}
)
SELECT
/*+ BROADCASTJOIN(j)*/
    a.user_id
    ,a.item_id
    ,shop_id
    ,content_id
    ,a.request_id
    ,a.search_session_id
    ,search_mid
    ,a.card_type
    ,is_ads
    ,sub_product_type
    ,a.keyword
    ,keyword_type
    ,imp_time
    ,a.location AS item_position
    ,es_score
    ,rank_score AS ranking_score
    ,rule_ids
    ,keyword_cluster AS query_cluster
    ,NAMED_STRUCT('L1', NAMED_STRUCT('cat_id', keyword_cat.level1_category.cat_id, 'cat_name',keyword_cat.level1_category.cat_name), 
        'L2', NAMED_STRUCT('cat_id', keyword_cat.level2_category.cat_id, 'cat_name',keyword_cat.level2_category.cat_name), 
        'L3', NAMED_STRUCT('cat_id', keyword_cat.level3_category.cat_id, 'cat_name',keyword_cat.level3_category.cat_name)) AS query_category
    ,predict_query_category
    ,query_rewrite
    ,query_correct
    ,default_variables
    ,rel_raw
    ,rel_lx
    ,rel_add
    ,audio_url
    ,concat('https://search-dl-ws-latam.img.susercontent.com/', ai_search_info_md5) AS image_url
    ,GET_JSON_OBJECT(ai_search_info_box, '$.box_xy') AS image_bounding_box
    ,user_intention
    ,with_filter
    ,sort_type
    ,platform
    ,search_filter
    ,algo_intent_search_txt
    ,GET_JSON_OBJECT(srp_seq_info_last_element, '$.md5') AS last_md5
    ,FROM_JSON(GET_JSON_OBJECT(srp_seq_info_last_element, '$.box_xy'), 'ARRAY<INT>') AS last_box_xy
    ,GET_JSON_OBJECT(srp_seq_info_last_element, '$.keyword') AS last_keyword
    ,CASE WHEN imp_image_id IS NOT NULL THEN
        CONCAT('https://cf.', region_domain, '/file/https://cf.', region_domain, '/file/', imp_image_id) 
        ELSE NULL END
    AS imp_image_url
FROM
    fe_log_${grass_region_without_quote} AS a
LEFT JOIN
    be_log_${grass_region_without_quote} b
ON
    a.request_id = b.request_id
    AND a.item_id = b.item_id
LEFT JOIN
    dim_item_${grass_region_without_quote} c
ON
    a.item_id = c.item_id
LEFT JOIN
    kw_type_${grass_region_without_quote} d
ON
    a.keyword = d.keyword
LEFT JOIN
    keyword_cat_${grass_region_without_quote} keyword_cat
ON
    a.keyword = keyword_cat.keyword
LEFT JOIN
    deduplicated_qp_log_${grass_region_without_quote} f
ON
    a.request_id = f.request_id
    AND a.user_id = f.user_id
LEFT JOIN
    audio_url_${grass_region_without_quote} g
ON
    a.user_id = g.user_id
    AND a.request_id = g.request_id
    AND a.search_session_id = g.search_session_id
LEFT JOIN
    ai_search_srp_seq_info_last_element_${grass_region_without_quote} h
ON
    a.request_id = h.request_id
LEFT JOIN
    imp_image_id_${grass_region_without_quote} i
ON
    a.request_id = i.request_id
    AND a.item_id = i.item_id
    AND a.location = i.location
LEFT JOIN
    web_domain_${grass_region_without_quote} j;
