-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d
-- physical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d.sql
-- deprecated: False
-- sha256: a7f812327e2ab228dc82cb3ed6cc0edff01d2b2d95fa2f30ac774b18e7050560
CREATE TEMPORARY VIEW traffic_${grass_region_without_quote} AS
select *
from srdi_mart.dws_sr_data_warehouse_tc_pb_reward_model_exp_level_1d
where grass_region = ${grass_region}
  and local_date between date_sub(${local_date},29) and ${local_date}
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW winner_30d_${grass_region_without_quote} AS
select model_id
from traffic_${grass_region_without_quote}
where is_win_day = 1 -- 只看winner model
group by 1
;
--sql_divide_splitter--
-- win day日均
CREATE TEMPORARY VIEW avg_30d_${grass_region_without_quote} AS
select a.model_id
    ,1.0000*sum(case when is_win_day=1 then imp_cnt else 0 end)/sum(is_win_day) avg_imp_cnt -- 用于圈选每个档位的model有哪些 & 计算model percentile
    ,sum(case when is_win_day=1 then gmv else 0 end)/sum(is_win_day) avg_gmv
    ,1.0000*sum(case when is_win_day=1 then cspu_imp_cnt else 0 end)/sum(is_win_day) avg_cspu_imp_cnt
    ,sum(case when is_win_day=1 then cspu_gmv else 0 end)/sum(is_win_day) avg_cspu_gmv
    ,sum(case when is_win_day=1 then control_imp_cnt else 0 end) control_imp_cnt
    ,sum(case when is_win_day=1 then treatment_imp_cnt_normal else 0 end) treatment_imp_cnt_normal
    ,sum(case when is_win_day=1 then control_gmv else 0 end) control_gmv
    ,sum(case when is_win_day=1 then treatment_gmv_normal else 0 end) treatment_gmv_normal
from traffic_${grass_region_without_quote} a
inner join winner_30d_${grass_region_without_quote} b
on a.model_id = b.model_id
group by 1
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW model_percentile_${grass_region_without_quote} AS
SELECT percentile.k AS k,
       imp_cnt_pp_arr[percentile.pos] AS imp_cnt_pp,
       gmv_pp_arr[percentile.pos] AS gmv_pp,
       cspu_imp_cnt_pp_arr[percentile.pos] AS cspu_imp_cnt_pp,
       cspu_gmv_pp_arr[percentile.pos] AS cspu_gmv_pp
from (
    SELECT
    APPROX_PERCENTILE(avg_imp_cnt, ARRAY(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)) AS imp_cnt_pp_arr,
    APPROX_PERCENTILE(avg_gmv, ARRAY(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)) AS gmv_pp_arr,
    APPROX_PERCENTILE(avg_cspu_imp_cnt, ARRAY(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)) AS cspu_imp_cnt_pp_arr,
    APPROX_PERCENTILE(avg_cspu_gmv, ARRAY(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)) AS cspu_gmv_pp_arr
    FROM avg_30d_${grass_region_without_quote}
)x
LATERAL VIEW posexplode(ARRAY(0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9)) percentile AS pos, k

union all
select 0 as k
     ,0 as imp_cnt_pp
     ,0 as gmv_pp
     ,0 as cspu_imp_cnt_pp
     ,0 as cspu_gmv_pp
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW imp_cnt_uplift_dict_raw_${grass_region_without_quote} AS
select cspu_k
     , k
     , case when sum(control_imp_cnt)>0 and 1.0000*sum(treatment_imp_cnt_normal)/sum(control_imp_cnt)-1 > 0 then 1.0000*sum(treatment_imp_cnt_normal)/sum(control_imp_cnt)-1
         when sum(control_imp_cnt)<=0 and sum(treatment_imp_cnt_normal)>0 then 1.0
     else 0.02 end as tbi_imp_cnt_uplift_pct
     ,count(distinct model_id) imp_group_model_cnt
from (SELECT model_id
            , control_imp_cnt
            , treatment_imp_cnt_normal
            , a.k as cspu_k
            , b.k
            , row_number() over(partition BY model_id ORDER BY a.k desc, b.k DESC) AS rnk
        from model_percentile_${grass_region_without_quote} a
        join model_percentile_${grass_region_without_quote} b
        on 1=1
        inner join avg_30d_${grass_region_without_quote} c
        on c.avg_cspu_imp_cnt >= a.cspu_imp_cnt_pp
        and c.avg_imp_cnt >= b.imp_cnt_pp
)x
where rnk = 1
group by 1,2
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv_uplift_dict_raw_${grass_region_without_quote} AS
select cspu_k
     , k
     , case when sum(control_gmv)>0 then GREATEST(sum(treatment_gmv_normal)/sum(control_gmv)-1,0)
         when sum(treatment_gmv_normal)>0 then 1.0
     else 0 end as tbi_gmv_uplift_pct
     ,count(distinct model_id) gmv_group_model_cnt
from (SELECT model_id
           , control_gmv
           , treatment_gmv_normal
           , a.k as cspu_k
           , b.k
           , row_number() over(partition BY model_id ORDER BY a.k desc, b.k DESC) AS rnk
      from model_percentile_${grass_region_without_quote} a
      join model_percentile_${grass_region_without_quote} b
      on 1=1
      inner join avg_30d_${grass_region_without_quote} c
      on c.avg_cspu_gmv >= a.cspu_gmv_pp
      and c.avg_gmv >= b.gmv_pp
     )x
where rnk = 1
group by 1,2
;
--sql_divide_splitter--
-- 缺失值填充：0和0.02，前述代码并没有填充缺失值，只填充了负值和零值，应该在现有表的基础上找空区间再填充

CREATE TEMPORARY VIEW combine_uplift_dict_${grass_region_without_quote} AS
SELECT a.k as cspu_k
    ,a.cspu_imp_cnt_pp
    ,a.cspu_gmv_pp
    ,b.k
    ,b.imp_cnt_pp
    ,b.gmv_pp
    ,coalesce(tbi_imp_cnt_uplift_pct,0.02) as tbi_imp_cnt_uplift_pct
    ,coalesce(tbi_gmv_uplift_pct,0) as tbi_gmv_uplift_pct

    ,imp_group_model_cnt
    ,gmv_group_model_cnt
from model_percentile_${grass_region_without_quote} a
join model_percentile_${grass_region_without_quote} b
on 1=1
left join imp_cnt_uplift_dict_raw_${grass_region_without_quote} c
on a.k = c.cspu_k
and b.k = c.k
left join gmv_uplift_dict_raw_${grass_region_without_quote} d
on a.k = d.cspu_k
and b.k = d.k
;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_tc_pb_reward_tbi_uplift_dictionary_30d
PARTITION (grass_region = ${grass_region}, local_date = ${local_date})
select cspu_k
     ,k
     ,cspu_imp_cnt_pp
     ,imp_cnt_pp
     ,tbi_imp_cnt_uplift_pct
     ,cspu_gmv_pp
     ,gmv_pp
     ,tbi_gmv_uplift_pct

--      下列字段仅用于自测
    ,imp_group_model_cnt
    ,gmv_group_model_cnt
from combine_uplift_dict_${grass_region_without_quote}
;
