-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d
-- physical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d/analytics-mart-sr-data-warehouse/src/main/resources/ads/ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d.sql
-- deprecated: False
-- sha256: 25e3d725a54e78cff2c194f616ab42b3e5013f2833d68020b576b87ddb974566

CREATE TEMPORARY VIEW tmp_order_${grass_region_without_quote} AS
SELECT  shop_id
        ,sum(imp_cnt) as imp_cnt
        ,sum(sold_cnt) as order_cnt
        ,sum(gmv) as gmv
FROM    srdi_mart.dwm_sr_data_warehouse_tc_pb_reward_model_mini
WHERE   grass_region = ${grass_region}
  AND   local_date >= date_sub(${local_date}, 29)
  AND   local_date <= ${local_date}
  and   model_status in (1,2)
GROUP BY 1
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW tmp_union_${grass_region_without_quote} AS
SELECT * FROM tmp_order_${grass_region_without_quote};

--sql_divide_splitter--
INSERT OVERWRITE TABLE ${schema}.ads_sr_data_warehouse_tc_pb_reward_banner_shop_30d
PARTITION(grass_region=${grass_region}, local_date=${local_date}, local_hour=${local_hour})
SELECT
    shop_id,
    SUM(imp_cnt) as imp_cnt_30d,
    SUM(order_cnt) as order_cnt_30d,
    SUM(gmv) as gmv_30d
FROM tmp_union_${grass_region_without_quote}
GROUP BY shop_id;
