-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_homepage_user_cardtype_ad_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_homepage_user_cardtype_ad_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_homepage_user_cardtype_ad_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_homepage_user_cardtype_ad_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_homepage_user_cardtype_ad_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_homepage_user_cardtype_ad_1d.sql
-- deprecated: False
-- sha256: 3080ae0ea8d728624e8e894c4a2f8cb9ea405d8a8dc7165d7611be281a585710
create temporary view dwm_homepage_user_item_${grass_region_without_quote} as
select
    user_id
    ,case
        when card_type in ('food_item', 'food_collection') then 'food'
        when card_type in ('insurance_card') then 'insurance'
        when card_type in ('shopeepay_near_me') then 'local service'
        when card_type in ('digital_product') then 'DP'
        when card_type in ('banner') then 'banner'
        when card_type in ('campaign') then 'campaign'
        else coalesce(get_dd_cardtype(object),get_dd_cardtype(source1_object), get_dd_cardtype(source2_object), object)
    end as card_type
    ,case
        when is_ads = true then 1
        else 0
    end as is_ads
    ,sum(imp_cnt) as imp_cnt
    ,sum(click_cnt) as click_cnt
    ,0 as order_cnt
    ,0 as gmv
    ,0 as pc2_gmv
    ,max(case when feature_detail like 'home-daily_discover-%' then location else 0 end) as location
    ,0 as ppv_cnt
from srdi_mart.dwm_sr_data_warehouse_homepage_user_item
where
    local_date = ${local_date}
    and grass_region = ${grass_region}
    and feature_detail like 'home-daily_discover-%'
group by 1, 2, 3
having card_type is not null
;

--sql_divide_splitter--
create temporary view dwm_homepage_user_item_order_ppv_${grass_region_without_quote} as
select
    user_id
    ,coalesce(get_dd_cardtype(object),get_dd_cardtype(source1_object), get_dd_cardtype(source2_object),case when source2_module = 'Daily Discover' then source2_object when source1_module = 'Daily Discover' then source1_object when module = 'Daily Discover' then object end ) as card_type
    ,case when is_ads = true then 1 else 0 end as is_ads
    ,0 as imp_cnt
    ,0 as click_cnt
    ,sum(case when (object in ('shopeepay_near_me') or source1_object in ('shopeepay_near_me') or source2_object in ('shopeepay_near_me'))
                   or (object in ('digital_product') or source1_object in ('digital_product') or source2_object in ('digital_product')) then 0 else order_cnt end) as order_cnt
    ,sum(case when (object in ('shopeepay_near_me') or source1_object in ('shopeepay_near_me') or source2_object in ('shopeepay_near_me'))
                   or (object in ('digital_product') or source1_object in ('digital_product') or source2_object in ('digital_product')) then 0 else gmv end) as gmv
    ,sum(pc2_gmv) as pc2_gmv
    ,sum(ppv_cnt) as ppv_cnt
    ,max(case when feature_detail like 'home-daily_discover-%' then location else 0 end) as location
from srdi_mart.dwm_sr_data_warehouse_homepage_user_item
where
    local_date = ${local_date}
    and grass_region = ${grass_region}
    and ((feature_detail like 'home-daily_discover-%')
    or (source1_feature_detail like 'home-daily_discover-%')
    or (source2_feature_detail like 'home-daily_discover-%'))
group by 1, 2, 3
having card_type is not null


--sql_divide_splitter--
create temporary view dwm_dd_others_user_location_${grass_region_without_quote} as
select
    user_id
    ,case
        when feature_detail = 'home-daily_discover-food' then 'food'
        when feature_detail = 'home-daily_discover-insurance' then 'insurance'
        when feature_detail = 'home-daily_discover-banner' then 'banner'
        when feature_detail = 'home-daily_discover-campaign' then 'campaign'
        when feature_detail = 'home-daily_discover-shopeepay_near_me' then 'local service'
        when feature_detail = 'home-daily_discover-digital_product' then 'DP'
        else null
    end as card_type
    ,0 as is_ads
    ,sum(case when operation = 'order' then operation_cnt else 0 end ) as order_cnt
    ,sum(case when operation = 'order' then gmv else 0 end) as gmv_usd
    ,max(location) as location
    ,sum(case when operation = 'ppv' then operation_cnt else 0 end) as ppv_cnt
from srdi_mart.dwm_sr_data_warehouse_dd_others_user_location
where
    local_date = ${local_date}
    and grass_region = ${grass_region}
group by 1, 2, 3
having card_type is not null
;

--sql_divide_splitter--
cache table dws_homepage_user_duration_${grass_region_without_quote} as
select
    *
from srdi_mart.dws_sr_data_warehouse_homepage_user_duration_1d
where
    local_date = ${local_date}
    and grass_region = ${grass_region}
    and user_id > 0
    and user_id is not null
;

--sql_divide_splitter--
--duration
create temporary view dws_homepage_user_card_ads_duration_${grass_region_without_quote} as
select
    user_id
    ,card_type
    ,is_ads
    ,sum(self_duration) as self_duration
    ,sum(landing_page_duration) as landing_page_duration
    ,sum(pdp_page_duration) as pdp_page_duration
from
    (
        select
            user_id
            ,'item' as card_type
            ,0 as is_ads
            ,dd_cover_duration_1d as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_cover_duration_1d > 0
        union all
        select
            user_id
            ,'video' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,dd_video_landing_page_duration as landing_page_duration
            ,0 as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_video_landing_page_duration > 0
        union all
        select
            user_id
            ,'LS' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,dd_live_duration_1d as landing_page_duration
            ,0 as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_live_duration_1d > 0
        union all
        select
            user_id
            ,'item_feed_card' as card_type
            ,0 as is_ds
            ,0 as self_duration
            ,dd_minifeed_duration_1d as landing_page_duration
            ,0 as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_minifeed_duration_1d > 0
        union all
        select
            user_id
            ,'item_mix_feed_card' as card_type
            ,0 as is_ds
            ,0 as self_duration
            ,dd_mixfeed_duration_1d as landing_page_duration
            ,0 as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_mixfeed_duration_1d > 0
        union all
        select
            user_id
            ,'item' as card_type
            ,1 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_ads_item_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_ads_item_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'item_mix_feed_card' as card_type
            ,1 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_ads_item_mix_feed_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_ads_item_mix_feed_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'item' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_organic_item_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_organic_item_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'item_mix_feed_card' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_organic_item_mix_feed_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_organic_item_mix_feed_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'video' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_video_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_video_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'LS' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_live_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_live_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'item_feed_card' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,dd_minifeed_pdp_duraion_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where dd_minifeed_pdp_duraion_1d > 0

        union all
        select
            user_id
            ,'new_arrival_card' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,new_arrival_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where new_arrival_pdp_duration_1d > 0
        union all
        select
            user_id
            ,'cheapest_landing_card' as card_type
            ,0 as is_ads
            ,0 as self_duration
            ,0 as landing_page_duration
            ,cheapest_pdp_duration_1d as pdp_page_duration
        from dws_homepage_user_duration_${grass_region_without_quote}
        where cheapest_pdp_duration_1d > 0
    )
group by 1, 2, 3
;

--sql_divide_splitter--
-- vv
create temporary view vv_data_${grass_region_without_quote} as
select
    grass_region
    ,grass_date as local_date
    ,user_id
    ,case
        when sv_source_page in ('iaa_dd_mix_item') then 'item_mix_feed_card'
        when sv_source_page in ('iaa_dd_video_card') then 'video'
    end as card_type
    ,case when coalesce(is_item_ads,0) = 1 then 1 else 0 end as is_ads
    ,sum(video_play_cnt_ntl_1d) as vv
from video.video_mart_dws_external_dd_mixfeed_ssecid_user_1d
where
    grass_region = ${grass_region}
    and grass_date = ${local_date}
    and current_page in ('mix_feed_page', 'common_video_feed_page','dd_video_new_landing_page')
    and sv_source_page in ('iaa_dd_mix_item', 'iaa_dd_video_card')
group by 1, 2, 3, 4, 5
;

--sql_divide_splitter--
--internal scroll depth
create temporary view internal_scroll_depth_${grass_region_without_quote} as
select
    user_id
    ,case
        when get_json_object(data, '$.position.current_page') in ('mix_feed_page', 'common_video_feed_page','dd_video_new_landing_page')
            and get_json_object(data, '$.params.sv_source_page') = 'iaa_dd_video_card'
            then 'video'
        when get_json_object(data, '$.position.current_page') in ('mix_feed_page')
            and get_json_object(data, '$.params.sv_source_page') = 'iaa_dd_mix_item'
            then 'item_mix_feed_card'
    end as card_type
    ,case when coalesce(get_json_object(data,'$.params.is_ads'),'') = 'true' then 1 else 0 end as is_ads
    ,max(cast(get_json_object(data, '$.params.index') as int)) as internal_scroll_depth
from video.video_mart_dwd_external_dd_mixfeed_traffic_hi
where
    grass_region = ${grass_region}
    and grass_date = ${local_date}
    and page_type = 'video'
    and operation = 'impression'
    and target_type = 'video_product_impression'
    and (
        (
            get_json_object(data, '$.position.current_page') in ('mix_feed_page', 'common_video_feed_page','dd_video_new_landing_page')
            and get_json_object(data, '$.params.sv_source_page') = 'iaa_dd_video_card'
        )
        or (
            get_json_object(data, '$.position.current_page') = 'mix_feed_page'
            and get_json_object(data, '$.params.sv_source_page') = 'iaa_dd_mix_item'
        )
    )
group by 1, 2 ,3
;

--sql_divide_splitter--
create temporary view minippv_data_base_${grass_region_without_quote} as
select  grass_region
        ,local_date as grass_date
        ,user_id
        ,coalesce(get_dd_cardtype(source1_object), source1_object) as card_type
        ,sum(item_impr_organic_cnt_1d) as minippv_organic
        ,sum(item_impr_ads_cnt_1d) as minippv_ads
from    traffic_omni_oa.dws_business_line_sales_funnel_metrics_1d__reg_sensitive_live
where   grass_region = ${grass_region}
  and   local_date = ${local_date}
  and   (
                source1_business_line = 'Homepage'
            and source1_module = 'Daily Discover'
        )
group by 1, 2, 3, 4
;

--sql_divide_splitter--
create temporary view minippv_data_result_${grass_region_without_quote} as
select
    user_id
    ,card_type
    ,1 as is_ads
    ,minippv_ads as minippv_cnt
from minippv_data_base_${grass_region_without_quote}
where coalesce(minippv_ads, 0) > 0
union all
select
    user_id
    ,card_type
    ,0 as is_ads
    ,minippv_organic as minippv_cnt
from minippv_data_base_${grass_region_without_quote}
where coalesce(minippv_organic, 0) > 0
;

--sql_divide_splitter--
create temporary view union_data_result_${grass_region_without_quote} as
select
    user_id
    ,card_type
    ,is_ads
    ,sum(imp_cnt) as imp_cnt
    ,sum(click_cnt) as click_cnt
    ,sum(order_cnt) as order_cnt
    ,sum(gmv) as gmv
    ,sum(pc2_gmv) as pc2_gmv
    ,max(location) as location
    ,sum(ppv_cnt) as ppv_cnt
    ,sum(minippv_cnt) as minippv_cnt
    ,sum(vv) as vv
    ,sum(self_duration) as self_duration
    ,sum(landing_page_duration) as landing_page_duration
    ,sum(pdp_page_duration) as pdp_page_duration
    ,max(internal_scroll_depth) as internal_scroll_depth
from
    (
        select
            user_id
            ,card_type
            ,is_ads
            ,imp_cnt
            ,click_cnt
            ,order_cnt
            ,gmv
            ,pc2_gmv
            ,location
            ,ppv_cnt
            ,0 as minippv_cnt
            ,0 as vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,null as internal_scroll_depth
        from dwm_homepage_user_item_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,imp_cnt
            ,click_cnt
            ,order_cnt
            ,gmv
            ,pc2_gmv
            ,location
            ,ppv_cnt
            ,0 as minippv_cnt
            ,0 as vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,null as internal_scroll_depth
        from dwm_homepage_user_item_order_ppv_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,0 as imp_cnt
            ,0 as click_cnt
            ,order_cnt
            ,gmv_usd
            ,0 as pc2_gmv
            ,location
            ,ppv_cnt
            ,0 as minippv_cnt
            ,0 as vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,null as internal_scroll_depth
        from dwm_dd_others_user_location_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,0 as imp_cnt
            ,0 as click_cnt
            ,0 as order_cnt
            ,0 as gmv
            ,0 as pc2_gmv
            ,null as location
            ,0 as ppv_cnt
            ,0 as minippv_cnt
            ,0 as vv
            ,self_duration
            ,landing_page_duration
            ,pdp_page_duration
            ,null as internal_scroll_depth
        from dws_homepage_user_card_ads_duration_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,0 as imp_cnt
            ,0 as click_cnt
            ,0 as order_cnt
            ,0 as gmv
            ,0 as pc2_gmv
            ,null as location
            ,0 as ppv_cnt
            ,0 as minippv_cnt
            ,vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,null as internal_scroll_depth
        from vv_data_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,0 as imp_cnt
            ,0 as click_cnt
            ,0 as order_cnt
            ,0 as gmv_usd
            ,0 as pc2_gmv
            ,null as location
            ,0 as ppv_cnt
            ,0 as minippv_cnt
            ,0 as vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,internal_scroll_depth
        from internal_scroll_depth_${grass_region_without_quote}
        union all
        select
            user_id
            ,card_type
            ,is_ads
            ,0 as imp_cnt
            ,0 as click_cnt
            ,0 as order_cnt
            ,0 as gmv_usd
            ,0 as pc2_gmv
            ,null as location
            ,0 as ppv_cnt
            ,minippv_cnt
            ,0 as vv
            ,0 as self_duration
            ,0 as landing_page_duration
            ,0 as pdp_page_duration
            ,null as internal_scroll_depth
        from minippv_data_result_${grass_region_without_quote}
    )
group by 1, 2, 3
;

--sql_divide_splitter--
create temporary view dim_user_${grass_region_without_quote} as
select
    user_id
    ,platform
    ,app_version_prefix
    ,user_purchase_type
from srdi_mart.dim_sr_data_warehouse_user_label
where
    grass_region = ${grass_region}
    and local_date = ${local_date}
;


--sql_divide_splitter--
INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_homepage_user_cardtype_ad_1d
partition (grass_region = ${grass_region}, local_date = ${local_date})
select
    T1.user_id
    ,T2.user_purchase_type
    ,T2.platform
    ,T2.app_version_prefix
    ,T1.card_type
    ,T1.is_ads
    ,T1.imp_cnt
    ,T1.click_cnt
    ,T1.order_cnt
    ,T1.gmv
    ,T1.pc2_gmv
    ,T1.location
    ,T1.ppv_cnt
    ,T1.minippv_cnt
    ,T1.vv
    ,T1.self_duration
    ,T1.landing_page_duration
    ,T1.pdp_page_duration
    ,T1.internal_scroll_depth
from
    union_data_result_${grass_region_without_quote} as T1
    left join dim_user_${grass_region_without_quote} as T2
    on T1.user_id = T2.user_id
