-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d.sql
-- deprecated: False
-- sha256: 12fce20d0526e48bde5345ec6a91aa4e2f1d26fe4a32d40397d2ad7a61d777da
CREATE TEMPORARY VIEW shop_type_${grass_region_without_quote} AS
select
     shop_id
    ,type as shop_scs_type
from regds_listing.dim_scs_shop_list_df
where grass_region in (${grass_region}) and type in ('scs-local','scs-cb')
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW all_cspu_model_${grass_region_without_quote} AS
SELECT
     item_id
    ,a.shop_id
    ,shop_scs_type
    ,cspu_id
    ,model_id
    ,local_hour
from (
    SELECT
         item_id
        ,shop_id
        ,cspu_id
        ,model_id
        ,local_hour
    from srdi_mart.dim_sr_data_warehouse_pb_all_cspu_link_analysis_hf
    where grass_region in (${grass_region})  and local_date = ${local_date}
) a
left join shop_type_${grass_region_without_quote} b on a.shop_id=b.shop_id
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cspu_label_${grass_region_without_quote} AS
select
     cspu_id
    ,order_cnt as cspu_l1d_order_cnt
from srdi_mart.dws_sr_data_warehouse_tc_pb_cspu_level_1d
WHERE grass_region IN (${grass_region}) and local_date = date_sub(${local_date}, 1)
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW cheapest_model_list_${grass_region_without_quote} AS
select
     local_hour as cheapest_hour
    ,a.cspu_id
    ,model_id
    ,item_id
    ,a.shop_id
    ,shop_scs_type
from (
    SELECT
         cspu_id
        ,model_id
        ,item_id
        ,shop_id
        ,business_type
        ,local_hour
    FROM srdi_mart.dim_sr_data_warehouse_pb_one_variation_model_analysis_hf
    WHERE grass_region = ${grass_region} AND local_date = ${local_date}
) a
left join shop_type_${grass_region_without_quote} b on a.shop_id=b.shop_id
left join cspu_label_${grass_region_without_quote} c on a.cspu_id=c.cspu_id
where business_type in (3,4)
   or (business_type in (1,2)
           and (c.cspu_l1d_order_cnt>0 or c.cspu_l1d_order_cnt is null)
       )
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW cheapest_cspu_all_model_${grass_region_without_quote} AS (
SELECT
    a.*
FROM all_cspu_model_${grass_region_without_quote} a
inner join (
    select
         cheapest_hour
        ,cspu_id
    from cheapest_model_list_${grass_region_without_quote}
    group by cheapest_hour,cspu_id
) b on a.cspu_id=b.cspu_id and a.local_hour=b.cheapest_hour
)
;
--sql_divide_splitter--
CREATE TEMPORARY VIEW cheapest_item_list_${grass_region_without_quote} AS (
select
     cheapest_hour
    ,item_id
    ,shop_id
    ,max(shop_scs_type) as shop_scs_type
from cheapest_model_list_${grass_region_without_quote}
group by
     cheapest_hour
    ,item_id
    ,shop_id
)
;
--sql_divide_splitter--
cache table cheapest_cspu_all_item_${grass_region_without_quote} AS (
select
     local_hour
    ,item_id
    ,shop_id
    ,max(shop_scs_type) as shop_scs_type
from cheapest_cspu_all_model_${grass_region_without_quote}
group by
     local_hour
    ,item_id
    ,shop_id
)
;

--sql_divide_splitter--
INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_tc_pb_basic_tag_aggr_1d
partition (grass_region = ${grass_region},local_date = ${local_date}, local_hour)
select  is_item_card
        ,user_id
        ,is_ads
        ,mapping_general
        ,a.shop_id
        ,a.item_id
        ,a.model_id

        ,if(b.item_id is not null,1,0) as cheapest_item
        ,if(c.item_id is not null,1,0) as cheapest_cspu_all_item
        ,if(b1.model_id is not null,1,0) as cheapest_model
        ,if(c1.model_id is not null,1,0) as cheapest_cspu_all_model

        ,coalesce(b1.shop_scs_type,b.shop_scs_type,c1.shop_scs_type,c.shop_scs_type,'') as shop_scs_type
        ,null as cspu_pr_rate

        ,imp_cnt
        ,click_cnt
        ,order_cnt
        ,gmv
        ,gmv_local
        ,pc2_gmv

        ,a.local_hour
from    (
    select  *
    from    srdi_mart.dws_sr_data_warehouse_tc_pb_basic_aggr_1d
    where   grass_region = ${grass_region}
      and   local_date = ${local_date}
      and   mapping_general in ('Post Purchase', 'Daily Discover', 'Search', 'You May Also Like', 'Shop', 'S&R__ALL__', '__ALL__' , 'Video', 'Live Streaming')
) as a
left join  cheapest_item_list_${grass_region_without_quote} b on  a.item_id=b.item_id and a.local_hour=b.cheapest_hour
left join  cheapest_cspu_all_item_${grass_region_without_quote} c on a.item_id=c.item_id and a.local_hour=c.local_hour
left join  cheapest_model_list_${grass_region_without_quote} b1 on  a.item_id=b1.item_id and a.model_id=b1.model_id and a.local_hour=b1.cheapest_hour
left join  cheapest_cspu_all_model_${grass_region_without_quote} c1 on a.item_id=c1.item_id and a.model_id=c1.model_id and a.local_hour=c1.local_hour
;
