-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d.sql
-- deprecated: False
-- sha256: c1722851821e2c4af42b4136005b8e28c2d334bcc5eab3509c902c7a74efba1e
CREATE TEMPORARY VIEW dim_whitelist_scene_${grass_region_without_quote} AS
SELECT DISTINCT
    CAST(scene_id AS INT) as scene_id
FROM
    srdi_mart.dim_sr_data_warehouse_search_scene_layer_whitelist
WHERE
    scene_id IS NOT NULL
    AND scene_id <> '';

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_whitelist_layer_${grass_region_without_quote} AS
SELECT DISTINCT
    CAST(layer_id AS INT) as layer_id
FROM
    srdi_mart.dim_sr_data_warehouse_search_scene_layer_whitelist
WHERE
    layer_id IS NOT NULL
    AND layer_id <> '';

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_exp_${grass_region_without_quote} AS
SELECT
    scene_id
    ,scene_name
    ,layer_id
    ,layer_name
    ,experiment_id
    ,experiment_name
    ,exp_group_id
    ,exp_group_name
FROM
    srdi_mart.dim_sr_data_warehouse_abtest_group
WHERE
    local_date = ${local_date}
    AND is_search_whitelist = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW user_exp_mapping_${grass_region_without_quote} AS
SELECT
    user_id
    ,exp_group_id
    ,local_date
FROM
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
WHERE
    grass_region = ${grass_region}
    AND local_date IN (${local_date}, date_sub(${local_date}, 1), date_sub(${local_date}, 7))
    AND is_assignment_log = 1
    AND is_search_whitelist = 1;

--sql_divide_splitter--

CACHE TABLE user_exp_mapping_1d_${grass_region_without_quote} AS
SELECT
    *
FROM
    user_exp_mapping_${grass_region_without_quote}
WHERE
    local_date = ${local_date};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_search_user_keyword_raw_${grass_region_without_quote} AS
SELECT
    local_date
    ,user_id
    ,device_id
    ,keyword
    ,page_type
    ,page_section
    ,target_type
    ,IF(is_ads IS NOT NULL, is_ads, 'false') AS is_ads
    ,IF(search_entrance IS NOT NULL AND trim(lower(search_entrance)) != '', trim(lower(search_entrance)), 'NA') AS search_entrance
    ,imp_cnt
    ,view_cnt
    ,ppv_cnt
    ,cart_cnt
    ,order_cnt
    ,gmv
    ,pc2_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_srp_user_benchmark_1d
WHERE
    local_date IN (${local_date}, date_sub(${local_date}, 1), date_sub(${local_date}, 7))
    AND grass_region = ${grass_region}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND user_id > 0;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_search_feature_${grass_region_without_quote} AS
SELECT
    user_id
    ,device_id
    ,keyword
    ,CASE
        WHEN page_section IS NULL AND target_type = 'item' THEN 'item'
        WHEN page_section IS NULL AND target_type = 'video' THEN 'video'
        WHEN page_section IS NULL AND target_type = 'livestream' THEN 'livestream'
        ELSE 'Other'
    END AS card_type
    ,cast(is_ads AS STRING) AS is_ads
    ,search_entrance
    ,IF(search_entrance IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,local_date
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(view_cnt) AS view_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv
    ,SUM(pc2_gmv) AS pc2_gmv
    ,MAX(CASE WHEN view_cnt > 0 OR (imp_cnt > 0 AND target_type = 'no_recall_general') THEN true ELSE false END) AS keyword_flag
    ,MAX(CASE WHEN imp_cnt > 0 AND target_type = 'no_recall_general' THEN true ELSE false END) AS norecall_keyword_flag
FROM
    dwm_search_user_keyword_raw_${grass_region_without_quote} t1
GROUP BY
    1,2,3,4,5,6,7,8;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_entrance_${grass_region_without_quote} AS
SELECT
    user_id
    ,IF(GROUPING(card_type) = 1, '__ALL__', card_type) AS card_type
    ,IF(GROUPING(is_ads) = 1, '__ALL__', CAST(is_ads AS STRING)) AS is_ads
    ,search_entrance_exploded AS search_entrance
    ,SUM(if(card_type IN ('item', 'video', 'livestream') ,imp_cnt, 0)) AS imp_cnt
    ,SUM(if(card_type IN ('item', 'video', 'livestream') ,gmv, 0)) AS gmv
    ,SUM(if(card_type IN ('item', 'video', 'livestream') ,pc2_gmv, 0)) AS pc2_gmv
    ,CASE WHEN SUM(order_cnt) > 0 THEN SUM(gmv) / SUM(order_cnt) ELSE 0 END AS abs
FROM
    dws_search_feature_${grass_region_without_quote}
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
WHERE
    local_date = ${local_date}
    AND (
        card_type IN ('item', 'video', 'livestream')
        OR view_cnt > 0
    )
GROUP BY
    user_id, CUBE(card_type, is_ads), search_entrance_exploded;

--sql_divide_splitter--

CACHE TABLE global_search_abs995_benchmark_${grass_region_without_quote} AS
SELECT
    is_ads,
    APPROX_PERCENTILE(IF(abs > 0, abs, NULL), 0.995) AS global_search_abs_995 -- 每个地区每天，根据是否为广告会有三个阈值：广告、非广告、整体
FROM 
    dws_entrance_${grass_region_without_quote}
WHERE 
    search_entrance = '__ALL__'
    AND card_type = '__ALL__'
GROUP BY
    1;

--sql_divide_splitter--

CACHE TABLE dws_995_metrics_${grass_region_without_quote} AS
SELECT
/*+ BROADCASTJOIN(c) */
    exp_group_id
    ,card_type
    ,a.is_ads
    ,search_entrance
    ,SUM(IF(abs <= c.global_search_abs_995, gmv, 0)) AS gmv_995
    ,SUM(IF(abs <= c.global_search_abs_995, gmv, 0)) / COUNT(CASE WHEN imp_cnt > 0 AND abs <= c.global_search_abs_995 THEN a.user_id ELSE NULL END) AS gmv_uu_995
    ,SUM(IF(abs <= c.global_search_abs_995, pc2_gmv, 0)) AS pc2_gmv_995
    ,SUM(IF(abs <= c.global_search_abs_995, pc2_gmv, 0)) / COUNT(CASE WHEN imp_cnt > 0 AND abs <= c.global_search_abs_995 THEN a.user_id ELSE NULL END) AS pc2_gmv_uu_995
FROM
    dws_entrance_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LEFT JOIN
    global_search_abs995_benchmark_${grass_region_without_quote} c
ON
    a.is_ads = c.is_ads
GROUP BY
    1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_norecall_rate_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance_exploded AS search_entrance
    ,IF(
        COUNT(DISTINCT CASE WHEN keyword_flag = true THEN (a.user_id, a.keyword) ELSE NULL END) != 0
        ,1.0 * COUNT(DISTINCT CASE WHEN keyword_flag = true AND norecall_keyword_flag = true THEN (a.user_id, a.keyword) ELSE NULL END)
            / COUNT(DISTINCT CASE WHEN keyword_flag = true THEN (a.user_id, a.keyword) ELSE NULL END)
        ,0
    ) AS norecall_rate
FROM
    dws_search_feature_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
    AND a.local_date = b.local_date
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2;

--sql_divide_splitter--

-- retention metric --
CREATE TEMPORARY VIEW srp_user_view_${grass_region_without_quote} AS
SELECT
    user_id
    ,search_entrance_exploded AS search_entrance
    ,local_date
FROM
    dws_search_feature_${grass_region_without_quote}
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
WHERE
    view_cnt > 0
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW retention_exp_user_${grass_region_without_quote} AS 
SELECT
    exp_group_id
    ,a.user_id
    ,search_entrance
    ,MAX(IF(a.local_date = date_sub(${local_date}, 7), true, false)) AS 7d_user
    ,MAX(IF(a.local_date = date_sub(${local_date}, 1), true, false)) AS 1d_user
    ,MAX(IF(a.local_date = ${local_date}, true, false)) AS 0d_user
FROM
    srp_user_view_${grass_region_without_quote} a
JOIN
    user_exp_mapping_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
    AND a.local_date = b.local_date
GROUP BY
    1,2,3;

--sql_divide_splitter--

CACHE TABLE retention_exp_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance
    ,SUM(IF(7d_user = true, 1, 0)) AS search_uu_7d
    ,SUM(IF(0d_user = true AND 7d_user = true, 1, 0)) AS retention_uu_7d
    ,SUM(IF(1d_user = true, 1, 0)) AS search_uu_1d
    ,SUM(IF(0d_user = true AND 1d_user = true, 1, 0)) AS retention_uu_1d
    ,SUM(IF(0d_user = true, 1, 0)) AS search_uu
FROM
    retention_exp_user_${grass_region_without_quote}
GROUP BY 
    1,2;

--sql_divide_splitter--
-- search scene metric --
CREATE TEMPORARY VIEW srp_all_search_scene_${grass_region_without_quote} AS
SELECT
    user_id
    ,IF(search_entrance IS NOT NULL AND trim(lower(search_entrance)) != '', trim(lower(search_entrance)), 'NA') AS search_entrance
    ,IF(TRIM(LOWER(search_entrance)) IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,SUM(imp_cnt) AS imp_cnt
FROM
    srdi_mart.dws_sr_data_warehouse_search_srp_user_benchmark_1d a
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND user_id > 0
    AND target_type IN ('item', 'video', 'livestream', 'related_search')
    AND page_type in (
            'global_search'
            ,'search_in_mall'
            ,'search_in_microsite'
            ,'search_in_main_category'
            ,'collection'
            ,'search_in_others'
            ,'search_in_collection'
            ,'search_in_product_attribute'
            ,'main_category_browsing'
            ,'search_in_voucher'
            ,'search_in_subcategory'
            ,'search_in_pdp'
            ,'search_prefill'
            ,'search'
        )
    AND page_section IS NULL 
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW search_scene_exp_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance_exploded AS search_entrance
    ,SUM(imp_cnt) AS search_scene_imp_cnt
FROM
    srp_all_search_scene_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2;

--sql_divide_splitter--
-- ROI metric --
CREATE TEMPORARY VIEW ads_performance_${grass_region_without_quote} AS
SELECT
    user_id
    ,IF(search_entrance IS NOT NULL AND trim(lower(search_entrance)) != '', trim(lower(search_entrance)), 'NA') AS search_entrance
    ,IF(TRIM(LOWER(search_entrance)) IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,SUM(expenditure_amt_usd) AS expenditure_amt_usd
    ,SUM(impression_cnt) AS paidads_imp_cnt
FROM
    mp_paidads.dwd_advertise_performance_di__reg_s0_live
WHERE
    grass_date = ${local_date}
    AND grass_region = ${grass_region}
    AND tz_type = 'local'
    AND entrance = 1
    AND user_id > 0
GROUP BY
    1,2,3;

--sql_divide_splitter--

CACHE TABLE dws_ads_performance_${grass_region_without_quote} AS 
SELECT 
    exp_group_id
    ,search_entrance_exploded AS search_entrance
    ,SUM(a.expenditure_amt_usd) AS ads_revenue
    ,SUM(paidads_imp_cnt) AS paidads_imp_cnt
FROM
    ads_performance_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2;

--sql_divide_splitter--
-- srp duration metrics --
CREATE TEMPORARY VIEW dwd_srp_duration_${grass_region_without_quote} AS 
SELECT
    userid AS user_id
    ,IF(GET_JSON_OBJECT(data,'$.search_FE.search_entrance.entrance') IS NOT NULL AND trim(lower(GET_JSON_OBJECT(data,'$.search_FE.search_entrance.entrance'))) != '', trim(lower(GET_JSON_OBJECT(data,'$.search_FE.search_entrance.entrance'))), 'NA') AS search_entrance
    ,IF(TRIM(LOWER(GET_JSON_OBJECT(data,'$.search_FE.search_entrance.entrance'))) IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,SUM(CAST(GET_JSON_OBJECT(data,'$.duration') as bigint)) AS duration
FROM 
    traffic.shopee_traffic_dwd_click_hi__reg_s1_live 
WHERE  
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND page_type = 'search'
    AND operation= 'stay_view'
    AND GET_JSON_OBJECT(data,'$.search_FE.search_params.search_scenario.key') in ('PAGE_GLOBAL_SEARCH','PAGE_PDP_SEARCH','PAGE_PREFILL_SEARCH') --限制global search
    AND userid > 0 and userid is not null--限制登录用户
    AND CAST(GET_JSON_OBJECT(data,'$.duration') as bigint) >0  
    AND CAST(GET_JSON_OBJECT(data,'$.duration') as bigint ) < 36000000  -- 限制单次停留时长大于0s且小于10h（去除异常值）
GROUP BY
    1,2,3;

--sql_divide_splitter--

CACHE TABLE dws_srp_duration_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance_exploded AS search_entrance
    ,SUM(duration) AS srp_duration
FROM
    dwd_srp_duration_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2;

--sql_divide_splitter--
-- pdp duration metrics --
CREATE TEMPORARY VIEW dwd_pdp_${grass_region_without_quote} AS
SELECT 
    userid AS user_id
    ,session_id
    ,event_timestamp
    ,CAST(GET_JSON_OBJECT(target_property, '$.duration') AS DOUBLE) AS duration
    ,CAST(GET_JSON_OBJECT(target_property_ext, '$.ctx_item_id') AS STRING) AS item_id
FROM
    traffic.shopee_traffic_dwd_click_hi__reg_s1_live
WHERE 
    local_date = ${local_date}
    and operation = 'stay_view'
    and page_type = 'product'
    and grass_region = ${grass_region};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_srp_click_${grass_region_without_quote} AS
select 
    userid AS user_id
    ,session_id
    ,event_timestamp
    ,GET_JSON_OBJECT(data,'$.search_FE.search_entrance.entrance') AS search_entrance
    ,cast(GET_JSON_OBJECT(data, '$.item.itemid') as STRING) as item_id
FROM
    traffic.shopee_traffic_dwd_click_hi__reg_s1_live
WHERE 
    local_date = ${local_date}
    AND operation = 'click'
    AND grass_region = ${grass_region}
    AND page_type = 'search'
    AND target_type = 'item'
    AND GET_JSON_OBJECT(data,'$.search_FE.search_params.search_scenario.key') 
        IN ('PAGE_GLOBAL_SEARCH','PAGE_PDP_SEARCH','PAGE_PREFILL_SEARCH');

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_pdp_duration_${grass_region_without_quote} AS
SELECT
    r.user_id
    ,IF(r.search_entrance IS NOT NULL AND TRIM(LOWER(r.search_entrance)) != '', TRIM(LOWER(r.search_entrance)), 'NA') AS search_entrance
    ,IF(TRIM(LOWER(r.search_entrance)) IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,SUM(duration) AS duration
FROM 
    dwd_srp_click_${grass_region_without_quote} r
LEFT JOIN
    dwd_pdp_${grass_region_without_quote} d
ON
    r.item_id = d.item_id
    AND r.session_id = d.session_id
    AND r.event_timestamp >= (d.event_timestamp-1000*60*10)
    AND r.event_timestamp <= d.event_timestamp
    AND r.user_id = d.user_id
GROUP BY
    1,2,3;

--sql_divide_splitter--

CACHE TABLE dws_pdp_duration_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance_exploded AS search_entrance
    ,SUM(duration) AS pdp_duration
FROM
    dwd_pdp_duration_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2;

--sql_divide_splitter--
-- video metrics --
CREATE TEMPORARY VIEW dwd_video_ads_ls_${grass_region_without_quote} AS
SELECT
    user_id
    ,sv_source_page
    ,SUM(video_play_cnt_ntl_1d) as vv
    ,SUM(video_view_duration_ntl_1d) as watch_time_ms
FROM
    video.video_mart_ads_bi_content_userid_cp_fs_ssp_vft_1d
WHERE 
    grass_region = ${grass_region}
    AND grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND grass_date = ${local_date}
    AND user_id IS NOT NULL
    AND user_id > 0
    AND tz_type = 'local'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_video_ls_${grass_region_without_quote} AS
SELECT
    user_id
    ,sv_source_page
    ,SUM(event_minils_play_vv_1d) as vv
    ,SUM(minils_watch_duration_1d) as watch_time_ms
FROM
    video.video_mart_dws_ls_content_minils_userid_cp_ssp_vft_aggr_1d
WHERE
    grass_region = ${grass_region}
    AND grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND grass_date = ${local_date}
    AND user_id IS NOT NULL
    AND user_id > 0
    AND tz_type = 'local'
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_video_ls_all_${grass_region_without_quote} AS
SELECT
    user_id
    ,sv_source_page
    ,SUM(vv) AS vv
    ,SUM(watch_time_ms) AS watch_time_ms
FROM (
    SELECT * FROM dwd_video_ads_ls_${grass_region_without_quote}
    UNION ALL
    SELECT * FROM dwd_video_ls_${grass_region_without_quote}
)
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_video_order_${grass_region_without_quote} AS
SELECT
    user_id
    ,GET_JSON_OBJECT(click_data, '$.params.sv_source_page') as sv_source_page
    ,SUM(video_order_fraction) as order
    ,SUM(gmv_usd) as gmv_usd
FROM
    mp_content_oa.dwd_video_order_omni_local_content_direct_final_detail_di
WHERE
    grass_region = ${grass_region}
    AND grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND grass_date = ${local_date}
    AND user_id IS NOT NULL
    AND user_id > 0
    AND tz_type = 'local'
    AND GET_JSON_OBJECT(click_video_property, '$.business_id') in ('1003', '1019')
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwm_video_metrics_${grass_region_without_quote} AS
SELECT
    COALESCE(a.user_id, b.user_id) AS user_id

    ,SUM(watch_time_ms) AS staytime
    ,SUM(CASE WHEN a.sv_source_page IN
        ('iaa_srp_video_card','iaa_srp_video_creator_banner','iaa_sup_creator_hint_keyword'
        ,'iaa_sdp_creator_hint_keyword','iaa_creator_hint_keyword') THEN watch_time_ms ELSE NULL
    END) AS staytime_all_srp
    ,SUM(CASE WHEN a.sv_source_page IN ('iaa_srp_video_card') THEN watch_time_ms ELSE NULL END) AS staytime_video_srp

    ,SUM(vv) AS vv
    ,SUM(CASE WHEN a.sv_source_page IN
        ('iaa_srp_video_card','iaa_srp_video_creator_banner','iaa_sup_creator_hint_keyword'
        ,'iaa_sdp_creator_hint_keyword','iaa_creator_hint_keyword') THEN vv ELSE NULL
    END) AS vv_all_srp
    ,SUM(CASE WHEN a.sv_source_page IN ('iaa_srp_video_card') THEN vv ELSE NULL END) AS vv_video_srp

    ,SUM(order) AS order
    ,SUM(CASE WHEN b.sv_source_page IN
        ('iaa_srp_video_card','iaa_srp_video_creator_banner','iaa_sup_creator_hint_keyword'
        ,'iaa_sdp_creator_hint_keyword','iaa_creator_hint_keyword') THEN order ELSE NULL
    END) AS order_all_srp
    ,SUM(CASE WHEN b.sv_source_page IN ('iaa_srp_video_card') THEN order ELSE NULL END) AS order_video_srp

    ,SUM(gmv_usd) AS gmv_usd
    ,SUM(CASE WHEN b.sv_source_page IN
        ('iaa_srp_video_card','iaa_srp_video_creator_banner','iaa_sup_creator_hint_keyword'
        ,'iaa_sdp_creator_hint_keyword','iaa_creator_hint_keyword') THEN gmv_usd ELSE NULL
    END) AS gmv_usd_all_srp
    ,SUM(CASE WHEN b.sv_source_page IN ('iaa_srp_video_card') THEN gmv_usd ELSE NULL END) AS gmv_usd_video_srp
FROM
    dwd_video_ls_all_${grass_region_without_quote} a
FULL JOIN
    dwd_video_order_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
    AND a.sv_source_page = b.sv_source_page
GROUP BY
    1;

--sql_divide_splitter--

CACHE TABLE dws_video_metrics_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,'__ALL__' AS card_type
    ,COALESCE(COUNT(CASE WHEN vv_all_srp > 0 THEN a.user_id ELSE NULL END), 0) AS search_to_video_viewer
    ,COALESCE(SUM(staytime_all_srp)) AS search_to_video_duration_time
    ,COALESCE(SUM(vv_all_srp), 0) AS search_to_video_vv
    ,COALESCE(SUM(order_all_srp), 0) AS search_to_video_order
    ,COALESCE(SUM(gmv_usd_all_srp), 0) AS search_to_video_gmv

    ,COALESCE(COUNT(CASE WHEN vv > 0 THEN a.user_id ELSE NULL END), 0) as all_video_side_viewer
    ,COALESCE(SUM(staytime), 0) as all_video_side_duration_time
    ,COALESCE(SUM(vv), 0) as all_video_side_vv
    ,COALESCE(SUM(order), 0) as all_video_side_order
    ,COALESCE(SUM(gmv_usd), 0) as all_video_side_gmv
FROM
    dwm_video_metrics_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2
UNION ALL
SELECT
    exp_group_id
    ,'video' AS card_type
    ,COALESCE(COUNT(CASE WHEN vv_video_srp > 0 THEN a.user_id ELSE NULL END), 0) AS search_to_video_viewer
    ,COALESCE(SUM(staytime_video_srp)) AS search_to_video_duration_time
    ,COALESCE(SUM(vv_video_srp), 0) AS search_to_video_vv
    ,COALESCE(SUM(order_video_srp), 0) AS search_to_video_order
    ,COALESCE(SUM(gmv_usd_video_srp), 0) AS search_to_video_gmv

    ,COALESCE(COUNT(CASE WHEN vv > 0 THEN a.user_id ELSE NULL END), 0) as all_video_side_viewer
    ,COALESCE(SUM(staytime), 0) as all_video_side_duration_time
    ,COALESCE(SUM(vv), 0) as all_video_side_vv
    ,COALESCE(SUM(order), 0) as all_video_side_order
    ,COALESCE(SUM(gmv_usd), 0) as all_video_side_gmv
FROM
    dwm_video_metrics_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2
UNION ALL
SELECT
    exp_group_id
    ,card_type
    ,search_to_video_viewer
    ,search_to_video_duration_time
    ,search_to_video_vv
    ,search_to_video_order
    ,search_to_video_gmv
    ,all_video_side_viewer
    ,all_video_side_duration_time
    ,all_video_side_vv
    ,all_video_side_order
    ,all_video_side_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_video_metrics_1d
WHERE
    grass_region = ${grass_region}
    AND grass_region IN ('BR', 'CO', 'CL', 'MX', 'AR')
    AND local_date = ${local_date};

--sql_divide_splitter--

CACHE TABLE dws_video_duration_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,'__ALL__' AS card_type
    ,SUM(watch_time_ms) AS video_duration
FROM
    dwd_video_ads_ls_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    a.sv_source_page IN (
        'iaa_srp_video_card'
        ,'iaa_srp_video_creator_banner'
        ,'iaa_sup_creator_hint_keyword'
        ,'iaa_sdp_creator_hint_keyword'
        ,'iaa_creator_hint_keyword'
    )
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,'video' AS card_type
    ,SUM(watch_time_ms) AS video_duration
FROM
    dwd_video_ads_ls_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    a.sv_source_page = 'iaa_srp_video_card'
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,card_type
    ,video_duration
FROM
    srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_video_metrics_1d
WHERE
    grass_region = ${grass_region}
    AND grass_region IN ('BR', 'CO', 'CL', 'MX', 'AR')
    AND local_date = ${local_date};

--sql_divide_splitter--
-- live metrics --
CREATE TEMPORARY VIEW dwd_live_view_${grass_region_without_quote} AS
SELECT
    viewer_id as user_id
    ,view_event_id as event_id
    ,sum(duration_b * 1000) as duration_b
FROM 
    livestream.ls_mart_dwd_view_streaming_detail_di a
WHERE
    tz_type = 'local'
    AND a.grass_region = ${grass_region}
    AND a.grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND a.grass_date = ${local_date}
    AND viewer_id IS NOT NULL
    AND viewer_id > 0
GROUP BY
    1, 2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_live_duration_pv_${grass_region_without_quote} AS
SELECT
    a.user_id AS user_id
    ,IF(GET_JSON_OBJECT(data,'$.live_scene_parameters.live_in_search.search_entrance') IS NOT NULL AND TRIM(LOWER(GET_JSON_OBJECT(data,'$.live_scene_parameters.live_in_search.search_entrance'))) != '', TRIM(LOWER(GET_JSON_OBJECT(data,'$.live_scene_parameters.live_in_search.search_entrance'))), 'NA') AS search_entrance
    ,CASE
        WHEN GET_JSON_OBJECT(data, '$.from_source') = 'global_search_srp_live_card_entry' THEN 1
        WHEN GET_JSON_OBJECT(data, '$.from_source') IN (
            'global_search_live_floating_entry'
            ,'pdp_search_live_floating_entry'
            ,'prefill_search_live_floating_entry'
            ,'other_search_live_floating_entry'
            ,'search_shop_entry'
            ,'search_kol_avatar_entry'
            ,'search_sup_creator_avatar_entry'
            ,'search_creator_page_avatar_entry'
        ) THEN 2
        ELSE 3
    END AS source_type
    ,SUM(duration_b) AS duration  -- duration_b单位为秒
    ,COUNT(1) AS view_pv
FROM 
    livestream.ls_mart_dwd_viewer_view_detail_di a 
LEFT JOIN
    dwd_live_view_${grass_region_without_quote} b 
ON
    a.user_id = b.user_id
    AND a.event_id = b.event_id
WHERE 
    grass_date = ${local_date}
    AND grass_region = ${grass_region}
    AND grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND tz_type = 'local'
    AND a.user_id IS NOT NULL
    AND a.user_id > 0
GROUP BY 
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_live_order_${grass_region_without_quote} AS
SELECT
    order_buyer_id AS user_id
    ,COALESCE(GET_JSON_OBJECT(click_data,'$.live_scene_parameters.live_in_search.search_entrance'),'NA') AS search_entrance
    ,CASE WHEN GET_JSON_OBJECT(click_data, '$.ctx_from_source') = 'global_search_srp_live_card_entry' THEN 1
        WHEN GET_JSON_OBJECT(click_data, '$.ctx_from_source') IN (
            'global_search_live_floating_entry'
            ,'pdp_search_live_floating_entry'
            ,'prefill_search_live_floating_entry'
            ,'other_search_live_floating_entry'
            ,'search_shop_entry'
            ,'search_kol_avatar_entry'
            ,'search_sup_creator_avatar_entry'
            ,'search_creator_page_avatar_entry'
        ) THEN 2
        ELSE 3
    END AS source_type
    ,SUM(ls_order_fraction) as order
    ,SUM(gmv_usd) as gmv_usd
FROM
    mp_content_oa.dwd_ls_order_omni_local_content_final_detail_di
where
    grass_date = ${local_date}
    AND grass_region = ${grass_region}
    AND grass_region IN ('ID', 'MY', 'PH', 'TH', 'TW', 'VN', 'SG')
    AND tz_type = 'local'
    AND order_cal_type = 'direct'
    AND is_content_directly_related = 1
GROUP BY
    1,2,3;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_live_order_flatten_${grass_region_without_quote} AS
SELECT
    user_id
    ,search_entrance
    ,source_type
    ,order
    ,gmv_usd
FROM
    dwd_live_order_${grass_region_without_quote}
UNION ALL
SELECT
    user_id
    ,IF(search_entrance IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS search_entrance
    ,source_type
    ,order
    ,gmv_usd
FROM
    dwd_live_order_${grass_region_without_quote};

--sql_divide_splitter--

CACHE TABLE dws_live_order_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,'livestream' AS card_type
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN order ELSE NULL END), 0) AS search_to_live_order
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN gmv_usd ELSE NULL END), 0) AS search_to_live_gmv
    ,COALESCE(SUM(gmv_usd), 0) AS all_live_side_gmv
    ,COALESCE(SUM(order), 0) AS all_live_side_order
FROM
    dwd_live_order_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,search_entrance
    ,'livestream' AS card_type
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN order ELSE NULL END), 0) AS search_to_live_order
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN gmv_usd ELSE NULL END), 0) AS search_to_live_gmv
    ,COALESCE(SUM(gmv_usd), 0) AS all_live_side_gmv
    ,COALESCE(SUM(order), 0) AS all_live_side_order
FROM
    dwd_live_order_flatten_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,'__ALL__' AS card_type
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN order ELSE NULL END), 0) AS search_to_live_order
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN gmv_usd ELSE NULL END), 0) AS search_to_live_gmv
    ,COALESCE(SUM(gmv_usd), 0) AS all_live_side_gmv
    ,COALESCE(SUM(order), 0) AS all_live_side_order
FROM
    dwd_live_order_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,search_entrance
    ,'__ALL__' AS card_type
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN order ELSE NULL END), 0) AS search_to_live_order
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN gmv_usd ELSE NULL END), 0) AS search_to_live_gmv
    ,COALESCE(SUM(gmv_usd), 0) AS all_live_side_gmv
    ,COALESCE(SUM(order), 0) AS all_live_side_order
FROM
    dwd_live_order_flatten_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL 
SELECT
    exp_group_id
    ,search_entrance
    ,card_type
    ,search_to_live_order
    ,search_to_live_gmv
    ,all_live_side_gmv
    ,all_live_side_order
FROM
    srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_livestream_metrics_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND grass_region IN ('BR', 'CL', 'CO', 'MX', 'AR');

--sql_divide_splitter--

CACHE TABLE dws_live_duration_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,IF(search_entrance IS NOT NULL, search_entrance, '__ALL__') AS search_entrance
    ,'__ALL__' AS card_type
    ,COALESCE(COUNT(DISTINCT CASE WHEN source_type IN (1,2) THEN a.user_id ELSE NULL END), 0) AS search_to_live_viewer
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN view_pv ELSE NULL END), 0) AS search_to_live_view_pv
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN duration ELSE NULL END), 0) AS search_to_live_duration_time
    ,COALESCE(COUNT(DISTINCT a.user_id), 0) AS all_live_side_viewer
    ,COALESCE(SUM(view_pv), 0) AS all_live_side_view_pv
    ,COALESCE(SUM(duration), 0) AS all_live_side_duration_time
FROM
    dwd_live_duration_pv_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY GROUPING SETS
    ((exp_group_id,search_entrance, card_type), (exp_group_id, card_type))
UNION ALL    
SELECT
    exp_group_id
    ,IF(search_entrance IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS search_entrance
    ,'__ALL__' AS card_type
    ,COALESCE(COUNT(DISTINCT CASE WHEN source_type IN (1,2) THEN a.user_id ELSE NULL END), 0) AS search_to_live_viewer
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN view_pv ELSE NULL END), 0) AS search_to_live_view_pv
    ,COALESCE(SUM(CASE WHEN source_type IN (1,2) THEN duration ELSE NULL END), 0) AS search_to_live_duration_time
    ,COALESCE(COUNT(DISTINCT a.user_id), 0) AS all_live_side_viewer
    ,COALESCE(SUM(view_pv), 0) AS all_live_side_view_pv
    ,COALESCE(SUM(duration), 0) AS all_live_side_duration_time
FROM
    dwd_live_duration_pv_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL
SELECT
    exp_group_id
    ,IF(search_entrance IS NOT NULL, search_entrance, '__ALL__') AS search_entrance
    ,'livestream' AS card_type
    ,COALESCE(COUNT(DISTINCT CASE WHEN source_type IN (1) THEN a.user_id ELSE NULL END), 0) AS search_to_live_viewer
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN view_pv ELSE NULL END), 0) AS search_to_live_view_pv
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN duration ELSE NULL END), 0) AS search_to_live_duration_time
    ,COALESCE(COUNT(DISTINCT a.user_id), 0) AS all_live_side_viewer
    ,COALESCE(SUM(view_pv), 0) AS all_live_side_view_pv
    ,COALESCE(SUM(duration), 0) AS all_live_side_duration_time
FROM
    dwd_live_duration_pv_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY GROUPING SETS
    ((exp_group_id, search_entrance, card_type), (exp_group_id, card_type))
UNION ALL    
SELECT
    exp_group_id
    ,IF(search_entrance IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS search_entrance
    ,'livestream' AS card_type
    ,COALESCE(COUNT(DISTINCT CASE WHEN source_type IN (1) THEN a.user_id ELSE NULL END), 0) AS search_to_live_viewer
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN view_pv ELSE NULL END), 0) AS search_to_live_view_pv
    ,COALESCE(SUM(CASE WHEN source_type IN (1) THEN duration ELSE NULL END), 0) AS search_to_live_duration_time
    ,COALESCE(COUNT(DISTINCT a.user_id), 0) AS all_live_side_viewer
    ,COALESCE(SUM(view_pv), 0) AS all_live_side_view_pv
    ,COALESCE(SUM(duration), 0) AS all_live_side_duration_time
FROM
    dwd_live_duration_pv_${grass_region_without_quote} a
INNER JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3
UNION ALL 
SELECT
    exp_group_id
    ,search_entrance
    ,card_type
    ,search_to_live_viewer
    ,search_to_live_view_pv
    ,search_to_live_duration_time
    ,all_live_side_viewer
    ,all_live_side_view_pv
    ,all_live_side_duration_time
FROM
    srdi_mart.dws_sr_data_warehouse_search_abtest_entrance_card_type_livestream_metrics_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND grass_region IN ('BR', 'CL', 'CO', 'MX');

--sql_divide_splitter--
-- search session level metrics --
CREATE TEMPORARY VIEW dwd_search_session_${grass_region_without_quote} AS
SELECT
    user_id
    ,search_session_id
    ,IF(search_entrance IS NOT NULL AND trim(lower(search_entrance)) != '', trim(lower(search_entrance)), 'NA') AS search_entrance
    ,IF(search_entrance IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,first_click_location
    ,max_imp_location
    ,search_time
FROM srdi_mart.dws_sr_data_warehouse_search_session_level_metircs_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND user_id > 0
    AND user_id IS NOT NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_first_location_${grass_region_without_quote} AS
SELECT
    user_id
    ,search_session_id
    ,first_click_location
    ,search_entrance
    ,is_content_entrance
    ,ROW_NUMBER() OVER(PARTITION BY user_id,search_session_id ORDER BY search_time ASC) AS click_time_rank
    ,ROW_NUMBER() OVER(PARTITION BY user_id,search_session_id,search_entrance ORDER BY search_time ASC) AS click_time_rank_tmp1
    ,ROW_NUMBER() OVER(PARTITION BY user_id,search_session_id,is_content_entrance ORDER BY search_time ASC) AS click_time_rank_tmp2
FROM
    dwd_search_session_${grass_region_without_quote}
WHERE
    first_click_location IS NOT NULL;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dwd_max_imp_location_${grass_region_without_quote} AS
SELECT
    user_id
    ,search_session_id
    ,search_entrance_exploded AS search_entrance
    ,MAX(max_imp_location) AS max_imp_location
FROM
    dwd_search_session_${grass_region_without_quote}
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
WHERE
    max_imp_location IS NOT NULL
GROUP BY
    1,2,3;

--sql_divide_splitter--

CACHE TABLE dws_first_location_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,'__ALL__' AS search_entrance
    ,AVG(first_click_location) as first_click_location_avg
    ,CASE
        WHEN COUNT(first_click_location) >= 1
        THEN ELEMENT_AT(SORT_ARRAY(COLLECT_LIST(first_click_location)), 1 + CAST(COUNT(first_click_location) / 2 AS INT))
        ELSE NULL
    END AS first_click_location_p50
FROM
    dwd_first_location_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    click_time_rank = 1
GROUP BY
    1,2
UNION ALL
SELECT
    exp_group_id
    ,search_entrance
    ,AVG(first_click_location) as first_click_location_avg
    ,CASE
        WHEN COUNT(first_click_location) >= 1
        THEN ELEMENT_AT(SORT_ARRAY(COLLECT_LIST(first_click_location)), 1 + CAST(COUNT(first_click_location) / 2 AS INT))
        ELSE NULL
    END AS first_click_location_p50
FROM
    dwd_first_location_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    click_time_rank_tmp1 = 1
GROUP BY
    1,2
UNION ALL
SELECT
    exp_group_id
    ,is_content_entrance AS search_entrance
    ,AVG(first_click_location) as first_click_location_avg
    ,CASE
        WHEN COUNT(first_click_location) >= 1
        THEN ELEMENT_AT(SORT_ARRAY(COLLECT_LIST(first_click_location)), 1 + CAST(COUNT(first_click_location) / 2 AS INT))
        ELSE NULL
    END AS first_click_location_p50
FROM
    dwd_first_location_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
WHERE
    click_time_rank_tmp2 = 1
GROUP BY
    1,2;

--sql_divide_splitter--

CACHE TABLE dws_max_imp_location_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,search_entrance 
    ,AVG(max_imp_location) AS max_imp_location_avg
    ,CASE
        WHEN count(max_imp_location) >= 1
        THEN ELEMENT_AT(SORT_ARRAY(COLLECT_LIST(max_imp_location)), 1 + CAST(COUNT(max_imp_location) / 2 AS INT))
        ELSE NULL
    END AS max_imp_location_p50
FROM
    dwd_max_imp_location_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2;

--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv995_v2_metrics_raw_${grass_region_without_quote} AS
SELECT
    user_id
    ,target_type AS card_type
    ,IF(is_ads IS NOT NULL, CAST(is_ads AS STRING), 'false') AS is_ads
    ,IF(search_entrance IS NOT NULL AND TRIM(LOWER(search_entrance)) != '', TRIM(LOWER(search_entrance)), 'NA') AS search_entrance
    ,IF(TRIM(LOWER(search_entrance)) IN ('live_search', 'video_search', 'content_mix_search'), 'all_content_search', 'not_content_search') AS is_content_entrance
    ,item_id
    ,order_id
    ,order_cnt
    ,gmv
    ,pc2_gmv
FROM
    srdi_mart.dws_sr_data_warehouse_platform_order_benchmark_1d
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND user_id > 0
    AND page_type IN ('global_search', 'search_prefill', 'search_in_pdp')
    AND page_section IS NULL
    AND target_type IN ('item', 'video', 'livestream');

--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv995_v2_outlier_${grass_region_without_quote} AS
SELECT
    is_ads
    ,category_tag
    ,gmv_995pct
    ,pc2_gmv_995pct
FROM 
    srdi_mart.dim_sr_data_warehouse_category_gmv_outlier
WHERE
    grass_region = ${grass_region}
    AND local_date = ${local_date}
    AND feature_group = 'dpm module Global Search business line Search';

--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv995_v2_item_order_grouped_${grass_region_without_quote} AS
SELECT
    user_id
    ,card_type_exploded AS card_type
    ,is_ads_exploded AS is_ads
    ,search_entrance_exploded AS search_entrance
    ,a.item_id AS item_id
    ,order_id
    ,COALESCE(category_tag, 'low gmv') AS category_tag
    ,COALESCE(SUM(order_cnt), 0.0) AS order_cnt
    ,COALESCE(SUM(gmv), 0.0) AS gmv
    ,COALESCE(SUM(pc2_gmv), 0.0) AS pc2_gmv
FROM
    gmv995_v2_metrics_raw_${grass_region_without_quote} a
LEFT JOIN
    srdi_mart.dim_sr_data_warehouse_item c
ON
    a.item_id = c.item_id
    AND c.local_date = ${local_date}
    AND c.grass_region = ${grass_region}
LATERAL VIEW
    EXPLODE(ARRAY(card_type, '__ALL__')) AS card_type_exploded
LATERAL VIEW
    EXPLODE(ARRAY(is_ads, '__ALL__')) AS is_ads_exploded
LATERAL VIEW
    EXPLODE(ARRAY(search_entrance, is_content_entrance, '__ALL__')) AS search_entrance_exploded
GROUP BY
    1,2,3,4,5,6,7;

--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv995_v2_user_level_filtered_${grass_region_without_quote} AS
SELECT
/*+ BROADCASTJOIN(b) */
    user_id
    ,card_type
    ,a.is_ads AS is_ads
    ,search_entrance
    ,a.category_tag AS category_tag
    ,SUM(IF(gmv <= gmv_995pct, order_cnt, 0)) AS gmv_order_cnt_995_v2
    ,SUM(IF(gmv <= gmv_995pct, gmv, gmv_995pct)) AS gmv_995_v2
    ,SUM(IF(pc2_gmv <= pc2_gmv_995pct, pc2_gmv, pc2_gmv_995pct)) AS pc2_gmv_995_v2
FROM
    gmv995_v2_item_order_grouped_${grass_region_without_quote} a
LEFT JOIN
    gmv995_v2_outlier_${grass_region_without_quote} b
ON
    a.is_ads = b.is_ads
    AND a.category_tag = b.category_tag
GROUP BY
    1,2,3,4,5;

--sql_divide_splitter--

CREATE TEMPORARY VIEW gmv995_v2_metrics_${grass_region_without_quote} AS
SELECT
    exp_group_id
    ,card_type
    ,search_entrance
    ,is_ads
    ,SUM(IF(category_tag = 'high gmv', gmv_order_cnt_995_v2, NULL)) AS high_gmv_order_cnt_995_v2
    ,SUM(IF(category_tag = 'high gmv', gmv_995_v2, NULL)) AS high_gmv_995_v2
    ,SUM(IF(category_tag = 'high gmv', pc2_gmv_995_v2, NULL)) AS high_pc2_gmv_995_v2
    ,SUM(IF(category_tag = 'low gmv', gmv_order_cnt_995_v2, NULL)) AS low_gmv_order_cnt_995_v2
    ,SUM(IF(category_tag = 'low gmv', gmv_995_v2, NULL)) AS low_gmv_995_v2
    ,SUM(IF(category_tag = 'low gmv', pc2_gmv_995_v2, NULL)) AS low_pc2_gmv_995_v2
FROM
    gmv995_v2_user_level_filtered_${grass_region_without_quote} a
JOIN
    user_exp_mapping_1d_${grass_region_without_quote} b
ON
    a.user_id = b.user_id
GROUP BY
    1,2,3,4;

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_search_abtest_entrance_card_type_other_metrics_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
    scene_id
    ,scene_name
    ,layer_id
    ,layer_name
    ,experiment_id
    ,experiment_name
    ,a.exp_group_id
    ,exp_group_name
    ,a.is_ads
    ,a.card_type
    ,a.search_entrance
    ,ads_revenue
    ,search_uu_1d
    ,retention_uu_1d
    ,search_uu_7d
    ,retention_uu_7d
    ,CAST(srp_duration AS DOUBLE) / CAST(search_uu AS DOUBLE) AS srp_duration_per_uu
    ,CAST(pdp_duration AS DOUBLE) / CAST(search_uu AS DOUBLE) AS pdp_duration_per_uu
    ,CAST(video_duration AS DOUBLE) / CAST(search_uu AS DOUBLE) AS video_duration_per_uu
    ,CAST(search_to_live_duration_time AS DOUBLE) / CAST(search_uu AS DOUBLE) AS live_duration_per_uu

    ,search_scene_imp_cnt
    ,paidads_imp_cnt
    ,gmv_995
    ,gmv_uu_995
    ,pc2_gmv_995
    ,pc2_gmv_uu_995
    ,norecall_rate

    ,search_to_live_viewer
    ,search_to_live_view_pv
    ,search_to_live_duration_time
    ,search_to_live_order
    ,search_to_live_gmv
    ,all_live_side_viewer
    ,all_live_side_view_pv
    ,all_live_side_duration_time
    ,all_live_side_order
    ,all_live_side_gmv

    ,search_to_video_viewer
    ,search_to_video_vv
    ,search_to_video_duration_time
    ,search_to_video_order
    ,search_to_video_gmv
    ,all_video_side_viewer
    ,all_video_side_vv
    ,all_video_side_duration_time
    ,all_video_side_order
    ,all_video_side_gmv

    ,max_imp_location_avg
    ,max_imp_location_p50
    ,first_click_location_avg
    ,first_click_location_p50

    ,high_gmv_order_cnt_995_v2
    ,high_gmv_995_v2
    ,high_pc2_gmv_995_v2
    ,low_gmv_order_cnt_995_v2
    ,low_gmv_995_v2
    ,low_pc2_gmv_995_v2
FROM
    dws_995_metrics_${grass_region_without_quote} a
LEFT JOIN
    dim_exp_${grass_region_without_quote} b
ON
    a.exp_group_id = b.exp_group_id
LEFT JOIN
    retention_exp_${grass_region_without_quote} c
ON
    a.exp_group_id = c.exp_group_id
    AND a.search_entrance = c.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_ads_performance_${grass_region_without_quote} d
ON
    a.exp_group_id = d.exp_group_id
    AND a.search_entrance = d.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_video_duration_${grass_region_without_quote} e
ON
    a.exp_group_id = e.exp_group_id
    AND a.search_entrance = e.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = e.card_type
LEFT JOIN
    dws_srp_duration_${grass_region_without_quote} f
ON
    a.exp_group_id = f.exp_group_id
    AND a.search_entrance = f.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_pdp_duration_${grass_region_without_quote} g
ON
    a.exp_group_id = g.exp_group_id
    AND a.search_entrance = g.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_live_duration_${grass_region_without_quote} h
ON
    a.exp_group_id = h.exp_group_id
    AND a.search_entrance = h.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = h.card_type
LEFT JOIN
    search_scene_exp_${grass_region_without_quote} m 
ON
    a.exp_group_id = m.exp_group_id
    AND a.search_entrance = m.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_norecall_rate_${grass_region_without_quote} n
ON
    a.exp_group_id = n.exp_group_id
    AND a.search_entrance = n.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_video_metrics_${grass_region_without_quote} o
ON
    a.exp_group_id = o.exp_group_id
    AND a.search_entrance = '__ALL__'
    AND a.is_ads = '__ALL__'
    AND a.card_type = o.card_type
LEFT JOIN
    dws_live_order_${grass_region_without_quote} p
ON
    a.exp_group_id = p.exp_group_id
    AND a.search_entrance = p.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = p.card_type
LEFT JOIN
    dws_first_location_${grass_region_without_quote} q
ON
    a.exp_group_id = q.exp_group_id
    AND a.search_entrance = q.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    dws_max_imp_location_${grass_region_without_quote} r
ON
    a.exp_group_id = r.exp_group_id
    AND a.search_entrance = r.search_entrance
    AND a.is_ads = '__ALL__'
    AND a.card_type = '__ALL__'
LEFT JOIN
    gmv995_v2_metrics_${grass_region_without_quote} s
ON
    a.exp_group_id = s.exp_group_id
    AND a.search_entrance = s.search_entrance
    AND a.is_ads = s.is_ads
    AND a.card_type = s.card_type;
