-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_nap_query_trending_1d
-- physical_table: srdi_mart.dwd_sr_data_warehouse_nap_query_trending_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dwd_sr_data_warehouse_nap_query_trending_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_nap_query_trending_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dwd_sr_data_warehouse_nap_query_trending_1d/analytics-mart-sr-data-warehouse/src/main/resources/dwd/dwd_sr_data_warehouse_nap_query_trending_1d.sql
-- deprecated: False
-- sha256: 5db414e61934a74784a870521289bf12956aef053d649a6ac3dce41c0fac327c
set cat_max_date = (select max(grass_date)  as max_date
from mkplsearch_data_product.trending_label_reg_daily_live
);

--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dwd_sr_data_warehouse_nap_query_trending_1d
partition (grass_region = ${grass_region}, local_date = ${local_date})
select  item_id
        ,ARRAY_DISTINCT(FROM_JSON(search_query_list, 'array<string>')) as search_query_list
        ,item_title
        -- 先聚合成 (rank, trending_keyword) 对，然后按 rank 排序
        ,transform(SORT_ARRAY(COLLECT_LIST(NAMED_STRUCT('rank', rank, 'keyword', trending_keyword))), x -> REGEXP_REPLACE(x.keyword, '^\'|\'+$', '')) as trending_keyword
        -- 先聚合 rank，再排序
        ,SORT_ARRAY(COLLECT_LIST(rank)) as trending_keyword_rank
        ,trending_type
        ,'pass' as qc_status
from    (
    select  CAST(task_data_item_id AS BIGINT) AS item_id
            ,task_data_item_title AS item_title
            ,task_data_trending_type AS trending_type
            ,task_data_trending_keyword AS trending_keyword
            ,cast(task_data_trending_keyword_rank as bigint) AS rank
            ,task_data_search_query_list AS search_query_list
    from    mkplsearch_data_product.trending_label_reg_daily_live
    where   grass_date = ${cat_max_date}
    and   project_name = 'Trend_Label_NAP'
    and   (completion_data_duplicated_meaning <> 'Yes'  or completion_data_duplicated_meaning is null)
    and   (completion_data_sensitive <> 'Yes'  or completion_data_sensitive is null)
    and   (completion_data_unclear <> 'Yes'  or completion_data_unclear is null)
    and   (completion_data_irrelevant <>'Yes'  or completion_data_irrelevant is null)
    and   huey_task_id <>'huey_task_id'
    group by 1, 2, 3, 4, 5, 6
)
group by item_id, item_title, trending_type, search_query_list
;
