-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d.sql
-- deprecated: False
-- sha256: cb41358c3421162ab0157c1165cd3563027503903ae2a4a390e82bd59c84f114
CREATE TEMPORARY VIEW user_exp_${grass_region_without_quote} as
select
    user_id
    ,exp_group_id
from
    srdi_mart.dim_sr_data_warehouse_abtest_user_group
where
    grass_region in (${grass_region})
    and local_date = ${local_date}
    and is_assignment_log = 1
    and scene_id = 142 -- daily_discover_main: 142
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_cluster_metrics_${grass_region_without_quote} as
select
    user_id
    ,item_llm_cluster_id
    ,case when is_ads = true then 'true' else 'false' end as is_ads
    ,case
        when array_contains(scenario_tags, 'dpm module Daily Discover business line Homepage') then 'DD'
        else 'Others'
     end as scene_type -- only DD for now
    ,sum(coalesce(omni_scenario_imp_cnt, 0)) as imp_cnt
    ,sum(coalesce(omni_scenario_click_cnt, 0)) as click_cnt
from
    srdi_mart.dwm_sr_data_warehouse_platform_user_item
where
    grass_region in (${grass_region})
    and local_date = ${local_date}
    and operation in ('omni_impression', 'omni_click')
    and array_contains(scenario_tags, 'dpm module Daily Discover business line Homepage')
    and user_id > 0
    and item_llm_cluster_id is not null
    and (omni_scenario_imp_cnt > 0 or omni_scenario_click_cnt > 0)
group by 1, 2, 3, 4
;

--sql_divide_splitter--
CREATE TEMPORARY VIEW user_bad_imp_${grass_region_without_quote} as
select
    user_id
    ,is_ads
    ,scene_type

    ,sum(imp_cnt) as imp_cnt
    ,sum(if(click_cnt = 0 and imp_cnt >= 20, imp_cnt, 0)) as imp_bad_cnt_20
    ,sum(if(click_cnt = 0 and imp_cnt >= 30, imp_cnt, 0)) as imp_bad_cnt_30
    ,sum(if(click_cnt = 0 and imp_cnt >= 40, imp_cnt, 0)) as imp_bad_cnt_40
from user_cluster_metrics_${grass_region_without_quote}
group by 1, 2, 3
;

--sql_divide_splitter--
insert overwrite table ${schema}.dws_sr_data_warehouse_platform_exp_level_imp_bad_rate_1d
partition (grass_region = ${grass_region}, local_date = ${local_date})

select
    exp_group_id
    ,scene_type
    ,coalesce(is_ads, '__ALL__') as is_ads
    ,sum(imp_cnt) as imp_cnt
    ,sum(imp_bad_cnt_20) as imp_bad_cnt_20
    ,sum(imp_bad_cnt_30) as imp_bad_cnt_30
    ,sum(imp_bad_cnt_40) as imp_bad_cnt_40
    ,sum(imp_bad_cnt_20)/sum(imp_cnt) as imp_bad_rate_20
    ,sum(imp_bad_cnt_30)/sum(imp_cnt) as imp_bad_rate_30
    ,sum(imp_bad_cnt_40)/sum(imp_cnt) as imp_bad_rate_40
from
    user_bad_imp_${grass_region_without_quote} as t1
inner join
    user_exp_${grass_region_without_quote} as t2
on t1.user_id = t2.user_id
group by grouping sets ((exp_group_id, scene_type, is_ads), (exp_group_id, scene_type))
