-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_antifraud_ovl_1h
-- physical_table: srdi_mart.dws_sr_data_warehouse_tc_antifraud_ovl_1h
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_tc_antifraud_ovl_1h
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_antifraud_ovl_1h.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_tc_antifraud_ovl_1h/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_tc_antifraud_ovl_1h.sql
-- deprecated: False
-- sha256: 3f1eebb4eeb876dd60f87ea59d06f2215afa0fba94510443ff2472b07b33bdd5



insert overwrite table ${schema}.dws_sr_data_warehouse_tc_antifraud_ovl_1h
partition (grass_region = ${grass_region}, local_date, local_hour, regional_date, regional_hour)
select  T1.shop_id as shop_id
        ,T1.update_time as update_time
        ,T2.placed_order_cnt_1d as avg_order_cnt_28d
        ,T1.order_limit_percentage as order_limit_percentage
        ,T1.order_limit_percentage/100 * coalesce(T2.placed_order_cnt_1d, 0) as order_ovl

        ,date(date_timezone_convert(${regional_date}, ${regional_hour}, 'SG', ${grass_region}, "yyyy-MM-dd")) as local_date
        ,cast(date_timezone_convert(${regional_date}, ${regional_hour}, 'SG', ${grass_region}, "HH") as int) as local_hour

        ,${regional_date} as regional_date
        ,${regional_hour} as regional_hour
from    (
    select  shop_id
            ,1.0000* order_limit / 10000 AS order_limit_percentage
            ,update_time
    from    ${table}
    where   punishment_status = 1
      and   region = ${grass_region}
) T1
left join (
    select  shop_id
            ,avg(placed_order_cnt_1d) as placed_order_cnt_1d
    from    mp_order.dws_seller_gmv_1d__reg_s0_live
    where   tz_type = 'local'
      and   grass_date BETWEEN date_sub(${local_date}, 29)
      and   date_sub(${local_date}, 2)
      and   grass_region = ${grass_region}
    group by shop_id
) T2
on      T1.shop_id = T2.shop_id
;
