-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
-- physical_table: srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_card_mab_analysis_1d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_search_card_mab_analysis_1d/analytics-mart-sr-data-warehouse/src/main/resources/dws_search/dws_sr_data_warehouse_search_card_mab_analysis_1d.sql
-- deprecated: False
-- sha256: 10b8a4c479b8b083ad8ecb494e2f86663fb4c1363e39305f3ce813b3c8313acb
-- DRD: https://confluence.shopee.io/pages/viewpage.action?pageId=2545624348
CREATE TEMPORARY VIEW dws_search_${grass_region_without_quote} AS
SELECT
    item_id
    ,CASE 
        WHEN image_id IS NOT NULL AND target_type = 'item' THEN image_id
        WHEN content_id IS NOT NULL AND target_type = 'video' THEN content_id
        ELSE 'NA'
    END AS content_id
    ,IF(is_ads = true, ads_id, 'not_ads') AS ads_id
    ,target_type AS card_type
    ,SUM(CASE WHEN operation = 'impression' THEN operation_cnt ELSE 0 END) AS imp_cnt
    ,SUM(CASE WHEN operation = 'click' THEN operation_cnt ELSE 0 END) AS click_cnt
    ,SUM(CASE WHEN operation = 'order' THEN operation_cnt ELSE 0 END) AS order_cnt
    ,SUM(CASE WHEN operation = 'order' THEN place_order_gmv ELSE 0 END) AS gmv 
    ,SUM(CASE WHEN operation = 'order' THEN pc2_gmv ELSE 0 END) AS pc2_gmv
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND page_section IS NULL
    AND target_type IN ('item', 'video', 'livestream')
    AND operation IN ('impression', 'click', 'order')
    AND item_id IS NOT NULL
    AND user_id > 0
GROUP BY 1,2,3,4
UNION ALL 
SELECT
    CAST(source1_ext_item_id AS BIGINT) AS item_id
    ,IF(source1_content_id IS NOT NULL AND source1_target_type = 'video', source1_content_id, 'NA') AS content_id
    ,IF(source1_is_ads = true,source1_ads_id, 'not_ads') AS ads_id
    ,source1_target_type AS card_type
    ,NULL AS imp_cnt 
    ,NULL AS click_cnt
    ,SUM(CASE WHEN operation = 'order' THEN operation_cnt ELSE 0 END) AS order_cnt
    ,SUM(CASE WHEN operation = 'order' THEN place_order_gmv ELSE 0 END) AS gmv 
    ,SUM(CASE WHEN operation = 'order' THEN pc2_gmv ELSE 0 END) AS pc2_gmv
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND source1_page_section IS NULL
    AND source1_page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND source1_target_type IN ('video', 'livestream')
    AND operation IN ('order')
    AND source1_ext_item_id IS NOT NULL
    AND user_id > 0
GROUP BY 1,2,3,4
UNION ALL 
SELECT
    CAST(source2_ext_item_id AS BIGINT) AS item_id
    ,IF(source2_content_id IS NOT NULL AND source2_target_type = 'video', source2_content_id, 'NA') AS content_id
    ,IF(source2_is_ads = true,source2_ads_id, 'not_ads') AS ads_id 
    ,source2_target_type AS card_type
    ,NULL AS imp_cnt 
    ,NULL AS click_cnt
    ,SUM(CASE WHEN operation = 'order' THEN operation_cnt ELSE 0 END) AS order_cnt
    ,SUM(CASE WHEN operation = 'order' THEN place_order_gmv ELSE 0 END) AS gmv 
    ,SUM(CASE WHEN operation = 'order' THEN pc2_gmv ELSE 0 END) AS pc2_gmv
FROM
    srdi_mart.dwd_sr_data_warehouse_search
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region}
    AND source2_page_section IS NULL
    AND source2_page_type IN ('global_search', 'search_in_pdp', 'search_prefill')
    AND source2_target_type IN ('video', 'livestream')
    AND operation IN ('order')
    AND source2_ext_item_id IS NOT NULL
    AND user_id > 0
GROUP BY 1,2,3,4;

--sql_divide_splitter--

CREATE TEMPORARY VIEW ads_type_${grass_region_without_quote} AS
SELECT
    ads_id
    ,max(sub_product_type) AS sub_product_type
FROM
    (
        SELECT
            *,
            row_number() over (partition by ads_id,grass_region order by placement DESC) as rn
        FROM
            mp_paidads.dim_advertise__reg_s0_live
        WHERE 
            tz_type = 'local'
            AND grass_date = ${local_date}
            AND grass_region = ${grass_region}
    )
WHERE 
    rn = 1
GROUP BY
    ads_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_video_${grass_region_without_quote} AS
SELECT
    DISTINCT item_id
FROM
    video.video_mart_dim_content_item_bind_df
WHERE
    grass_date = ${local_date}
    AND grass_region = ${grass_region}
    AND content_type = 'shopee_video'
    AND tz_type = 'local';

--sql_divide_splitter--

CREATE TEMPORARY VIEW raw_mab_${grass_region_without_quote} AS
SELECT
    items
    ,RANK() OVER (PARTITION  BY date ORDER BY grass_date DESC) AS rank_grass_date
FROM
    search_algo.search_video_competitive_item_candidate
WHERE
    grass_region = ${grass_region}
    AND date = ${local_date};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_mab_${grass_region_without_quote} AS
SELECT
DISTINCT
    item_id
FROM
    raw_mab_${grass_region_without_quote}
    lateral view explode(items) AS item_id
WHERE
    rank_grass_date = 1;

--sql_divide_splitter--

CREATE TEMPORARY VIEW dim_item_${grass_region_without_quote} AS
SELECT
    item_id 
    ,level1_global_be_category
    ,level1_global_be_category_id
FROM
    srdi_mart.dim_sr_data_warehouse_item
WHERE
    local_date = ${local_date}
    AND grass_region = ${grass_region};

--sql_divide_splitter--

CREATE TEMPORARY VIEW dws_item_${grass_region_without_quote} AS
SELECT
    a.item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,IF(d.item_id IS NOT NULL, TRUE, FALSE) AS has_video
    ,IF(e.item_id IS NOT NULL, TRUE, FALSE) AS skip_mab
    ,card_type
    ,content_id
    ,CASE 
        WHEN a.ads_id = 'not_ads' THEN 'not_ads'
        WHEN c.sub_product_type IS NOT NULL THEN c.sub_product_type
        ELSE 'NA'
    END AS sub_product_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv 
    ,SUM(pc2_gmv) AS pc2_gmv
FROM
    dws_search_${grass_region_without_quote} a 
    LEFT JOIN dim_item_${grass_region_without_quote} b
        ON a.item_id = b.item_id
    LEFT JOIN ads_type_${grass_region_without_quote} c 
        ON a.ads_id = c.ads_id
    LEFT JOIN dim_video_${grass_region_without_quote} d
        ON a.item_id = d.item_id 
    LEFT JOIN dim_mab_${grass_region_without_quote} e 
        ON a.item_id = e.item_id
GROUP BY 
    1,2,3,4,5,6,7,8;
    
--sql_divide_splitter--

CREATE TEMPORARY VIEW cube_data_${grass_region_without_quote} AS
SELECT
    item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,IF(card_type IS NULL, '__ALL__', card_type) AS card_type
    ,IF(content_id IS NULL, '__ALL__', content_id) AS content_id
    ,IF(sub_product_type IS NULL, '__ALL__', sub_product_type) AS sub_product_type
    ,SUM(imp_cnt) AS imp_cnt
    ,SUM(click_cnt) AS click_cnt
    ,SUM(order_cnt) AS order_cnt
    ,SUM(gmv) AS gmv 
    ,SUM(pc2_gmv) AS pc2_gmv
    ,COALESCE(SUM(click_cnt) / SUM(imp_cnt), 0)  AS ctr
    ,COALESCE(SUM(order_cnt) / SUM(click_cnt), 0) AS cr
    ,COALESCE(SUM(order_cnt) / SUM(imp_cnt), 0) AS ctr_x_cr
FROM 
    dws_item_${grass_region_without_quote}
GROUP BY GROUPING SETS (
    (item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, card_type, content_id, sub_product_type)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, card_type, content_id)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, card_type, sub_product_type)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, card_type)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, content_id, sub_product_type)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, content_id)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab, sub_product_type)
    ,(item_id, level1_global_be_category, level1_global_be_category_id, has_video, skip_mab)
);

--sql_divide_splitter--
    
CREATE TEMPORARY VIEW item_rank_data_${grass_region_without_quote} AS
SELECT
    *
    ,RANK() OVER (ORDER BY order_cnt DESC) AS item_order_rank
FROM 
    cube_data_${grass_region_without_quote}
WHERE
    card_type = '__ALL__'
    AND content_id = '__ALL__'
    AND sub_product_type = '__ALL__';

--sql_divide_splitter--

CREATE TEMPORARY VIEW content_rank_data_${grass_region_without_quote} AS
SELECT
    *
    ,RANK() OVER (PARTITION BY item_id, sub_product_type, card_type  ORDER BY ctr_x_cr DESC) AS ctr_x_cr_rank
FROM 
    cube_data_${grass_region_without_quote}
WHERE
    card_type IN ('item', 'video')
    AND content_id != '__ALL__';

--sql_divide_splitter--

CREATE TEMPORARY VIEW video_rank_data_${grass_region_without_quote} AS
SELECT
    *
FROM
    content_rank_data_${grass_region_without_quote}
WHERE
    card_type = 'video';

--sql_divide_splitter--

CREATE TEMPORARY VIEW video_dim_content_${grass_region_without_quote} AS
SELECT
    CAST(content_id AS STRING) AS content_id
    ,post_date
FROM
    video.video_mart_dim_content
WHERE
    grass_region = ${grass_region}
    AND grass_date = ${local_date}
    AND content_type = 'shopee_video';

--sql_divide_splitter--

CREATE TEMPORARY VIEW video_rank_data_dim_joined_${grass_region_without_quote} AS
SELECT
    item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,card_type
    ,COALESCE(a.content_id, b.content_id) AS content_id
    ,sub_product_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv 
    ,pc2_gmv
    ,ctr
    ,cr
    ,ctr_x_cr
    ,ctr_x_cr_rank
    ,post_date
    ,CASE
        WHEN DATEDIFF(${local_date}, post_date) <= 13 THEN TRUE
        WHEN DATEDIFF(${local_date}, post_date) > 13 THEN FALSE
        ELSE NULL
    END is_new_video
FROM
    video_rank_data_${grass_region_without_quote} a
FULL JOIN
    video_dim_content_${grass_region_without_quote} b
ON
    a.content_id = b.content_id;

--sql_divide_splitter--

CREATE TEMPORARY VIEW total_order_cnt_${grass_region_without_quote} AS
SELECT
    SUM(order_cnt) AS total_order_cnt
FROM
    item_rank_data_${grass_region_without_quote};

--sql_divide_splitter--

INSERT OVERWRITE TABLE srdi_mart.dws_sr_data_warehouse_search_card_mab_analysis_1d
PARTITION (
    grass_region = ${grass_region}
    ,local_date = ${local_date}
)
SELECT
	item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,card_type
    ,content_id
    ,sub_product_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv 
    ,pc2_gmv
    ,ctr
    ,cr
    ,ctr_x_cr
    ,NULL AS item_order_rank
    ,NULL AS item_order_quantile
    ,NULL AS image_ctr_x_cr_rank
    ,NULL AS video_ctr_x_cr_rank
    ,NULL AS item_cum_order_prop
    ,NULL AS post_date
    ,NULL AS is_new_video
FROM
    cube_data_${grass_region_without_quote}
WHERE
    (
        card_type != '__ALL__'
        OR content_id != '__ALL__'
        OR sub_product_type != '__ALL__'
    )
    AND (
        card_type NOT IN ('item', 'video')
        OR content_id = '__ALL__'
    )
UNION ALL 
SELECT
/*+ BROADCASTJOIN(total_order_cnt_${grass_region_without_quote}) */
	item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,card_type
    ,content_id
    ,sub_product_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv 
    ,pc2_gmv
    ,ctr
    ,cr
    ,ctr_x_cr
    ,item_order_rank
    ,item_order_rank / MAX(item_order_rank) OVER (PARTITION BY card_type, content_id, sub_product_type) AS item_order_quantile
    ,NULL AS image_ctr_x_cr_rank
    ,NULL AS video_ctr_x_cr_rank
    ,SUM(order_cnt) OVER (ORDER BY item_order_rank ASC) / total_order_cnt AS item_cum_order_prop
    ,NULL AS post_date
    ,NULL AS is_new_video
FROM
    item_rank_data_${grass_region_without_quote}
JOIN
    total_order_cnt_${grass_region_without_quote}
UNION ALL 
SELECT
	item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,card_type
    ,content_id
    ,sub_product_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv 
    ,pc2_gmv
    ,ctr
    ,cr
    ,ctr_x_cr
    ,NULL AS item_order_rank
    ,NULL AS item_order_quantile
    ,ctr_x_cr_rank AS image_ctr_x_cr_rank
    ,NULL AS video_ctr_x_cr_rank
    ,NULL AS item_cum_order_prop
    ,NULL AS post_date
    ,NULL AS is_new_video
FROM
    content_rank_data_${grass_region_without_quote}
WHERE
    card_type = 'item'
UNION ALL 
SELECT
	item_id
    ,level1_global_be_category
    ,level1_global_be_category_id
    ,has_video
    ,skip_mab
    ,card_type
    ,content_id
    ,sub_product_type
    ,imp_cnt
    ,click_cnt
    ,order_cnt
    ,gmv 
    ,pc2_gmv
    ,ctr
    ,cr
    ,ctr_x_cr
    ,NULL AS item_order_rank
    ,NULL AS item_order_quantile
    ,NULL AS image_ctr_x_cr_rank
    ,ctr_x_cr_rank AS video_ctr_x_cr_rank
    ,NULL AS item_cum_order_prop
    ,CAST(post_date AS DATE) AS post_date
    ,is_new_video
FROM
    video_rank_data_dim_joined_${grass_region_without_quote};
