-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_explore_item_nd
-- physical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_explore_item_nd
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_ni_boost_explore_item_nd
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_ni_boost_explore_item_nd.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_ni_boost_explore_item_nd/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_ni_boost_explore_item_nd.sql
-- deprecated: False
-- sha256: 2f23c14eb673898bdb1b30235b824b2d99cf92d516178859238334869724addc
CREATE TEMPORARY VIEW all_new_item_${grass_region_without_quote} AS
select
     exp_tag
    ,item_id
    ,create_time
from(
    select
         item_id
        ,item_create_timestamp as create_time
    from srdi_mart.dim_sr_data_warehouse_item
    where grass_region in (${grass_region}) and local_date = ${local_date}
    and datediff(${local_date}, from_unixtime(item_create_timestamp, 'yyyy-MM-dd')) < 90
) a
lateral view explode(array('T1')) b as exp_tag
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW before_data_${grass_region_without_quote} AS
select
     exp_tag
    ,item_id
    ,create_time
    ,platform_imp_cnt
    ,explore_imp_cnt
    ,explore_click_cnt
    ,explore_order_cnt
from srdi_mart.dws_sr_data_warehouse_ni_boost_explore_item_nd
WHERE grass_region IN (${grass_region}) AND regional_date = date_add(${local_date}, -1)
and datediff(${local_date}, from_unixtime(create_time, 'yyyy-MM-dd')) <= 90 -- 剔除超期的，减轻存储负担
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW today_data_raw_${grass_region_without_quote} AS
select
     exp_tag
    ,item_id
    ,imp_cnt   as explore_imp_cnt
    ,click_cnt as explore_click_cnt
    ,order_cnt as explore_order_cnt
from srdi_mart.dws_sr_data_warehouse_ni_boost_offline_common_1d
WHERE grass_region IN (${grass_region}) AND regional_date = ${local_date}
and exp_tag like 'T%'
;
--sql_divide_splitter--

CREATE TEMPORARY VIEW today_data_${grass_region_without_quote} AS
select
     a.exp_tag
    ,a.item_id
    ,a.create_time
    ,b.platform_imp_cnt
    ,explore_imp_cnt
    ,explore_click_cnt
    ,explore_order_cnt
from all_new_item_${grass_region_without_quote} a
left join (
    select
         item_id
        ,sum(imp_cnt) as platform_imp_cnt
    from srdi_mart.dws_sr_data_warehouse_ni_boost_offline_common_1d
    WHERE grass_region IN (${grass_region}) AND regional_date = ${local_date}
    group by item_id
) b on a.item_id=b.item_id
left join today_data_raw_${grass_region_without_quote} c on a.exp_tag=c.exp_tag and a.item_id=c.item_id
;
--sql_divide_splitter--

INSERT OVERWRITE TABLE ${schema}.dws_sr_data_warehouse_ni_boost_explore_item_nd PARTITION (grass_region = ${grass_region}, regional_date = ${local_date})
select
     exp_tag
    ,item_id
    ,max(create_time)       as create_time
    ,sum(platform_imp_cnt)  as platform_imp_cnt
    ,sum(explore_imp_cnt)   as explore_imp_cnt
    ,sum(explore_click_cnt) as explore_click_cnt
    ,sum(explore_order_cnt) as explore_order_cnt
from (
   select
   *
   from before_data_${grass_region_without_quote}
   union all
   select
   *
   from today_data_${grass_region_without_quote}
) a
group by exp_tag,item_id
;
