-- Generated by pipeline/25_promote_srdi_assets.py
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_item_level_ppv_layer_30d
-- physical_table: srdi_mart.dws_sr_data_warehouse_platform_item_level_ppv_layer_30d
-- source_count: 1
-- Source priority: full Spark SQL from analytics-mart-spark.

-- ====== ETL SOURCE BOUNDARY ======
-- canonical_table: srdi_mart.dws_sr_data_warehouse_platform_item_level_ppv_layer_30d
-- source_index: 1
-- source_relative_path: analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_item_level_ppv_layer_30d.sql
-- snapshot_path: data/domains/srdi/snapshots/etl/dws_sr_data_warehouse_platform_item_level_ppv_layer_30d/analytics-mart-sr-data-warehouse/src/main/resources/dws/dws_sr_data_warehouse_platform_item_level_ppv_layer_30d.sql
-- deprecated: False
-- sha256: 77d87b6eba10ec0643510d70dfff4fd70dc625fc2828fd08ecaea8d862a59638
create temporary view item_level_benchmark_7d_${grass_region_without_quote} as
select
    item_id
    ,shop_id
    ,level1_global_be_category_id
    ,level2_global_be_category_id
    ,level3_global_be_category_id
    ,level4_global_be_category_id
    ,level5_global_be_category_id
    ,level1_global_be_category
    ,level2_global_be_category
    ,level3_global_be_category
    ,level4_global_be_category
    ,level5_global_be_category
    ,ppv_cnt_exclude_isback
    ,order_cnt
    ,local_date
from
    srdi_mart.dws_sr_data_warehouse_platform_item_level_benchmark_1d
where
    grass_region = ${grass_region}
    and local_date between date_sub(${local_date}, 6) and ${local_date}
    and item_id is not null
    and feature_detail = '__ALL__'
    and scenario_tag = '__ALL__'
;

--sql_divide_splitter--
create temporary view item_info_7d_${grass_region_without_quote} as
select
    item_id
    ,shop_id
    ,level1_global_be_category_id
    ,level2_global_be_category_id
    ,level3_global_be_category_id
    ,level4_global_be_category_id
    ,level5_global_be_category_id
    ,level1_global_be_category
    ,level2_global_be_category
    ,level3_global_be_category
    ,level4_global_be_category
    ,level5_global_be_category
    ,row_number() over(partition by item_id order by local_date desc) as rn
from
    item_level_benchmark_7d_${grass_region_without_quote}
;

--sql_divide_splitter--
create temporary view item_metrics_7d_${grass_region_without_quote} as
select
    item_id
    ,sum(ppv_cnt_exclude_isback) as total_ppv_l7d
    ,sum(order_cnt) as order_counts_l7d
from
    item_level_benchmark_7d_${grass_region_without_quote}
group by
    item_id
having
    total_ppv_l7d > 0
;

--sql_divide_splitter--
create temporary view item_metrics_7d_window_${grass_region_without_quote} as
select
    item_id
    ,total_ppv_l7d
    ,order_counts_l7d
    ,sum(total_ppv_l7d) over(order by total_ppv_l7d desc) as running_total_ppv
from
    item_metrics_7d_${grass_region_without_quote}
;

--sql_divide_splitter--
create temporary view all_item_metrics_7d_${grass_region_without_quote} as
select
/*+ REPARTITION(1) */
    sum(ppv_cnt_exclude_isback) as all_item_total_ppv_cnt
from
    item_level_benchmark_7d_${grass_region_without_quote}
;

--sql_divide_splitter--
create temporary view item_metrics_30d_${grass_region_without_quote} as
select
    item_id
    ,sum(ppv_cnt_exclude_isback) as total_ppv_l30d
    ,sum(order_cnt) as order_counts_l30d
from
    srdi_mart.dws_sr_data_warehouse_platform_item_level_benchmark_1d
where
    grass_region = ${grass_region}
    and local_date between date_sub(${local_date}, 29) and ${local_date}
    and item_id is not null
    and feature_detail = '__ALL__'
    and scenario_tag = '__ALL__'
group by
    item_id
;

--sql_divide_splitter--
insert overwrite table ${schema}.dws_sr_data_warehouse_platform_item_level_ppv_layer_30d
partition (local_date = ${local_date}, grass_region = ${grass_region})

select
    t1.item_id
    ,shop_id
    ,level1_global_be_category_id
    ,level2_global_be_category_id
    ,level3_global_be_category_id
    ,level4_global_be_category_id
    ,level5_global_be_category_id
    ,level1_global_be_category
    ,level2_global_be_category
    ,level3_global_be_category
    ,level4_global_be_category
    ,level5_global_be_category
    ,total_ppv_l7d
    ,total_ppv_l30d
    ,order_counts_l7d
    ,order_counts_l30d
    ,case
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 1 then '10%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 2 then '20%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 3 then '30%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 4 then '40%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 5 then '50%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 6 then '60%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 7 then '70%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 8 then '80%'
        when running_total_ppv < all_item_total_ppv_cnt / 10 * 9 then '90%'
        else '100%'
     end as ppv_percent
from
    item_metrics_7d_window_${grass_region_without_quote} as t1
left join
    all_item_metrics_7d_${grass_region_without_quote} as t2
left join
    item_metrics_30d_${grass_region_without_quote} as t3
on
    t1.item_id = t3.item_id
left join
    (select * from item_info_7d_${grass_region_without_quote} where rn = 1) as t4
on
    t1.item_id = t4.item_id
;
